### ISSUE TITLE
getWithRedirect is creating a cookie with invalid double quote characters

### ISSUE THREAD

**Issue by damien-gl** [okta/okta-auth-js#100]
[getWithRedirect](https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L545) function is creating a cookie with stringified JSON object which results in invalid double quote characters in the cookie which are not allowed as per [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1) and are causing issues.

Can you please encode the stringified JSON object (e.g. in base64 or via encodeURIComponent) before storing it in the cookie?

Thanks in advance for your support.

**Comment by jmelberg-okta** [comment]
Resolved with [`2.0.0`](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-2.0.0).
