### ISSUE TITLE
429 Too many requests: How autoRenew and syncStorage works together?

### ISSUE THREAD

**Issue by darkowic** [okta/okta-auth-js#1001]
Hi!
I am debugging an issue with a 429 (Too many requests) error from Okta APIs. When there are multiple tabs opened, we sometimes hit the limit.

We use localStorage for sessions storage which means [syncStorage](https://github.com/okta/okta-auth-js#syncstorage) is enabled. We have [autoRenew](https://github.com/okta/okta-auth-js#autorenew) enabled as well. I made sure the service start is called.

I noticed that if there are multiple tabs opened, each tab is doing a separate call to get the token in the background. And if there are many tabs - we have 429. Is this expected behavior or a bug? I would expect only one tab is syncing and other tabs just waiting for new tokens.

**Comment by monde** [comment]
@darkowic can you check out Okta's rate limit overview and let me know if you think your app is running up to a rate limit on your org? The API 429's signal the request has hit a rate limits. See:
https://developer.okta.com/docs/reference/rate-limits/

Additionally, all of the categories of endpoints are granular on specific endpoints, see:
* https://developer.okta.com/docs/reference/rl-global-mgmt/
* https://developer.okta.com/docs/reference/rl-global-enduser/
* https://developer.okta.com/docs/reference/rl-global-other-endpoints/

Rate limits occur in one minute buckets and reset after one minute. Currently, spiking/surging is not tolerated. 

There are rate limit metrics in the HTTP headers also:
https://developer.okta.com/docs/reference/rl-best-practices/

**Comment by darkowic** [comment]
I believe we hit this limit:
> End-user rate limits: Okta limits the number of requests from the Admin Console and End-User Dashboard to 40 requests per user per 10 seconds per endpoint.

And I'm sure it is 429 - I receive the exact network error with this code and description. I can reproduce it by opening around 15 tabs and simulating token renew in all of them at the same time (By setting expireEarlySeconds).

We can not prevent users to open that many tabs ;) For sure we have to handle it differently in the case when auto-renew is disabled (proper logout page) but **the question here is how should it work when syncStorage is enabled?** I would expect only the primary tab will fetch the new token and all others will just wait for the primary tab to finish its job.

**Comment by shuowu** [comment]
@darkowic Thanks for reporting the issue! It does sound like a bug, probably some request cancelling mechanism should be implemented from the SDK end. We'll investigate on it. Meanwhile, please turn off the `syncStorage` option if it keeps causing rate limit issue.

Internal Ref: OKTA-445148

**Comment by darkowic** [comment]
> please turn off the syncStorage option if it keeps causing rate limit issue.

It will not change anything as it works right now like there is no sync between tabs at all ;) If this case is not handled then looks like syncStorage is not doing anything at all. This scenario is the main use-case I can imagine for syncing between tabs :/

**Comment by koswedo** [comment]
This problem will become a blocker as mentioned in https://developer.okta.com/docs/reference/rl-clientbased/#what-to-monitor-and-the-action-to-take:

> Note: In March 2022, the default client-based rate limit for the OAuth 2.0 /authorize and /login/login.htm endpoints is going to be elevated to Enforce limit and log per client (recommended) mode. This means that if an org's client-based rate limit was previously set to Do nothing or Log per client, the setting is going to change to Enforce limit and log per client (recommended) mode.

Do you have any timeline for solving this issue?

**Comment by darkowic** [comment]
Any update? March 2022 is close and this will become a problem for many

**Comment by shuowu** [comment]
Fix released in [v6.2](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-6.2.0).
