### ISSUE TITLE
signInWithCredentials on 403 response from okta missing AuthApiError data

### ISSUE THREAD

**Issue by photchkiss** [okta/okta-auth-js#1029]
We are using `"@okta/okta-auth-js": "^5.4.3"` of okta-auth-js. 

signInWithCredentials calls api/v1/authn. If we use a bad username and password, the AuthApiError is fully inflated with data. However, if an IP is in the global block list, and api/v1/auth returns a 403 Forbidden, the ApiAuthError contains no data. All properties are empty. We are looking to redirect the user to some sort of oops page in the event a 403 is returned, but because no xhr is populated when a forbidden status is provided, we instead are checking for xhr being undefined on the AuthApiError and assuming that's the 403 response status. 

## signInWithCredentials - bad credentials xhr
```json
{
    "name": "AuthApiError",
    "errorSummary": "Authentication failed",
    "errorCode": "E0000004",
    "errorLink": "E0000004",
    "errorId": "oaeeBDIrNsUTmaQOioKD4_O0g",
    "errorCauses": [],
    "xhr": {
        "responseText": "{\"errorCode\":\"E0000004\",\"errorSummary\":\"Authentication failed\",\"errorLink\":\"E0000004\",\"errorId\":\"oaeeBDIrNsUTmaQOioKD4_O0g\",\"errorCauses\":[]}",
        "status": 401,
        "headers": {
            "cache-control": "no-cache, no-store",
            "content-type": "application/json",
            "expires": "0",
            "pragma": "no-cache"
        },
        "responseType": "json",
        "responseJSON": {
            "errorCode": "E0000004",
            "errorSummary": "Authentication failed",
            "errorLink": "E0000004",
            "errorId": "oaeeBDIrNsUTmaQOioKD4_O0g",
            "errorCauses": []
        }
    }
}
``` 
## signInWithCredentials - 403 xhr
```json
{
    "name": "AuthApiError"
}
```

I would expect the 403 to also include xhr information, but instead its undefined.

**Comment by aarongranick-okta** [comment]
@photchkiss Thank you for this submission. Hopefully we can provide better error information in this case. I've created an internal issue for tracking: OKTA-453297. Our engineers will investigate and see what options we can provide.

**Comment by shuowu** [comment]
Hi @photchkiss, the 403 error fails at the `preflight` stage, and the `status code` is hidden from the fetch client for security reason. You can find more information in [this thread](https://github.com/whatwg/fetch/issues/443).

You still are able to find information like `TypeError: failed to parse ...` from `error.xhr` field, but it's pretty vague information which can only tell you the preflight request fails. 

auth-js SDK exposes option to let you customize the default request client implementation, you can try with the [httpRequestClient](https://github.com/okta/okta-auth-js#httprequestclient) option to see if it can be a workaround.
