### ISSUE TITLE
changePassword an resetPassword methods not available in AuthTransaction object

### ISSUE THREAD

**Issue by fseee** [okta/okta-auth-js#1042]
Hi All
I'm implementing change/reset password workflows in our application, which uses the [okta-auth-js](https://github.com/okta/okta-auth-js) 5.9.1 version.
According to [this](https://github.com/okta/okta-auth-js/blob/master/docs/authn.md#changepasswordoptions), I need an instance of an AuthTransaction object which should be the result of e.g. the [signInWithCredentials](https://github.com/okta/okta-auth-js/blob/master/docs/authn.md#signinwithcredentialsoptions) method.
Below is the code (which is working fine to login workflow):

```
changePassword(currentPassword: string, newPassword: string, username: string) {
    return this.oAuth.signInWithCredentials({
        username: username,
        password: currentPassword
    }).then((response) => {
        if (response.status === 'SUCCESS') {
            return response.changePassword({
                oldPassword: currentPassword,
                newPassword
            })
            .then((res) => {
                console.log(res);
            }).catch((err) => {
                console.log(err);
            })
        }
    }).catch((err) => {
        console.error(err);
    })
}
```

The issue is that the AuthTransaction object **_response_** is not listing any of the functions starting from [this](https://github.com/okta/okta-auth-js/blob/HEAD/docs/authn.md#changepasswordoptions), so the changePassword method call will result in a _response.changePassword is not a function_.
As well as [reset](https://github.com/okta/okta-auth-js/blob/HEAD/docs/authn.md#resetpasswordoptions) which is not listed as mentioned above.
Is the availability of above methods the result of something to be enabled from okta administration console or this is to be considered an issue?
Thanks for you attention and replies.
Cheers

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the report @fseee.

`changePassword` method is available on AuthTransaction instance during sign in in case administrator resets password for the user.

`resetPassword` is created on AuthTransaction instance when user initiates [`forgotPassword`](https://github.com/okta/okta-auth-js#forgotpasswordoptions) flow.

Hope this helps.

**Comment by fseee** [comment]
Thanks for your replies.
So if a user would change its own password from self this method is not available?
How can this could be achieved?
Thanks

**Comment by oleksandrpravosudko-okta** [comment]
Right, password change (other than forgot password flow) can not be initiated by user.
In case your setup includes back-end, you could try utilizing Okta Management API method: [changePassword](https://github.com/okta/okta-sdk-nodejs/blob/master/src/types/generated-client.d.ts#L552).

**Comment by fseee** [comment]
Many thanks, this has been solved as above explained
