### ISSUE TITLE
resetPassword method not triggering any error if user does not exist

### ISSUE THREAD

**Issue by fseee** [okta/okta-auth-js#1044]
As mentioned in the subject, calling the [forgotPassword](https://github.com/okta/okta-auth-js#forgotpasswordoptions) passing a non existing username, will not throw any error as the response will be always below:

```
{
    "status": "RECOVERY_CHALLENGE",
    "factorResult": "WAITING",
    "factorType": "EMAIL",
    "recoveryType": "PASSWORD"
}
```

whether username exists or whether not.
Is this the expected behaviour or a "non existing user" error should be thrown?

Thanks

**Comment by aarongranick-okta** [comment]
@fseee Thanks for the question. I believe this behavior is expected when "User Enumeration Prevention" feature is turned on: https://help.okta.com/oie/en-us/Content/Topics/Security/Security_General.htm?cshid=csh_security_general

This feature prevents "fishing" for valid user accounts by malicious actors.

You can view/modify this setting under `Security > General` in the Okta Admin UI
