### ISSUE TITLE
Does  okta-auth-js Support angular.js (1.x)  ? 

### ISSUE THREAD

**Issue by r-kotagudem** [okta/okta-auth-js#1076]
any sample reference implementations or example?

**Comment by oleksandrpravosudko-okta** [comment]
Hi @r-kotagudem, there are no Okta-maintained AngularJS samples I am aware of.
According to this [post](https://www.phpflow.com/misc/angular/okta-authentication-using-angularjs-or-javascript/), okta-auth-js@5.2.3 can be used in AngularJS app.
