### ISSUE TITLE
Samples link in docs/idx.md

### ISSUE THREAD

**Issue by olecom** [okta/okta-auth-js#1098]
https://github.com/okta/okta-auth-js/blob/master/docs/idx.md?plain=1#L3

> [Embedded auth with SDKs[: https://github.com/okta/okta-auth-js/tree/master/samples/generated/express-direct-auth

There is no `express-direct-auth` any more, which one is successor of it in https://github.com/okta/okta-auth-js/tree/master/samples/generated ?

express-embedded-auth-with-sdk
express-embedded-sign-in-widget
express-web-no-oidc
express-web-with-oidc
static-spa
webpack-spa

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for pointing this out @olecom.
It should be updated to `express-embedded-auth-with-sdk`.
