### ISSUE TITLE
Question : Can we use other SSO like google and github with this library.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [okta/okta-auth-js#1099]
In our project we support multiple SSO, So just wanted to know will this library support the Google and Github SSO.

**Comment by oleksandrpravosudko-okta** [comment]
Hi @Sachin-chaurasiya. This SDK is intended to work with Okta as SSO provider.
Just in case you are referring to Google and GitHub as IdP providers, than yes, they can be used through `idp` [parameter](https://github.com/okta/okta-auth-js#authorize-options) passed to `signIn*` method.

**Comment by Sachin-chaurasiya** [comment]
Thank you @oleksandrpravosudko-okta, for your quick response.
