### ISSUE TITLE
High severity vulnerability found with node-fetch

### ISSUE THREAD

**Issue by cmacdonnacha** [okta/okta-auth-js#1111]
There is a High severity vulnerability with the current node-fetch package being used, which is throwing dependabot alerts.

See [github advisory here](https://github.com/advisories/GHSA-r683-j2x4-v87g)

## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Vulnerability exists

## Expected behavior
Vulnerability is patched. Upgrading to version `3.1.1` should be enough.

**Comment by denysoblohin-okta** [comment]
okta-auth-js version 6.1.0 depends on [`cross-fetch@3.1.5`](https://github.com/okta/okta-auth-js/pull/1103) which uses vuln-free `node-fetch 2.6.7`

**Comment by denysoblohin-okta** [comment]
However old version of node-fetch left in yarn.lock, will be fixed in next version of okta-auth-js
Internal ref: OKTA-470146
