### ISSUE TITLE
Non-JWT access_token throws error in okta-auth-js

### ISSUE THREAD

**Issue by timiles** [okta/okta-auth-js#1119]
### Describe the bug?

My Identity Provider issues an `access_token` which isn't in JWT format, but okta-auth-js tries to [decode it as JWT](https://github.com/okta/okta-auth-js/blob/1478c1930c4034d0033f5af740dc996cbe58ceb5/lib/oidc/handleOAuthResponse.ts#L90), and [throws an error when it fails to decode](https://github.com/okta/okta-auth-js/blob/9831eb1362dc4674071bc0aa8fe058b9339a18f3/lib/oidc/decodeToken.ts#L28).

### What is expected to happen?

From the auth0 blog:

[Note: Access Tokens should be treated as opaque strings by clients. They are only meant for the API. Your client should not attempt to decode them or depend on a particular access_token format.](https://auth0.com/blog/why-should-use-accesstokens-to-secure-an-api/)

So I would expect a non-JWT access_token to be left alone.

### What is the actual behavior?

An error is thrown ([`AuthSdkError('Malformed token')`](https://github.com/okta/okta-auth-js/blob/9831eb1362dc4674071bc0aa8fe058b9339a18f3/lib/oidc/decodeToken.ts#L28)).

### Reproduction Steps?

I'm using PKCE flow with an Identity Provider issuing GUID format access_tokens. I don't have control of the Identity Provider so would not be able to provide a reproduction repo here, but I could supply sample client code if that will help.

### SDK Versions

    "@okta/okta-auth-js": "^6.0.0",
    "@okta/okta-react": "^6.4.2",

### Execution Environment

Browser

### Additional Information?

Note that I don't have control of the Identity Provider, so changing the format of the access_token is not an option for me.

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the report @timiles.

This SDK works with Okta-issued tokens. Does your setup allow to [register](https://developer.okta.com/docs/guides/add-an-external-idp/openidconnect/main/) external Identity Provider in Okta org?

**Comment by timiles** [comment]
Hi @oleksandrpravosudko-okta, ok that explains the difference, I was hoping Okta was a spec-compliant library for generic use. I believe another part of the business is using the external IdP with Okta so maybe something can be done, but otherwise I'll find a different library to use. Thanks!
