### ISSUE TITLE
'Unable to parse a token from the url' error can be misleading

### ISSUE THREAD

**Issue by robertjd** [okta/okta-auth-js#112]
In the callback handler, we error if we can't pull the tokens from the callback url OR we can't read the cookie where we stored the state/nonce for the authorize url:

https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L602-L605

If you manually created the authorize URL outside of this library you will get this error because the cookie was not created.

We should have a more specific error for the cookie error case, to clue the developer into the fact that we can't process a callback URL without that cookie.

**Comment by jmelberg-okta** [comment]
Resolved with [`2.0.0`](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-2.0.0).
