### ISSUE TITLE
ES modules not working with Next.js

### ISSUE THREAD

**Issue by asanabria-hc** [okta/okta-auth-js#1188]
### Describe the bug?

Using ES Module like stated in documentation: 

```javascript
// ES module
import { OktaAuth } from '@okta/okta-auth-js'
const authClient = new OktaAuth(/* configOptions */) 
```
Results in the following error: 
```
error - SyntaxError: Named export 'BroadcastChannel' not found. The requested module 'broadcast-channel' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'broadcast-channel';
const { BroadcastChannel, createLeaderElection } = pkg;
```

### What is expected to happen?

The application runs properly.

### What is the actual behavior?

The application breaks.

### Reproduction Steps?

1. Clone  https://github.com/asanabria-hc/nextjs-okta-auth-api
2. Install packages and run application on dev mode.
3. Go to http://localhost:3000/api/hello
4. You will see the following error:

![Screen Shot 2022-04-19 at 2 21 21 PM](https://user-images.githubusercontent.com/77176710/164089053-0d0e1bdf-0b24-451a-adfa-5c760844e6ce.png)

### SDK Versions

@okta/okta-auth-js: "^6.4.3"

### Execution Environment

Node: 16.14.2

### Additional Information?

Application runs correctly if importing with require and Common Js. 
```javascript
const OktaAuth = require("@okta/okta-auth-js").OktaAuth;
```

**Comment by shuowu** [comment]
Internal Ref: OKTA-491223

**Comment by thaiphan** [comment]
@HugoP27 Yeah, you can import using `require`...

```typescript
const {OktaAuth, toRelativeUrl} = require('@okta/okta-auth-js')
```

**Comment by denysoblohin-okta** [comment]
Reason for error: `broadcast-channel` is an ESM package that's not Node.js compatible.
It should have `"type": "module"` in `package.json` + have a `.js` extension in all imports to be Node.js compatible.
See https://github.com/vercel/next.js/issues/31518
Next.js tries to load `broadcast-channel/dist/esnode/index.js` (ESM version of module, see [`package.json`](https://github.com/pubkey/broadcast-channel/blob/master/package.json#L8)) as a CommonJS package but it's not possible.

Solutions:
1. Prepare a PR to `broadcast-channel` to make it Node.js compatible. Wait for merge and new release, then release new okta-auth-js version.
2. Workaround - Force using CJS version of `broadcast-channel` (`broadcast-channel/dist/es5node/index.js`) for `@okta/okta-auth-js`

Wokaround for 2 can be one of follows:
1. In `next.config.js` add
```js
experimental: { esmExternals: false },
```
2. Install `next-transpile-modules` package and change `next.config.js`:
```js
const nextConfig = {
    ...
};
const withTM = require('next-transpile-modules')([
  '@okta/okta-auth-js',
  'broadcast-channel'
]);  
module.exports = withTM(nextConfig);
```

**Comment by denysoblohin-okta** [comment]
Please upgrade to 6.6.1 to fix the issue without workarounds

**Comment by asanabria-hc** [comment]
Now is working as expected on version `6.7.0` 🚀
