### ISSUE TITLE
Uncaught exception thrown when redirect happens after okta sign in

### ISSUE THREAD

**Issue by gmoitra** [okta/okta-auth-js#1194]
### Describe the bug?

This library throws an uncaught exception when the browser is redirected after successful log in in okta. This is affecting the okta-vuejs library and won't allow you gracefully handle the exception.

native.js?b7d0:26 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed
    at Object.postMessage (webpack-internal:///./node_modules/broadcast-channel/dist/esbrowser/methods/native.js:44:21)
    at eval (webpack-internal:///./node_modules/broadcast-channel/dist/esbrowser/broadcast-channel.js:244:47)
postMessage @ native.js?b7d0:26
eval @ broadcast-channel.js?e27c:198
Promise.then (async)
eval @ broadcast-channel.js?e27c:202
Promise.then (async)
_post @ broadcast-channel.js?e27c:197
postInternal @ broadcast-channel.js?e27c:112
_sendMessage @ leader-election.js?a603:311
eval @ leader-election.js?a603:158
Promise.then (async)
applyRun @ leader-election.js?a603:151
eval @ leader-election.js?a603:183
Promise.then (async)
applyOnce @ leader-election.js?a603:182
eval @ leader-election.js?a603:252
_awaitLeadershipOnce @ leader-election.js?a603:238
awaitLeadership @ leader-election.js?a603:195
startElector @ ServiceManager.ts?5a65:141
start @ ServiceManager.ts?5a65:100
start @ OktaAuth.ts?f435:366
created @ okta-vue.ts?3973:127
callWithErrorHandling @ runtime-core.esm-bundler.js?d2dd:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?d2dd:164
callHook @ runtime-core.esm-bundler.js?d2dd:2983
applyOptions @ runtime-core.esm-bundler.js?d2dd:2885
finishComponentSetup @ runtime-core.esm-bundler.js?d2dd:7230
setupStatefulComponent @ runtime-core.esm-bundler.js?d2dd:7142
setupComponent @ runtime-core.esm-bundler.js?d2dd:7063
mountComponent @ runtime-core.esm-bundler.js?d2dd:4951
processComponent @ runtime-core.esm-bundler.js?d2dd:4926
patch @ runtime-core.esm-bundler.js?d2dd:4518
componentUpdateFn @ runtime-core.esm-bundler.js?d2dd:5136
run @ reactivity.esm-bundler.js?89dc:185
callWithErrorHandling @ runtime-core.esm-bundler.js?d2dd:155
flushJobs @ runtime-core.esm-bundler.js?d2dd:394
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js?d2dd:285
queueJob @ runtime-core.esm-bundler.js?d2dd:279
eval @ runtime-core.esm-bundler.js?d2dd:5168
triggerEffects @ reactivity.esm-bundler.js?89dc:382
triggerRefValue @ reactivity.esm-bundler.js?89dc:982
eval @ reactivity.esm-bundler.js?89dc:1113
triggerEffects @ reactivity.esm-bundler.js?89dc:382
triggerRefValue @ reactivity.esm-bundler.js?89dc:982
eval @ reactivity.esm-bundler.js?89dc:1113
triggerEffects @ reactivity.esm-bundler.js?89dc:382
triggerRefValue @ reactivity.esm-bundler.js?89dc:982
eval @ reactivity.esm-bundler.js?89dc:1113
triggerEffects @ reactivity.esm-bundler.js?89dc:382
triggerRefValue @ reactivity.esm-bundler.js?89dc:982
eval @ reactivity.esm-bundler.js?89dc:1113
triggerEffects @ reactivity.esm-bundler.js?89dc:382
triggerRefValue @ reactivity.esm-bundler.js?89dc:982
set @ reactivity.esm-bundler.js?89dc:1026
finalizeNavigation @ vue-router.esm-bundler.js?ec2d:3194
eval @ vue-router.esm-bundler.js?ec2d:3067
Promise.then (async)
pushWithRedirect @ vue-router.esm-bundler.js?ec2d:3031
push @ vue-router.esm-bundler.js?ec2d:2966
navigate @ vue-router.esm-bundler.js?ec2d:2093
callWithErrorHandling @ runtime-core.esm-bundler.js?d2dd:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?d2dd:164
invoker @ runtime-dom.esm-bundler.js?2725:369

The same issue is observed while running the sample project https://github.com/okta-samples/okta-vue-sample. 

### What is expected to happen?

Gracefully handling of the promise returned back from callback.

### What is the actual behavior?

Callback from okta is happening but bunch of errors are thrown after landing in the redirected page.

### Reproduction Steps?

Running this project will reproduce same error.
https://github.com/okta-samples/okta-vue-sample. 

### SDK Versions

    "@okta/okta-auth-js": "^6.4.3",
    "@okta/okta-vue": "^5.2.1",

### Execution Environment

Chrome, Edge
    "vue": "^3.2.33",
    "vue-router": "^4.0.14",
    "vuex": "^4.0.2"

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting!

@shuowu-okta can you help take a look please?

**Comment by shuowu** [comment]
Similar issue: https://github.com/okta/okta-auth-js/issues/1174

**Comment by gmoitra** [comment]
@shuowu Thanks a ton!! Downgrading okta-auth-js version to 6.2.0 did the trick.
