### ISSUE TITLE
Auth JS 6.5.0 upgrade cause warnings

### ISSUE THREAD

**Issue by udayshetty** [okta/okta-auth-js#1206]
### Describe the bug?

Upgrade of  auth js from 6.1.0 to 6.5.0  cause warnings in Angular

### What is expected to happen?

ng serve should compile without warnings

### What is the actual behavior?

C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\array\from.js depends on 'core-js-pure/stable/array/from'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\concat.js depends on 'core-js-pure/stable/instance/concat'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\entries.js depends on 'core-js-pure/stable/instance/entries'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\filter.js depends on 'core-js-pure/stable/instance/filter'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\find.js depends on 'core-js-pure/stable/instance/find'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\includes.js depends on 'core-js-pure/stable/instance/includes'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\index-of.js depends on 'core-js-pure/stable/instance/index-of'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\keys.js depends on 'core-js-pure/stable/instance/keys'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\map.js depends on 'core-js-pure/stable/instance/map'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\reduce.js depends on 'core-js-pure/stable/instance/reduce'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\slice.js depends on 'core-js-pure/stable/instance/slice'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\instance\values.js depends on 'core-js-pure/stable/instance/values'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\json\stringify.js depends on 'core-js-pure/stable/json/stringify'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\map.js depends on 'core-js-pure/stable/map'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\number\is-integer.js depends on 'core-js-pure/stable/number/is-integer'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\object\assign.js depends on 'core-js-pure/stable/object/assign'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\object\entries.js depends on 'core-js-pure/stable/object/entries'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\object\from-entries.js depends on 'core-js-pure/stable/object/from-entries'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\object\keys.js depends on 'core-js-pure/stable/object/keys'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\object\set-prototype-of.js depends on 'core-js-pure/stable/object/set-prototype-of'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\object\values.js depends on 'core-js-pure/stable/object/values'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\parse-int.js depends on 'core-js-pure/stable/parse-int'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\promise.js depends on 'core-js-pure/stable/promise'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\reflect\construct.js depends on 'core-js-pure/stable/reflect/construct'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\symbol.js depends on 'core-js-pure/stable/symbol'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: C:\Temp\angulartest\webapp\node_modules\@babel\runtime-corejs3\core-js-stable\url.js depends on 'core-js-pure/stable/url'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

### Reproduction Steps?

ng serve

### SDK Versions

[package.zip](https://github.com/okta/okta-auth-js/files/8644089/package.zip)

### Execution Environment

Windows 10 , npm 7.5.6 , node 16.15.0, Angular 12.1.1

### Additional Information?

Same warnings when you upgrade from 6.1.0 to 6.2.0

**Comment by denysoblohin-okta** [comment]
Have you tried adding `core-js-stable` to `allowedCommonJsDependencies` in `angular.json`?
```
"build": {
  "options": {
     "allowedCommonJsDependencies": [
        "core-js-stable"
     ]
  }
}
```

**Comment by udayshetty** [comment]
Did that ,still getting same warnings.

**Comment by denysoblohin-okta** [comment]
@udayshetty Sorry, please use `core-js-pure` instead of `core-js-stable` in `angular.json`:
```
"build": {
  "options": {
     "allowedCommonJsDependencies": [
        "core-js-pure"
     ]
  }
}
```
Just tried on your sample app, should build without warnings.

As for errors you mentioned in https://github.com/okta/okta-signin-widget/issues/2505
as a workaround, you can add
```

    "@types/backbone": "^1.4.15",
    "@types/jquery": "^3.5.14",
    "@types/jqueryui": "^1.12.16",
    "@types/q": "^1.5.5",
    "@types/selectize": "^0.12.35",
    "@types/underscore": "^1.11.4"
```
to `dependencies` in `package.json`

**Comment by udayshetty** [comment]
Issue resolved
