### ISSUE TITLE
Include a method to obtain a new sessionToken

### ISSUE THREAD

**Issue by hecmocer-pro** [okta/okta-auth-js#1214]
### Describe the feature request?

Eventhough there are many methods that work with sessionTokens, there is no way to obtain a new sessionToken using this library. SessionTokens are critical and needed for some other methods to work like the session and token renewal methods.

It makes no sense there are many api methods that require a sessionToken but still the library does not provide a method (or even proper documentation) on how to obtain one

### New or Affected Resource(s)

SessionToken

**Comment by oleksandrpravosudko-okta** [comment]
Hi @hecmocer-pro, [`signInWithCredentials`](https://github.com/okta/okta-auth-js/blob/master/docs/authn.md#signinwithcredentialsoptions) returns a session token, you can also refresh active session using [`refreshSession`](https://github.com/okta/okta-auth-js/blob/a4bb17a444ffef27dda65a5499b29d51e689cc72/lib/session.ts#L59) method.
Can you describe your Okta usage in more detail in case these options don't work for you?

**Comment by hecmocer-pro** [comment]
Hi @oleksandrpravosudko-okta, in our scenario we are using [signInWithRedirect](https://github.com/okta/okta-auth-js#signinwithredirectoptions) to redirect our application to the okta user credentials form. Then after the user fills this form, the user is redirected to our application where through [parseFromUrl](parseFromUrl) we can only obtain an access token.

We find convenient to delegate the user credentials form to okta. Our users are already used to okta sign in forms and having to implement a custom form in the application is not only time consuming but also worst in terms of user experience.

Is there any way we could obtain a sessionToken through the flow I just described? Maybe we got it wrong?

Thanks!

**Comment by oleksandrpravosudko-okta** [comment]
When using redirect flow, session token is obtained(and used to set session cookie) by Okta-hosted sign-in widget so you don't have get it yourself. Once Okta session expires, user has to re-authenticate to establish a new session. In your application you could check if access/ID tokens are still valid and prompt user to sign in in case tokens can not be renewed (see React [sample app](https://github.com/okta/samples-js-react/blob/master/custom-login/src/App.jsx#L51)).

**Comment by hecmocer-pro** [comment]
The objective for obtaining the session is so that we can refresh the token silently so that users don't have to constantly logout+login each time the token expires.

According to the documentation, we are supposed to use either [tokenManager.renew(key)](tokenManager.renew(key)) or [token.renew(tokenToRenew)](token.renew(tokenToRenew)), but for obtaining a new token silently a valid session is needed. Through the redirect flow we do not have a valid session.

I hope you now understand why I was asking how to get a sessionToken in the first place, so that we can exchange it for a sessionCookie and keep a valid session that could be used to provide silent token renovation.

In our app, after the redirect flow, we are initializing the OktaAuthClient (picture 1), and when we call the following code (picture 2) we only get errors on the console, most likely because there is no valid session (picture 3)

![image](https://user-images.githubusercontent.com/22548110/169310453-81e3a267-97f6-4a6a-80ea-486b198d8b27.png)
Picture 1

![image](https://user-images.githubusercontent.com/22548110/169310816-0f57d35d-c472-4f67-bf06-daf4c5a4e05f.png)
Picture 2

![image](https://user-images.githubusercontent.com/22548110/169311005-fad31536-fb10-4dbb-8cb9-21c2001f6987.png)
Picture 3

**Comment by hecmocer-pro** [comment]
Apparently our okta instance manager team had the sessionTokens disabled U.U

Now after login-in with redirect flow we get back the refresh token and it can be used to establish a session and renew tokens.

Still I think it could be useful to add documentation regarding how to obtain a sessionToken and that it can be disabled via okta configuration, I had a hard time looking for information online only from a developer point of view.

Anyways, thanks!!
