### ISSUE TITLE
 Cannot find module '@okta/okta-auth-js' in jest tests in Angular 14

### ISSUE THREAD

**Issue by redmanmsc** [okta/okta-auth-js#1230]
### Describe the bug?

When you create a unit test using jest for a component or services that depends on OktaAuth from '@okta/okta-auth-js' the test fails with the following error message: Cannot find module '@okta/okta-auth-js' from 'path/to/service/depending/on/OktaAuth '

### What is expected to happen?

The test pass

### What is the actual behavior?

 Test suite failed to run

    Cannot find module '@okta/okta-auth-js' from 'src/app/authentication/okta.service.ts'

    Require stack:
      src/app/authentication/okta.service.ts
      src/app/guards/auth.guard.ts
      src/app/guards/auth.guard.spec.ts

      1 | import { Injectable } from '@angular/core';
    > 2 | import { OktaAuth, UserClaims } from '@okta/okta-auth-js';
        | ^
      3 | import { from, Observable } from 'rxjs';
      4 |
      5 | @Injectable({

### Reproduction Steps?

1. Create a new angular 14 application.
2. Configure jest as test library
3. Install @okta/okta-auth-js and @okta/okta-angular
4. Create an authentication service depending on OktaAuth.
5. Ensure you have the default spec for the service.
6. Run the tests

### SDK Versions

"@okta/okta-angular": "^5.2.0",
"@okta/okta-auth-js": "^6.6.1"

dev:
"@angular-builders/jest": "^13.0.4",
"@types/jest": "^27.5.2",
"jest": "^28.1.0",
"jest-junit": "^13.2.0",
"jest-preset-angular": "^12.1.0",
"ts-jest": "^28.0.4",

### Execution Environment

Node 18.3.0, Windows 11

### Additional Information?

With angular 13 I had no that issue, the issue started after upgrading to angular 14.

Reproduction repository:
https://github.com/redmanmsc/angular14-jest-okta

**Comment by redmanmsc** [comment]
[https://kulshekhar.github.io/ts-jest/docs/getting-started/paths-mapping/](https://kulshekhar.github.io/ts-jest/docs/getting-started/paths-mapping/) here just specify how to use the configured paths, but is not required for jest to works, anyway, the repo has that configuration done: [https://github.com/redmanmsc/angular14-jest-okta/blob/main/jest.config.js#:~:text=moduleNameMapper%3A%20pathsToModuleNameMapper,%7D)](https://github.com/redmanmsc/angular14-jest-okta/blob/main/jest.config.js#:~:text=moduleNameMapper%3A%20pathsToModuleNameMapper,%7D))

**Comment by jaredperreault-okta** [comment]
I made the following change to your `jest.config.js` and all tests passed

```
moduleNameMapper: {
    ...pathsToModuleNameMapper(compilerOptions.paths || {}, {
      prefix: '<rootDir>/'
    }),
    '@okta/okta-auth-js': '<rootDir>/node_modules/@okta/okta-auth-js/dist/okta-auth-js.umd.js'
},
```

**Comment by redmanmsc** [comment]
Using angular 13 it works without that extra configuration, any idea on why?

**Comment by jaredperreault-okta** [comment]
My guess is https://www.npmjs.com/package/@angular-builders/jest, it seems to require strict matching of Angular major versions and does not currently support Angular 14

**Comment by russcarver** [comment]
This reared it's ugly head for me (for the first time) in Angular 14/Jest 28. Solved by adding:
```
  moduleNameMapper: {
    '@okta/okta-auth-js': '<rootDir>/node_modules/@okta/okta-auth-js/dist/okta-auth-js.umd.js'
  },
 ```
 to my jest.config.js file

**Comment by mdowling17** [comment]
This fix is no longer working for me in okta-auth-js v7.3.0 since it looks like there's no longer the file at `<rootDir>/node_modules/@okta/okta-auth-js/dist/okta-auth-js.umd.js`

**Comment by jaredperreault-okta** [comment]
Our module entrypoints changed in v7, so the moduleMapper path will need to change (as @mdowling17 pointed out). However I would try to run your tests without the mapper with auth-js v7. I have been using jest 29 in a separate project with auth-js 7.3 as a dependency and everything worked out of the box

**Comment by mdowling17** [comment]
@jaredperreault-okta you're correct, I took it out altogether and it worked just fine.
