### ISSUE TITLE
Okta not logging out automatically

### ISSUE THREAD

**Issue by anjalichawlaa** [okta/okta-auth-js#1238]
### Describe the feature request?

Hi, 
We are using okta organisation server in our application.
Application is using okta react. Application flow - Authorization code flow with pkce refresh token. 
these are the settings and cannot be updated 
Access token lifetime - 60 mins
Refresh token lifetime - 100 days

My application is not getting logged out for days,  can u explain what is the issue here? 

### New or Affected Resource(s)

All

**Comment by jaredperreault-okta** [comment]
> A refresh token is a special token that is used to obtain additional access tokens. This allows you to have short-lived access tokens without having to collect credentials every time one expires. You request a refresh token alongside the access and/or ID tokens as part of a user's initial authentication and authorization flow. Applications must then securely store refresh tokens since they allow users to remain authenticated.
-https://developer.okta.com/docs/guides/refresh-tokens/main/

A user will be able to extend their current session as long as they have a valid refresh token. With your settings, the refresh token will be valid for 100 days. If you need/want the session to end after a certain period of inactivity, you'll either need to adjust the refresh token lifetime to something much shorter or have you application explicitly call `.signOut`
