### ISSUE TITLE
Revoke organization server refresh token

### ISSUE THREAD

**Issue by anjalichawlaa** [okta/okta-auth-js#1239]
### Describe the feature request?

Hi, 

I'm trying to revoke organization server refresh token using this POST request

https://{baseurl}/oauth2/v1/revoke?client_id=****&token=*****&token_type_hint=refresh_token
Passing content-type in header as "application/x-www-form-urlencoded"

I get response as ok but I can still get new access token using this refresh token.

https://developer.okta.com/docs/guides/revoke-tokens/main/#revoke-only-the-refresh-token

What is the authorization header in this example request? Am I missing anything here?

### New or Affected Resource(s)

ALL

**Comment by oleksandrpravosudko-okta** [comment]
Hi @anjalichawlaa, in case you having issues with revoking the token using SDK code please provide minimal repro snippet.
Otherwise I suggest to ask this question at Okta dev forum.  
Authorization header contains base64-encoded clientId and clientSecret(if available).
