### ISSUE TITLE
Add ability to disable absolute URL check for redirectUri when running on web (in order to support Capacitor and other hybrid apps)

### ISSUE THREAD

**Issue by kito99** [okta/okta-auth-js#1248]
### Describe the feature request?

When running inside of a browser, If the redirectURI contains a scheme that has periods, okta-auth-js assumes it's a relative URI, so it tries to generate an absolute URI using `window.location.origin`. This works fine in normal web apps, but if your code is running inside of a mobile app that's using a WebView (as it is in Capacitor or Cordova apps), it could have a custom scheme that includes periods: for example `com.acme.mobileapp`. So the redirectURI would be `com.acme.mobileapp://localhost/callback`, for example.

In the example above, okta-auth-js would change the redirectURI to `https://localhost/com.acme.mobileapp::/localhost/callback`, which of course doesn't work. 

A workaround is to just manually set the value after creating a new `OktaAuth` instance: 

```javascript
    const oktaAuth = new OktaAuth(OKTA_CONFIG.oidc);
    oktaAuth.options.redirectUri = MobileAppUtil.getLoginCallbackUri();
```

### New or Affected Resource(s)

See: https://github.com/okta/okta-auth-js/blob/master/lib/OktaAuth.ts#L211. When running a WebView within a mobile app, `isBrowser()` returns true. The request is to have an additional option that skips this behavior even if `isBrowser()` returns true.

### Provide a documentation link

iOS and Android apps can have custom schemes and it's common to use those in redirect URIs. See: https://capacitorjs.com/docs/android/configuration#url-schemes.

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref:  OKTA-511508

**Comment by jaynewstrom-okta** [comment]
Also noted as an issue here: https://github.com/okta/okta-oidc-android/issues/219 added internal ref on Android issue as well.
