### ISSUE TITLE
Make `tokenManager.get()` asynchronous

### ISSUE THREAD

**Issue by robertjd** [okta/okta-auth-js#125]
This method is currently synchronous, and creates problems if the token is being refreshed at the time that this method is called.  This problem has been discussed at length in these issues:

https://github.com/okta/okta-auth-js/issues/92
https://github.com/okta/okta-auth-js/issues/123
https://github.com/okta/okta-oidc-js/pull/181

The desired fix is described in this comment:

https://github.com/okta/okta-oidc-js/pull/181#issuecomment-388165011

We are going to implement this fix and release a major version.  Please watch this issue for updates.

**Comment by jmelberg-okta** [comment]
Resolved with [`2.0.0`](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-2.0.0).
