### ISSUE TITLE
Make HTTP code less brittle

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-auth-js#126]
Reported by a customer:

> IE Edge has an issue with JSON parse.  responseText could be null which would case an exception with JSON.parse down below. 

      res = resp.responseText;
      if (res && util.isString(res)) {
        res = JSON.parse(res);
      }
 
> Our fix ->  res = resp.responseText ? resp.responseText : resp;

**Comment by rchild-okta** [comment]
@nbarbettini What are the details around the request that triggers this? We should fix it at the API level. I do agree that we should make the handler code less brittle (don't throw an exception), but it should probably be a generic error message rather than the raw response.

**Comment by aarongranick-okta** [comment]
In version 3.0 we added better handling for unexpected response types. We are handling text when we expected JSON and invalid JSON. I believe a null or empty string would be handled by these cases: https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/test/spec/fetch-request.js#L141
