### ISSUE TITLE
 Unsatisfied version 0 from of shared singleton module @okta/okta-auth-js (required =6.7.4)

### ISSUE THREAD

**Issue by samartomar** [okta/okta-auth-js#1270]
### Describe the bug?

main.ts:2 
        
       Error: Unsatisfied version 0 from testproject of shared singleton module @okta/okta-auth-js (required =6.7.4)

node_modules\@okta\okta-auth-js\lib\index.d.ts 

Missing version property exposed from package. 

Webpack build with module federation is failied. 

### What is expected to happen?

Must have version exposed

### What is the actual behavior?

Missing version - causing webpack build fail 

### Reproduction Steps?

https://nx.dev/ 
[create sample project using ](https://nx.dev/module-federation/dynamic-module-federation-with-angular#advanced-angular-micro-frontends-with-dynamic-module-federation)

Add Okta lib. and run project you will be able to see failure. 

### SDK Versions

6.7.4
6.7.3
6.7.1

### Execution Environment

Dev/sit/prod

**Comment by jaredperreault-okta** [comment]
I think this issue is related to https://github.com/webpack/webpack/issues/13457

Thanks for the report! We will continue to investigate

**Comment by samartomar** [comment]
it seems like how to fix is known now, but when this can be available to end user ?

**Comment by jaredperreault-okta** [comment]
@samartomar this issue should be fixed in version `6.7.5`
