### ISSUE TITLE
IDX skip implemented

### ISSUE THREAD

**Issue by phi1ipp** [okta/okta-auth-js#1327]
### Describe the feature request?

comparing this implementations with Java one, I noticed that I can't skip a step if required. In Java your have `skipAuthenticatorEnrollment`, but here I'm not sure how to achieve the same functionality

### New or Affected Resource(s)

OktaAuth.idx

**Comment by jaredperreault-okta** [comment]
Our `idx` sdk only allows for skipping optional authenticator enrollments, if an authenticator is marked as required, then the user will be prompt to enroll. If you would like your users to have the ability to skip enrollments, I suggest reviewing your Authenticator policies

**Comment by jaredperreault-okta** [comment]
Apologizes, I misunderstood your question.

This does seem to be something that is missing thorough documentation

```javascript
await authClient.idx.proceed({ skip: true });
``` 

Ref: `nextStep.canSkip` ([docs](https://github.com/okta/okta-auth-js/blob/master/docs/idx.md#nextstep))
Ref: [sample](https://github.com/okta/okta-auth-js/blob/master/samples/generated/express-embedded-auth-with-sdk/web-server/routes/authenticator.js#L54)
