### ISSUE TITLE
token.getUserInfo() performs unexpected API request

### ISSUE THREAD

**Issue by dtrenz** [okta/okta-auth-js#1332]
### Describe the bug?

According to [the documentation](https://github.com/okta/okta-auth-js#tokengetuserinfoaccesstokenobject-idtokenobject), `token.getUserInfo()` (aka `oktaAuth.getUser()`) retrieves user info from a locally stored ID token. However, calling this method triggers an API request to a `GET /userinfo` endpoint.

### What is expected to happen?

User info should be returned from the local ID token, without the need for an API request.

### What is the actual behavior?

A `GET /userinfo` API request is made to fetch user info from the Okta API, even though the user info is available in the locally stored ID token.

### Reproduction Steps?

1. Log-in to an application using Okta auth
2. Call `token.getUserInfo()` or `oktaAuth.getUser()`

### SDK Versions

```
"@okta/okta-auth-js": "6.0"
"@okta/okta-react": "6.4"
```

### Execution Environment

Browser (Chrome).

**Comment by jaredperreault-okta** [comment]
I believe the documentation for this method is misleading. The method retrieves both the `idToken` and `accessToken` from the `tokenManager` using the default keys (`"idToken" and "accessToken" respectively). If your tokens are being stored with different keys, you'll need to pass the tokens to the method, however this method always invokes the `/userinfo` endpoint.

src: https://github.com/okta/okta-auth-js/blob/master/lib/oidc/getUserInfo.ts
