### ISSUE TITLE
Authentication flow steps are incorrect for "identify"

### ISSUE THREAD

**Issue by probablykabari** [okta/okta-auth-js#1338]
### Describe the bug?

When starting the authentication flow, the `nextStep` paremeter shows the following:

```
nextStep: {
 inputs:  [
    {name: 'username', label: 'Username', required: true},
    {name: 'rememberMe', type: 'boolean', label: 'Remember this device'}
  ],
  name:  "identify"
}
```

However if you submit this step with `username` as one of the field, it fails and responds with a message saying that `identifier` is the required param. However if you send `identifier` as the param initially, even though it specifically shows to use `username`, it works.

### What is expected to happen?

The `nextStep` should provide the correct parameters on initialization.

### What is the actual behavior?

The initial step provided is incorrect.

### Reproduction Steps?

Within Okta, this client is set to only allow SSO via custom IdP's. So there is no password login or signup.

This issue happens in an incognito browser with no previous session data.

```
const idx = await okta.idx.start({ flow: 'authenticate' })
console.log("INIT TXN %o", idx) // this shows up with the issue above
```

Elsewhere on the login form:

```
    if (status === IdxStatus.PENDING) {
      if (valid && nextStep?.name === 'identify') {
        const resp = await auth.proceed(nextStep.name, { username: values.username, rememberMe: values.rememberMe })
        console.log("auth resp", resp) // this returns the failed step and message saying identity is a required param
      }
    }
```

### SDK Versions

``` // dependencies
    "@heroicons/react": "^2.0.13",
    "@mobily/ts-belt": "^3.13.1",
    "@okta/okta-auth-js": "^7.0.1",
    "@tailwindcss/forms": "^0.5.3",
    "@types/node": "18",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "autoprefixer": "^10.4.13",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "reakit": "^1.3.11",
    "recoil": "^0.7.6",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.8.4",
    "wouter": "^2.8.0",
    "yup": "^1.0.0-beta.7"
```

```
"packageManager": "yarn@3.2.4",
```

### Execution Environment

Chrome, React 18, OSX.

**Comment by denysoblohin-okta** [comment]
Please use
```js
const resp = await okta.idx.proceed({ username: values.username, rememberMe: values.rememberMe })
```
instead of 
```js
const resp = await auth.proceed(nextStep.name, { username: values.username, rememberMe: values.rememberMe })
```

[idx.proceed](https://github.com/okta/okta-auth-js/blob/master/docs/idx.md#idxproceed) is the documented API method. 
Method `proceed` of IDX transaction is internal and doesn't perform remediator data [mapping](https://github.com/okta/okta-auth-js/blob/3136928d6d2d941dced698e502ea77dcc741b324/lib/idx/remediators/Identify.ts#L27)
