### ISSUE TITLE
414 Request-URI Too Long Returned Calling /logout Endpoint 

### ISSUE THREAD

**Issue by stuconnall** [okta/okta-auth-js#1346]
### Describe the bug?

Not sure if this is a bug, per se, but I'm getting a 414 http code when calling the /logout API from both the Okta SPA sample application and our own SPA application. The problem is occurring when the okta-auth-js signOut() issues the /logout API call passing the id_token_hint which is nearly 18K in length. The /logout endpoint is a GET and may be better if it were a POST due to the large parameter value, i.e., the id_token_hint.  I've debugged the auth-js code and the code pulls the idToken from local Storage and adds it to the URL.  The token itself is nearly 18K.  Is the id_token_hint supposed to contain the full idToken value?

### What is expected to happen?

The Okta /logout API is accepted and the user is successfully signed out of the SPA application.

### What is the actual behavior?

A 414 URI Too Long is returned and the /logout doesn't complete. The Okta keys in localstorage are deleted but the session remains open because the logout didn't make it to the Okta server.

### Reproduction Steps?

Build and run the okta-hosted-login SPA application in a local environment or any SPA application that invokes the signOut() in the okta-auth-js library.

https://github.com/okta/samples-js-vue/tree/master/okta-hosted-login

### SDK Versions

@okta/okta-auth-js : version 7.0.1
@okta/okta-vue : version 5.5.0

### Execution Environment

Windows 10
npm: 8.1.2
node: 16.13.2
All browsers - latest versions Chrome, Edge, Firefox

Running locally with npm run dev command

**Comment by jaredperreault-okta** [comment]
Thank you for this report

Internal Ref: OKTA-551961

**Comment by stuconnall** [comment]
This issue has been resolved thanks to Andrea at Okta.  She informed me that the reason the logout endpoint was failing was due to the amount of claims data for the user account I was testing with.  We use an inline hook to add additional claims data when a user signs into our applications. Some of our internal test accounts contain a large amount of claims data which makes up the id_token_hint passed on the /logout endpoint.  This is not an issue for our external users (customers), therefore, all internal users will use an alternate logout that essentially revokes the access token and clears the session cookies.  This works in all browsers except for Firefox.  The long term solution is to reduce the amount of data we are adding to the hook and make it available from an API call instead.

A temporary logout solution looks something like this:

`const idToken = await this.$auth.tokenManager.get('idToken');
if(idToken.idToken.length < 1848) {
  await this.$auth.signOut();
} else {
  await this.$auth.revokeAccessToken();
  this.$auth.closeSession()
    .then(() => { window.location.href = "/login"; })
    .catch(e => console.log(e.getMessage));
}
`

**Comment by jaredperreault-okta** [comment]
Thanks posting this update! I'm glad Andrea was able to help! Just curious, why doesn't this solution work with Firefox?
