### ISSUE TITLE
`TokenManager.on` fires events across sessions (tabs)

### ISSUE THREAD

**Issue by dcbroad3** [okta/okta-auth-js#1351]
### Describe the bug?

Starting in 7.0.0, when one browser session uses `tokenManager.on(...)`, the subscribed event handler is fired also for events that occur in other browser sessions. When using `storageType: 'sessionStorage'`, it is expected that the library will be compartmentalized across sessions, so it is not expected that the library would fire events that occur in other sessions. 

Specifically, when logging in using one account in session A, then logging into the same account in session B, session A fires an event with the new token from session B. 

This did not occur in version 6.9.0, I will roll back to that version until this is either fixed or a workaround is identified.

### What is expected to happen?

Events should only fire for the current session, especially if the storage type is set to use session storage.

### What is the actual behavior?

Events are firing for different sessions inside a single session.

### Reproduction Steps?

Use `oktaAuth.tokenManager.on('added', () => console.log('added');` to subscribe to the 'added' event in a given session. Open two sessions. When you log into the second session and a token is added for that session, a console message is logged in the first session. 

### SDK Versions

`okta-auth-js 7.0.0` is the first version that encounters this issue. We are also using `okta-angular 6.0.0`, but it does not appear to be related.

### Execution Environment

Firefox/Chrome latest (Firefox 106.0.5 as of time reported)
NodeJS 16.13.1

**Comment by jaredperreault-okta** [comment]
> Specifically, when logging in using one account in session A, then logging into the same account in session B, session A fires an event with the new token from session B.

Do you mind clarifying your use of "session"? Do mean "auth session" or "window/tab session"?

**Comment by dcbroad3** [comment]
Generally here when I say session I'm referring to browser sessions (tabs).

**Comment by denysoblohin-okta** [comment]
Please add
```js
services: {
  syncStorage: false,
}
```
or 
```js
tokenManager: {
  syncStorage: false,
}
```
to `oktaAuth ` config to disable tokens synchronisation across tabs.

`syncStorage` is [enabled by default](https://github.com/okta/okta-auth-js/blob/f5c58a708323f51aa3388cc76236ddf37a5f6e81/lib/core/ServiceManager/browser.ts#L51). 
[Before 7.0 it was disabled](https://github.com/okta/okta-auth-js/pull/1296/files#diff-b4f655bf7aab1f3954369864b3d92340fc875670471f0f22c5f45d9d7a06d0a0L39) for `sessionStorage ` type, but now you should disable it with config please. 
Probably should be reflected in readme.

**Comment by dcbroad3** [comment]
Confirmed; I could've sworn the code still looked like it would disable `syncStorage` if set to use `sessionStorage` in 7.0, but you're right. Mentioning this in the README would be very helpful.
