### ISSUE TITLE
Update static-spa sample to support OIE forgot password flow

### ISSUE THREAD

**Issue by icsrmontano** [okta/okta-auth-js#1358]
### Describe the feature request?

The current static-spa (widget mode) sample still uses the deprecated recoveryToken for the forgot password flow. After editing the email template to use the callback URL along with the otp and state parameters, the widget failed to bootstrap to prompt the user to complete the forgot password flow.

### New or Affected Resource(s)

 static-spa

### Provide a documentation link

https://help.okta.com/oie/en-us/Content/Topics/Settings/settings-customize-email-magic-link.htm

**Comment by denysoblohin-okta** [comment]
What error do you get while trying to bootstrap widget with `recoveryToken ` ?

**Comment by jaredperreault-okta** [comment]
This example should be helpful https://github.com/okta/okta-auth-js/blob/master/docs/idx.md#email-verify-callback as a means to unblock you.

If your curious, this is the logic running under the hood: https://github.com/okta/okta-auth-js/blob/master/lib/idx/emailVerify.ts#L46. It extracts the `state` and `otp` from the query parameter and passes those values to IDX

We'll work on updating the sample you mentioned

**Comment by icsrmontano** [comment]
FYI, the workaround I found was tu use this sample instead:

https://github.com/okta/okta-auth-js/tree/master/samples/generated/express-embedded-sign-in-widget

For reasons unclear to me, the forgot password flow requires a server-side endpoint to process the otp and state parameters as indicated here:

https://developer.okta.com/docs/guides/oie-embedded-sdk-use-case-custom-pwd-recovery-mfa/java/main/#summary-of-steps
