### ISSUE TITLE
signInWithRedirect not compatible with in memory token storage

### ISSUE THREAD

**Issue by KokoWebDev** [okta/okta-auth-js#1372]
### Describe the bug?

I have a React app that is using the redirection model for sign in. I want to move to in-memory/web-worker solution based on [Auth0's recommendation](https://auth0.com/docs/secure/security-guidance/data-security/token-storage#if-no-backend-is-present). I followed through the updates on the custom [storage implementation](https://github.com/okta/okta-auth-js/issues/211)

Through various logging I determined the authState gets updated, but a page-refresh occurs which is clearing the in-memory authState.

I believe this [else condition here](https://github.com/okta/okta-auth-js/blob/2c92f04e2703f5eae10ff84fc4f46bbbcd500777/lib/oidc/getWithRedirect.ts#L34) (`window.location.assign(requestUrl);`) is causing the page-refresh.

The else condition can't be avoided unless `sdk.options.setLocation` is populated. Looking into the [setLocation function](https://github.com/okta/okta-auth-js/blob/1263546ef236f95420025bc2e25ac1b11378d120/lib/oidc/options/OAuthOptionsConstructor.ts) - it appears this is only for server-side. I am running client-side React.

If we're able to inject a function (prefered) or an opt in for `window.history.pushState` instead of being restricted to `window.location.assign` - the memory storage (and web workers 💯) option is possible, and the consumer can handle the redirection.

### What is expected to happen?

Memory storage is persisted after redirection flow.

### What is the actual behavior?

Redirection flow starts.
Auth state is updated correctly.
Page refresh from `window.location.assign(requestUrl);` clears auth state in memory storage.

### Reproduction Steps?

`const oktaAuth = new OktaAuth({`
`  issuer: authSettings.issuer,`
`  clientId: authSettings.clientId,`
`  tokenManager: {`
`    storage: 'memory',`
`  },`
`});`

`// Some button click calls this loginRedirect`
`async function loginRedirect() {`
`  const tokenParams: TokenParams = {`
`    pkce: true,`
`    clientId: authSettings.clientId,`
`    redirectUri: authSettings.redirectUri,`
`  };`
`  await oktaAuth.signInWithRedirect(tokenParams);`
`}`

### SDK Versions

okta-auth-js: 7.2.0
React: ^18

### Execution Environment

localhost, but I expect this behavior to exist in all environments.

### Additional Information?

Willing to contribute

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Did you consider using `token.getWithPopup` or embedded [sign-in widget](https://github.com/okta/okta-signin-widget) (as implemented in [the test app](https://github.com/okta/okta-auth-js/tree/master/test/apps/app)), to be able to use in-memory storage without refreshing your SPA page?

**Comment by KokoWebDev** [comment]
The `token.getWithPopup()` is a possibility. I appreciate you pointing that out.

The Sign-in widget isn't an option due to [SSO requirements](https://developer.okta.com/docs/concepts/redirect-vs-embedded/#redirect-vs-embedded) and [XSS attack surface](https://developer.okta.com/docs/concepts/redirect-vs-embedded/#embedded-summary). 

Either way, It feels like login approach shouldn't effect the token storage decision

**Comment by robertdamphousse-okta** [comment]
@KokoWebDev could you share with us some details on how the URLs need to change within your application?  I.E. does the user need to navigate away from the URL that they land on when they come back from Okta, or can they stay on that URL.  It's when you move from one URL to another that you are going to end up with a document load event from the browser, and that will cause memory state to be lost.

As you see, the default behavior of this library is to assign a new URL, however you can override that functionality here: https://github.com/okta/okta-auth-js#restoreoriginaluri

That would allow you to use alternate application routing strategies that won't trigger a document load

**Comment by KokoWebDev** [comment]
@robertdamphousse-okta [this](https://github.com/okta/okta-auth-js#restoreoriginaluri) is exactly what I was looking for - a way to override the router. This worked like a charm - I appreciate the quick and thought out responses and apologize for missing that on the docs.

I'm creating a package that encapsulates okta-auth-js (similar implementation to okta-react). The package will be used to by all of our web apps to follow a similar auth pattern. So I need to be able to inject custom routing based on the routing library being used. With the info you gave me, I can do that.

**Comment by jaredperreault-okta** [comment]
@KokoWebDev I recommend taking a look at https://github.com/okta/okta-react/tree/master/samples as well
