### ISSUE TITLE
Cross Fetch Polyfill breaks Fetch API in React Native

### ISSUE THREAD

**Issue by TiKevin83** [okta/okta-auth-js#1393]
### Describe the bug?

The polyfilling of fetch with cross-fetch in this library breaks the Fetch API in React Native. This happens even if you use overrides to upgrade okta-auth-js to its current version.

### What is expected to happen?

Fetch works in React Native while this library is included

### What is the actual behavior?

Fetch is defined as "false" in React Native while this library is included

### Reproduction Steps?

Init a react native app with okta-react-native which uses this library under the hood and write a Fetch call. The app will error saying "Fetch" is currently defined as the boolean "false" instead of the Fetch API.

### SDK Versions

@okta/okta-react-native 2.8.0
@okta/okta-auth-js 7.2.0

### Execution Environment

React Native

### Additional Information?

Issue in Okta-React-Native where this was being discussed:
https://github.com/okta/okta-react-native/issues/301

Fetch in React Native works fine with cross-fetch removed as in this commit:
https://github.com/okta/okta-auth-js/compare/master...TiKevin83:okta-auth-js:remove-fetch-polyfill

**Comment by shuowu-okta** [comment]
@TiKevin83 Thanks for reporting the issue, we will investigate on it.

Internal Ref: OKTA-592572

**Comment by TiKevin83** [comment]
fixed in #1404
