### ISSUE TITLE
Failed call to `/api/sessions/v1/me` is silently ignored when using 3rd party IDP

### ISSUE THREAD

**Issue by krzempekk** [okta/okta-auth-js#1394]
### Describe the bug?

When `/api/sessions/v1/me` endpoint fails in scenario described on [this Okta support page](https://support.okta.com/help/s/article/Okta-session-me-API-returns-404), the error is silently ignored (https://github.com/okta/okta-auth-js/blob/master/lib/session/mixin.ts#L36). 

### What is expected to happen?

Error should be thrown, so it can be handled correctly on app side.

### What is the actual behavior?

Error is silently ignored.

### Reproduction Steps?

1. In browser setting, block third-party cookies.
2. Log in to application using other IDP that default Okta's (so after typing email on Okta login site it redirects you to other site).
3. Try to log out (using `signOut` method) - on network tab you can see that `/me` failed with 404, but no error was thrown and user was not logged out.

### SDK Versions

`@okta/okta-auth-js@6.9.0`

### Execution Environment

`Google Chrome v111`

**Comment by denysoblohin-okta** [comment]
Ignoring HTTP 404 error was done for a reason - if 3rd party IdP is not used and 3rd party cookie is not blocked, just ignoring already closed session makes sense for a "good path". 
But as you mentioned, this error needs to be handled in other cases.
However removing the [condition](https://github.com/okta/okta-auth-js/blob/master/lib/session/mixin.ts#L36) in `catch` block to throw any error would be a breaking change.
If `closeSession()` promise resolves with `false` in case if session not found, and `true` in case of successful closing, will this change work for you?

Internal ref: OKTA-594167

**Comment by krzempekk** [comment]
Hi @denysoblohin-okta! Thank you for response. Yes, that would help fixing my case. Note that I would also need promise returned from `signOut` function to be resolved with `true` or `false` depending on what `closeSession` returned (https://github.com/okta/okta-auth-js/blob/f9ecbbcf1a3bd1fb4bd4b9f37c33d1d0f3d3bbf7/lib/OktaAuth.ts#L562).

**Comment by denysoblohin-okta** [comment]
@krzempekk But `signOut` will redirect to [postLogoutRedirectUri](https://github.com/okta/okta-auth-js#postlogoutredirecturi) after closing session, even if session was not found or has already been closed.
How do you plan to handle this with a promise resolve value?

**Comment by darkowic** [comment]
Scenario: user don't have access and there is an authorization error page with logout button.

User clicks the logout button. The `session/me` throws 404. The [postLogoutRedirectUri](https://github.com/okta/okta-auth-js#postlogoutredirecturi) is redirecting back to log in again (after some internal redirects) and the app ends up again on authorization error page because some state left not cleanup in browser or somewhere else. Therefore, the user is not able to change account etc.

**Comment by denysoblohin-okta** [comment]
@krzempekk Could you please use branch from https://github.com/okta/okta-auth-js/pull/1395 in your project and check if it solves your issue?
