### ISSUE TITLE
storageManager separate configuration for accessToken and idToken

### ISSUE THREAD

**Issue by riwu** [okta/okta-auth-js#1405]
### Describe the feature request?

I want to store `accessToken` in the cookies so that the server can use it for authentication, but I do not want/need `idToken` to be in the cookies.

Can we have separate token configurations?
```
storageManager: {
  accessToken: {
    storageType: 'cookie'
  },
  idToken: {
    storageType: 'localStorage'
  }
}
```

### New or Affected Resource(s)

`storageManager`

### Provide a documentation link

https://github.com/okta/okta-auth-js#storagemanager

**Comment by jaredperreault-okta** [comment]
Our TokenManager/StorageManager does not have the ability to store tokens in separate locations. You could accomplish this by providing your own Storage implementation ([ref](https://github.com/okta/okta-auth-js#storage)) or listening to token events and writing the `accessToken` to a cookie manually ([ref](https://github.com/okta/okta-auth-js#tokenmanageronevent-callback-context))
