### ISSUE TITLE
getSession() returns INACTIVE for session status when status is MFA_ENROLL or MFA_REQUIRED

### ISSUE THREAD

**Issue by pro4tlzz** [okta/okta-auth-js#1408]
### Describe the bug?

Hi,

The [getSession()](https://github.com/okta/okta-auth-js/blob/master/lib/session/api.ts#L30) returns INACTIVE if an Okta session is in MFA_ENROLL or MFA_REQUIRED status.

https://developer.okta.com/docs/reference/api/sessions/#session-status

### What is expected to happen?

getSession() should return MFA_ENROLL or MFA_REQUIRED if they are the STATUS of the session.

### What is the actual behavior?

The [error catching](https://github.com/okta/okta-auth-js/blob/master/lib/session/api.ts#L45) returns INACTIVE in the promise.
I don't understand the code here that well but I don't see why having a status of MFA_ENROLL or MFA_REQUIRED returns a fail on the res.refresh call.

### Reproduction Steps?

Using an Okta user with MFA_ENROLL or MFA_REQUIRED as the session status and call `oktaSignIn.authClient.session.get();` and then check the promise for the status. Note that I am using the Okta sign in widget here to call the JS function as I'm unsure how to call it directly from the JS in a browser console.

### SDK Versions

Okta Sign In Widget version 7.6.1, I'm unaware what lib version of the JS sdk is shipped alongside the widget.

### Execution Environment

Just testing in a browser window.

**Comment by jaredperreault-okta** [comment]
Can you paste the output of `npx envinfo --system --npmPackages '{@okta/*,}' --binaries --browsers`

**Comment by jaredperreault-okta** [comment]
Can you also paste your widget config (please obfuscate sensitive fields)

**Comment by pro4tlzz** [comment]
> npx envinfo --system --npmPackages '{@okta/*,}' --binaries --browsers

```
npx envinfo --system --npmPackages '{@okta/*,}' --binaries --browsers

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 8.23 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 113.0.5672.126
    Firefox: 110.0.1
    Safari: 16.4
  npmPackages:
    @okta/eslint-plugin-okta: 0.5.0 => 0.5.0
    @okta/okta-auth-js: ~7.0.0 => 7.0.1
```




> Can you also paste your widget config (please obfuscate sensitive fields)

I am using the default config.

```
const config = {
  baseUrl: 'http://localhost:3000',
  logo: '/img/logo_widgico.png',
  logoText: 'Windico',
  features: {
    router: true,
    rememberMe: true,
    multiOptionalFactorEnroll: true
  },
  // Do not bootstrap stateToken if you want to enable v1
  stateToken: 'dummy-state-token-wrc',
  authParams: {
    pkce: false // PKCE is enabled by default in okta-auth-js@3.0
  },
  // Host the assets (i.e. json files) locally
  assets: {
    baseUrl: '/'
  },
  // Hooks block processing and run custom logic before or after a form is rendered
  hooks: {
    'identify': {
      after: [
        // createDummyHook('after-identify', 0)
      ]
    },
    'success-redirect': {
      before: [
        // createDummyHook('before-success-redirect',  1000)
      ]
    }
  }
};

function createDummyHook(name, waitTimeMs) {
  // Hook functions receive no parameters. They may return a promise but the value is not used.
  return function() {
    console.log('hook started: ' + name);
    return new Promise(resolve => {
      setTimeout(() => {
        console.log('hook finished: ' + name);
        resolve();
      }, waitTimeMs);
    });
  };
}

module.exports = config;
```

In any case I can no longer reproduce the issue, I can now see that the session status of MFA_ENROLL is returned instead of INACTIVE.
