### ISSUE TITLE
SSO logout on IE using TokenManager

### ISSUE THREAD

**Issue by bajcmartinez** [okta/okta-auth-js#141]
Hi all,

I'm having a weird problem that only happens on IE when using TokenManager on 2 different apps on 2 subdomains. The problem is as follows

1) Login subdomain1, on IE this creates a cookie "okta-token-storage" with the session information
2) SSO into subdomain2, token manager will pick it and save a new cookie for that subdomain
3) Log out from subdomain1, (which should log out from all apps)
4) Log again with another user name into subdomain1, works great
5) SSO into subdomain2, and you are logged in with the old user, as the cookie for the token manager was never erased for that subdomain.

Any ideas? Looks like the problem is with the domain that's specified on the cookie of the TokenManager. When I call the function to clean up the TokenManager, it only deletes the cookie for the current domain. As chrome and other browsers uses local and session storage this problem doesn't happen there.
I went through the code but couldn't find a way to set the domain for the cookie.

Thanks

**Comment by chilicoder** [comment]
+1
