### ISSUE TITLE
The signout function puts a default postLogoutRedirectUri when it's not passed

### ISSUE THREAD

**Issue by prabhjot85** [okta/okta-auth-js#1410]
### Describe the bug

As per https://developer.okta.com/docs/guides/sign-users-out/nodeexpress/main/, it's totally valid to not pass `postLogoutRedirectUri`, however, the [`signOut` function defaults to window.location.origin](https://github.com/okta/okta-auth-js/blob/f1b59e49b0f46745c5cb0beffefa2af8bf712d40/lib/oidc/mixin/index.ts#L288-L292) when it's not passed which causes issues as it's not whitelisted.

### Reproduction Steps?

1. Call signOut function
`await oktaAuth.signOut({
      idToken: { idToken: logoutQueryParams.idToken }, 
      state: logoutQueryParams.state,
    });`
2. Shows error, that URL is not whitelisted but it should Okta signin page as per documentation.

### SDK Versions

  System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 20.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.1 - ~/.nvm/versions/node/v14.21.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.1/bin/yarn
    npm: 8.13.2 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 16.4
  npmPackages:
    @okta/okta-auth-js: ^6.9.0 => 6.9.0
    @okta/okta-react: ^6.7.0 => 6.7.0

**Comment by denysoblohin-okta** [comment]
Yes, by default `postLogoutRedirectUri` equals `window.location.origin` if no explicit value is passed.
As a workaround you can pass an URL which is whitelisted in Okta Admin UI.

**Comment by prabhjot85** [comment]
Correct, but the SDK should allow not to pass the `postLogoutRedirectUri` since, it's a valid request.

**Comment by jaredperreault-okta** [comment]
Sorry @prabhjot85, I'm not sure I understand. The `signOut` method of the SDK _does_ allow for `postLogoutRedirectUri` to be undefined, and in such a case, `postLogoutRedirectUri` will default to `window.location.origin`.  The default behavior of this methods does _not_ redirect to the SignIn Widget

**Comment by prabhjot85** [comment]
@jaredperreault-okta Yes, it does allow it be passed as `undefined`, but it fills it with a default value which can't be whitelisted for our use case. We're hosting our own logout endpoint which redirects to Okta for our use cases. Okta clearly allows to not pass any `post_logout_redirect_uri`, but SDK is enforcing this by adding a default which I believe it shouldn't do.

**Comment by jaredperreault-okta** [comment]
Internal Ref: OKTA-612929

**Comment by jaredperreault-okta** [comment]
Resolved in https://github.com/okta/okta-auth-js/pull/1439. Released in `7.4.0`
