### ISSUE TITLE
I am encountered with okta auth js Sdk. 

### ISSUE THREAD

**Issue by rinsarmu** [okta/okta-auth-js#1418]
### Describe the bug

i have configured all required fields. but it says CORS is missing and AUTH api error. CORS is coming with 200 status code.  u can find all screenshots below.

![Screenshot from 2023-06-09 13-17-11](https://github.com/okta/okta-auth-js/assets/92099288/6bcdbe36-b5f5-4b89-973b-808ca82adcbb)
![Screenshot from 2023-06-09 13-16-33](https://github.com/okta/okta-auth-js/assets/92099288/af76b6ae-b499-41db-995e-dccd43b4d8b8)

### Reproduction Steps?

I don't want to say more.

### SDK Versions

7.0.0

**Comment by rinsarmu** [comment]
thank you. It worked fine. before I close this issue, in my application when I input my okta account I got success transaction with responses like sessionToken, profile and etc.
![Screenshot from 2023-06-11 08-35-41](https://github.com/okta/okta-auth-js/assets/92099288/8615bf44-102f-4492-8a95-33d9b75cc0a5) 
 but on my server there is protected route by okta. so that i should provide OKTA JWT Token. I found that i can built OKTA JWT accessToken using OpenID. but this is  not user specific. for this case I am troubling to generate okta jwt accessToken for current logged in us

![Screenshot from 2023-06-11 08-37-12](https://github.com/okta/okta-auth-js/assets/92099288/74e17fa4-e160-4b3f-a89c-1d3e1d1f2386)
![Screenshot from 2023-06-11 08-37-26](https://github.com/okta/okta-auth-js/assets/92099288/3088a7f1-f045-4200-a51d-c9143f4a3571)
![Screenshot from 2023-06-11 08-38-24](https://github.com/okta/okta-auth-js/assets/92099288/869ed4ab-dddf-433a-9c5f-6b7f12722fe2)
er. I have tried with introspect, but at the end I got invalid client_id error. I am sure client_Id i provide is correct. thank you.
![Screenshot from 2023-06-11 08-42-34](https://github.com/okta/okta-auth-js/assets/92099288/e37cf184-6e98-4e40-bcb4-3703f51c94ea)

**Comment by jaredperreault-okta** [comment]
You shouldn't have to mint your own idToken, instead you can exchange your `sessionToken` token for OIDC tokens via [setCookieAndRedirect](https://github.com/okta/okta-auth-js/blob/master/docs/authn.md#sessionsetcookieandredirectsessiontoken-redirecturi) or [token.getWithoutPrompt](https://github.com/okta/okta-auth-js/tree/master#tokengetwithoutpromptoptions)
