### ISSUE TITLE
Autorenew Token not working in browser (CDN) version

### ISSUE THREAD

**Issue by mrevjd** [okta/okta-auth-js#1427]
### Describe the bug

We are using the CDN browser based version of the Okta SDK and when the AutoRenew token function runs we see the below error:
`okta.auth.js:2 Uncaught TypeError: this.sdk.token.renewTokens(...).then(...).catch(...).finally is not a function
    at e.value (okta.auth.js:2:235440)
    at <anonymous>:1:25` 

When this error occurs, the user is logged out and has to log back in.

If manually running:
`authClient.tokenManager.renew('idToken')
.then(function (newToken) {
  console.log(newToken);
});`

The same error also occurs.

### Reproduction Steps?

1. Log in to system using Okta auth
2. Wait 30mins for token auto renew 
3. Error produced, and user logged out
4. Log back in
5. Wait another 30mins for token auto renew
6. Error produced, and user logged out

### SDK Versions

https://global.oktacdn.com/okta-auth-js/7.2.0/okta-auth-js.min.js

### Additional Information?

We have tried previous versions with the same error.

**Comment by mrevjd** [comment]
From around line 12443 we made the following changes.
From:
```
.catch(function (r) {
   throw (t.remove(e), (r.tokenKey = e), t.emitError(r), r);
})
.finally(function () {
   t.state.renewPromise = null;
}))
```
To
```
.catch(function (r) {
   t.state.renewPromise = null;
   throw (t.remove(e), (r.tokenKey = e), t.emitError(r), r);
})
.then(function () {
   t.state.renewPromise = null;
}))
```

**Comment by denysoblohin-okta** [comment]
What is your browser and browser version?
Do you use polyfill for `fetch`?

**Comment by mrevjd** [comment]
We tested on multiple browsers:

- Microsoft Edge Version 114.0.1823.67 (Official build) (64-bit)
- Firefox Version 115.0.1 (64-bit
- Chrome Version 114.0.5735.199

All on Windows 11 laptops

We tried with and without the polyfill.

Cheers

**Comment by denysoblohin-okta** [comment]
If you run `console.log(Promise.prototype.finally)`, will it show `undefined`?

As a workaround, you can include `https://global.oktacdn.com/okta-auth-js/7.2.0/okta-auth-js.polyfill.js`
Or just add simple polyfill:
```js
      Promise.prototype.finally = function (handler) {
        return this.then(handler, handler);
      }
```


Just replacing `finally` with `then` is not perfect solution, because in this case an error being thrown in `.catch` 
https://github.com/okta/okta-auth-js/blob/0a23b5a91099263e5b157a63a6873661228deca7/lib/oidc/TokenManager.ts#L445-L451
will prevent execution of `finally` callback
https://github.com/okta/okta-auth-js/blob/0a23b5a91099263e5b157a63a6873661228deca7/lib/oidc/TokenManager.ts#L452-L455

**Comment by mrevjd** [comment]
Hi @denysoblohin-okta,

Thanks for the response.
We did try with that version of the polyfill and had not luck. The polyfill also caused other issues.

With that code, did you want that added before the import/load of the [okta-auth-js.min.js](https://global.oktacdn.com/okta-auth-js/7.2.0/okta-auth-js.min.js)?

We have used finally in some of our other JS calls without issues.

Cheers
Evan

**Comment by mrevjd** [comment]
Hi @denysoblohin-okta,

Thanks for the response.
We did try with that version of the polyfill and had not luck. The polyfill also caused other issues.

With that code, did you want that added before the import/load of the [okta-auth-js.min.js](https://global.oktacdn.com/okta-auth-js/7.2.0/okta-auth-js.min.js)?

We have used finally in some of our other JS calls.

Cheers
Evan

**Comment by mrevjd** [comment]
Hi @denysoblohin-okta,

Thanks for the response.
We did try with that version of the polyfill and had not luck. The polyfill also caused other issues.

With that code, did you want that added before the import/load of the [okta-auth-js.min.js](https://global.oktacdn.com/okta-auth-js/7.2.0/okta-auth-js.min.js)?

We have used finally in some of our othe JS calls.

Cheers
Evan

**Comment by denysoblohin-okta** [comment]
Internal ref: OKTA-628044

**Comment by mrevjd** [comment]
Hi @denysoblohin-okta,

Thank you for your time looking into this.
I'm unable to access the systems for the next week.

We only use the CDN version. We don't use Node or npm.

Cheers

**Comment by shuowu-okta** [comment]
@mrevjd It also looks like polyfill issue to me, but as you have tested with latest browsers, I suspect there are some code messed up native promise API from the browser. Do you have a public url that we can take a quick investigation? Thanks

**Comment by mrevjd** [comment]
Hi @shuowu-okta thank you for the response but unfortunately I cannot give access to this.
However, if you have any troubleshooting steps I can assist with, then I'm happy to help.
Thanks

**Comment by mrevjd** [comment]
> If you run `console.log(Promise.prototype.finally)`, will it show `undefined`?
> 
> As a workaround, you can include `https://global.oktacdn.com/okta-auth-js/7.2.0/okta-auth-js.polyfill.js` Or just add simple polyfill:
> 
> ```js
>       Promise.prototype.finally = function (handler) {
>         return this.then(handler, handler);
>       }
> ```
> 
> Just replacing `finally` with `then` is not perfect solution, because in this case an error being thrown in `.catch`
> 
> https://github.com/okta/okta-auth-js/blob/0a23b5a91099263e5b157a63a6873661228deca7/lib/oidc/TokenManager.ts#L445-L451
> 
> 
> will prevent execution of `finally` callback
> https://github.com/okta/okta-auth-js/blob/0a23b5a91099263e5b157a63a6873661228deca7/lib/oidc/TokenManager.ts#L452-L455

Back into the thick of things.
I added the code snippet from above.

```html
       ...
        <link rel="stylesheet" href="/js/load/print.min.css" media="print" onload="this.media='all'">
        <link rel="stylesheet" href="/js/load/jquery-ui.css" media="print" onload="this.media='all'">
        <link rel="stylesheet" href="/js/load/bootstrap.min.css">
        <link rel="stylesheet" href="/js/load/css/case.css" media="print" onload="this.media='all'">
        <!-- <script src="/js/load/okta.auth.js"></script> -->
        <script>
            Promise.prototype.finally = function (handler) {
                return this.then(handler, handler);
            }
        </script>
        <script src="https://global.oktacdn.com/okta-auth-js/7.3.0/okta-auth-js.min.js" type="text/javascript"></script>
        <script src="/js/load/print.min.js"></script>
        <script src="/js/load/jquery.min.js"></script>
        <script src="/js/load/jquery-ui.js"></script>
        <!-- Popper JS -->
        <script src="/js/load/popper.min.js"></script>
        <!-- Latest compiled JavaScript -->
        <script src="/js/load/bootstrap.min.js"></script>
       ...
```

And ran the console log snippet.
It came back with undefined

![image](https://github.com/okta/okta-auth-js/assets/161211/78b91a00-8f0c-4002-b066-3f1bab9ffaee)

**Comment by mrevjd** [comment]
@shuowu-okta @denysoblohin-okta any news on this?

**Comment by jaredperreault-okta** [comment]
@mrevjd To isolate this issue, can you load a random website (like google.com) in the browsers where you're experiencing this issue and run `console.log(Promise.prototype)` in the JS console and confirm `finally` exists?

It should print
```
Promise {Symbol(Symbol.toStringTag): 'Promise', constructor: ƒ, then: ƒ, catch: ƒ, finally: ƒ}
```

Then do the same thing on your app.

**Comment by mrevjd** [comment]
@jaredperreault-okta 

Using google.com:
![image](https://github.com/okta/okta-auth-js/assets/161211/727982c3-3358-4be6-8eb2-f02131e49501)

From our app:
![image](https://github.com/okta/okta-auth-js/assets/161211/16e4264d-3dbf-46c8-ac9d-5b4bbb9e529b)

**Comment by jaredperreault-okta** [comment]
From this test, it seems like something in your application is polyfilling (or editing) the `Promise` prototype, causing `.finally` (and potentially `.catch`) to not exist on the prototype.

I am unable to try out Edge, but you could repeat the experiment in my previous comment by making a simple html file
```html
<html>
  <h1>Hello World!</h1>
</html>
```
And serve the file using [serve](https://www.npmjs.com/package/serve) or [http-server](https://www.npmjs.com/package/http-server). I suspect the `Promise` prototype will look as it did on google.com, possibly indicating your application is manipulating the `Promise` prototype in some way

Perhaps you can try loading AuthJS and the AuthJS provided-polyfill in the `<body>`, so it's the last JS file loaded onto the page (A previous screenshot included css `<link>` tags, so I assume the JS is currently being loaded in the `<head>`).

**Comment by mrevjd** [comment]
@jaredperreault-okta 
Thank you for your time and troubleshooting tips and techniques.

I will let you know the results as soon as poosible.

**Comment by mrevjd** [comment]
@jaredperreault-okta 

Looks like I found the culprit. It was one of the js libraries we were importing.

**Comment by mrevjd** [comment]
@jaredperreault-okta 
Thanks for your suggestions, it was one of the JS libraries we were importing. I have updated that library and refresh now works as expected.

![image](https://github.com/okta/okta-auth-js/assets/161211/b4394ae1-ba0f-4b3d-ad8d-9cfe4473e176)

Thanks
Evan
