### ISSUE TITLE
Vulnerable and Outdated JS Library found in the Application

### ISSUE THREAD

**Issue by manam9595** [okta/okta-auth-js#1428]
### Describe the bug

Hello Team,

 We are using "@okta/okta-signin-widget@3.9.1" and the node version is 10.16.3.

We are getting the security Vulnerability in code audit as mentioned below.
_**Vulnerable and Outdated JS Library found in the Application**_

Looks like the issue coming from **hadnlebars**

Currently our **hadnlebars** version is **^4.5.3**.

What is the @okta/okta-signin-widget supported version for node 10.16.3

Regards,
Narendra.

### Reproduction Steps?

NA

### SDK Versions

NA

**Comment by jaredperreault-okta** [comment]
@manam9595 just to be clear, you're using [@okta/okta-signin-widget](https://github.com/okta/okta-signin-widget), not [@okta/okta-auth-js](https://github.com/okta/okta-signin-widget)?
