### ISSUE TITLE
closeSession() logs out the user from all okta applications

### ISSUE THREAD

**Issue by samuelnavarrodexcom** [okta/okta-auth-js#1429]
### Describe the bug

I am using the redirect flow to sign the user in. When I sign out I was using 
`await this.oktaAuth
        .signOut({
          postLogoutRedirectUri: this.LOGOUT_REDIRECT_URI
        })`

This resulted on the user getting logged out of all applications. 

I was expecting when switching to close the session to have the user only logged out from the specific application
`await this.oktaAuth.closeSession();`

This is how I create an okta auth
` this.oktaAuth = new OktaAuth({
      clientId: CLIENT ID,
      issuer: OKTA_ISSUER,
      redirectUri: this.LOGIN_REDIRECT_URI,
      pkce: true
    });`

### Reproduction Steps?

1. Login to the app using okta hosted login page.
2. Logout from application 
3. Open the okta dashboard, the user is asked to enter his credentials again

### SDK Versions

  System:
    OS: macOS 11.7.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.77 GB / 32.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.4.1
  npmPackages:
    @okta/okta-auth-js: 5.1.1 => 5.1.1

**Comment by jaredperreault-okta** [comment]
`signOut` revokes tokens, clears the tokens from storage and calls `closeSession`. `closeSession` kills the session between Okta and the user's browser.

I believe you should only have to revoke tokens for your use case of logging a user out of a single app.

**Comment by samuelnavarrodexcom** [comment]
I am trying to do that with the following code:

`await this.oktaAuth.revokeRefreshToken();`
`await this.oktaAuth.revokeAccessToken();`
` this.router.navigateByUrl('/');`

I checked the network tab and the revoke endpoint was called succesfully.

After this code is executed, If I execute the next line of code:
`return await this.oktaAuth.isAuthenticated();`

I get false as expected, until here is everything fine.

I then trigger the login and execute this code
`  this.oktaAuth.token.getWithRedirect({
      scopes: this.DEFAULT_SCOPES
    });`
    
 
 When I used `signOut()` this function would redirect me to the hosted okta login page.
 When I used `revokeAccessToken()` this function doesn't do the redirect and instead redirects me to the `redirectURI` I specified when configuring the OktaAuth object. I assume that it went to okta, and okta just generated a new token and determined that no login was required because I am still authenticated to okta outside of this application.

**Comment by samuelnavarrodexcom** [comment]
I tried the same code in the last version 7.3.0 and I am getting the same results

**Comment by shuowu-okta** [comment]
Internal Ref: OKTA-634181

**Comment by jaredperreault-okta** [comment]
@samuelnavarrodexcom Are you using Classic (authn) or OIE?

If you're unsure you can reference `https://{org-name}.okta.com/.well-known/okta-organization` and check if the `pipeline` property === `idx`

**Comment by denysoblohin-okta** [comment]
@samuelnavarrodexcom 
Please try
```js
  this.oktaAuth.token.getWithRedirect({
    scopes: this.DEFAULT_SCOPES,
    prompt: 'login'
  });
```
to prompt the user for authentication. 
By default (without `prompt: 'login'`) if an Okta session already exists, the user would be silently authenticated as you assumed.
See [prompt parameter documentation](https://developer.okta.com/docs/reference/api/oidc/#parameter-details)

**Comment by denysoblohin-okta** [comment]
@samuelnavarrodexcom
Could you please try the above recommendation and tell if this resolves or not your issue? Thanks.
