### ISSUE TITLE
Remove jQuery and reqwest dependencies

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-auth-js#144]
To further clean up the internals of this library, let's do the following:

- [ ] Remove dependency on reqwest
- [ ] Remove devDependency on jQuery
- [ ] Use `fetch()` or another approach (with broad browser compatibility) to do HTTP calls from Auth.js. A developer using Auth.js by itself shouldn't need to provide an HTTP client implementation, and a package that consumes Auth.js (i.e. Sign-In Widget, other Okta SDKs) shouldn't need to provide an HTTP client implementation. Auth.js should provide its own HTTP client.
- [ ] Allowing the developer to pass their own HTTP client (to replace Auth.js' internal HTTP client) is out of scope, but should be considered in the technical design.
- [ ] For scenarios where Auth.js is making calls on behalf of SIW or other Okta SDKs, make sure we can attach additional User-Agent tokens from those libraries on the calls Auth.js makes. (If necessary, this can be split into a separate issue)
- [ ] Update readme to remove references to jQuery and reqwest

**Comment by nbarbettini** [comment]
As mentioned in https://github.com/okta/okta-auth-js/issues/122, reqwest is no longer maintained: https://github.com/ded/reqwest/issues/259

cc @robertdamphousse-okta @manueltanzi-okta

**Comment by aarongranick-okta** [comment]
reqwest and jquery were removed in version 3.0
