### ISSUE TITLE
Token autorenew does not run reliably on a schedule when tabs is minimized or in the background

### ISSUE THREAD

**Issue by ybudweiser** [okta/okta-auth-js#1445]
### Describe the bug

When running okta-angular and  okta-auth-js authClient.start() and waiting long periods of time in the browser (~2-8 hours) we are seeing the autorenew timer delay and not execute a refresh until after the refreshtoken has expired and causing an invalid grant as the refresh token has not been used in its proper time. 
The [documentation](https://github.com/okta/okta-auth-js#running-as-a-service) states to run autorenew , one must invoke authClient.start() however that is not enough in modern browsers. Many browser will put background tabs to sleep when their visibility changes, and standard js timers and intervals are not reliable. 
It is now recommended to use the [Web Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) to run reliable timers in the background that are not paged out when a tab goes idle.

### Reproduction Steps?

Enable autorenew with authClient.start() and leave browse idle and minimized. 

### SDK Versions

Okta Auth JS 7.3.0

**Comment by ybudweiser** [comment]
Truth is, we see this happening after 30 minutes at times, but its less often. 
Also ideally we would like to properly log the user out after inactivity, in which we actually have our own code explicitly call oktaAuth.logout()  if their are no mouse movements, however when the refresh token renewal fails, we are not seeing the onerror callback and our app actually fails in a permanently broken manner. And we cant log the user out.

**Comment by jaredperreault-okta** [comment]
Looking into the renew logic, it does seem like there might be a logic fork where an error is thrown, but not emitted.

Could you try looking at `localStorage` after a repro of the error and see if any tokens are stored?

I'm also curious if the error persists if you add `tokenManager.autoRemove: false` to your AuthJS config

```js
new OktaAuth({
  ..., // current config
  tokenManager: {
    autoRemove: false
  }
});
```

**Comment by ybudweiser** [comment]
Yes, Thanks!
we were able to include the above config and now we are catching the error condition and able to redirect properly. This greatly improves our user experience. Thanks

**Comment by ashishbairwa** [comment]
Hi, I'm facing similar issue in my app but we want the app to be working as per 2nd point of yours:

> 2. Or, are you looking to avoid the user re-authenticating after they interact with tab after the long period of inactivity?
> a. And, if so, why not increase the lifetime of the refresh token to accommodate this?

I also created a devforum post on the same which has information related to code https://devforum.okta.com/t/using-renewtokens-results-in-an-expired-token-after-some-time/30018

After some time of keeping the tab idle our app starts to call `/token` in a loop, when I observed the token on storage it appears to be always expired

**Comment by jaredperreault-okta** [comment]
@ashishbairwa Are you using auth-js `5.1.1`, as the forum post mentions? I recommend trying to upgrade to the latest version of auth-js, we have made improvements to token renewal since `5.1.1`

**Comment by ashishbairwa** [comment]
Thanks for the response @jaredperreault-okta and yes, we are currently sticked to 5.1.1 as we started off with it. I want to understand the importance of offline_access scope in case of renewal. Do renewTokens really depend on that?
