### ISSUE TITLE
Why is that always Google Authenticator app?

### ISSUE THREAD

**Issue by vladkasianenko** [okta/okta-auth-js#1459]
### Describe the feature request?

I think it's fair to mention only Google Authenticator App. There are a lot of other apps that can do the same.
For example, in Github:
![image](https://github.com/okta/okta-auth-js/assets/14053728/917a432a-32c5-4f13-93ba-2deac0724a56)

### New or Affected Resource(s)

All Okta

**Comment by jaredperreault-okta** [comment]
@vladkasianenko Sorry I'm not sure I understand. Why is this is reference to?
