### ISSUE TITLE
idp parameter not assignable to new OktaAuth in react app

### ISSUE THREAD

**Issue by jgrumboe** [okta/okta-auth-js#1461]
### Describe the bug

I'm following the example app https://github.com/oktadev/okta-react-fastify-postgresql-example and I somehow can't find how to add the extra query parameter `idp` to tell Okta which third party IDP to use.
The code I'm referring to is https://github.com/oktadev/okta-react-fastify-postgresql-example/blob/64afa8402fd80126256b799b3b0cba49aa865eb2/packages/frontend/src/App.tsx#L11.
`OktaAuh` extends `OktaAuthIdxOptions`, which extends `OktaAuthCoreOptions`, which extends `OktaAuthOAuthOptions`, which is exported here https://github.com/okta/okta-auth-js/blob/6ab18a633b8cbcbea393fad3f1480627a2df4824/lib/oidc/types/options.ts#L84-L114.
I see that it picks some parameters from `TokenParams`, e.g. `scopes`, but why not also `idp`?

### Reproduction Steps?

Unfortunately, I have none

### SDK Versions

```
  System:
    OS: macOS 13.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Browsers:
    Chrome: 117.0.5938.132
    Edge: 117.0.2045.55
    Safari: 16.6
```

### Additional Information?

Probably I also miss something and there's another way how to inject the `idp` query parameter?!

Thanks for your support!

**Comment by jaredperreault-okta** [comment]
I am not familiar with this sample, but I think you'll want to add your `idp` param to the `oktaAuth.signInWithRedirect()` call. [Docs](https://github.com/okta/okta-auth-js#signinwithredirectoptions)

Found here: https://github.com/oktadev/okta-react-fastify-postgresql-example/blob/64afa8402fd80126256b799b3b0cba49aa865eb2/packages/frontend/src/components/secureRoute.tsx#L20

**Comment by jgrumboe** [comment]
Awesome! Thanks @jaredperreault-okta to point me to the correct place!
An `oktaAuth.signInWithRedirect({ idp: 'xxxxxxxxxx' })` does the trick.
