### ISSUE TITLE
DPoP support

### ISSUE THREAD

**Issue by good-system** [okta/okta-auth-js#1464]
### Describe the feature request?

Since OKTA is adding `DPoP` https://developer.okta.com/docs/guides/dpop/main/, what's the plan to add support in JS library?

### New or Affected Resource(s)

N/A

**Comment by jaredperreault-okta** [comment]
We will look into this and get back to you

**Comment by mguagenti** [comment]
We would be interested in this as well, either support in the SDK or a workaround on how to do it in the SDK. It looks like we could use a custom HTTP Adapter with the SDK to intercept the token requests and add perform the binding but that could be messy.

**Comment by jaredperreault-okta** [comment]
@good-system @mguagenti I am spiking on this effort now. More updates to come

**Comment by jaredperreault-okta** [comment]
This was just released in version `7.7.0`
