### ISSUE TITLE
Circular dependency b/n esm\browser\myaccount\request.js and all the files in the transactions subfolder

### ISSUE THREAD

**Issue by lvid-ascent** [okta/okta-auth-js#1471]
### Describe the bug

If you install okta-auth-js in a React app with Vite, the production build fails because there is a circular dependency between the esm\browser\myaccount\request.js and all the classes in the transactions subfolder.

### Reproduction Steps?

1. Create a new React app with Vite.
2. Reference okta-auth-js (7.4.2 or 7.4.3)
3. Set up Okta authentication in the app so that at least one component references okta-auth-js
4. Run a production build

You receive errors like:
Circular dependency: node_modules/@okta/okta-auth-js/esm/browser/myaccount/request.js -> node_modules/@okta/okta-auth-js/esm/browser/myaccount/transactions/PhoneTransaction.js -> node_modules/@okta/okta-auth-js/
esm/browser/myaccount/request.js

### SDK Versions

7.4.2 and 7.4.3

### Additional Information?

The issue can be resolved by exporting the generateRequestFnFromLinks() function from a separate file that will be referenced by the classes in the transactions subfolder.

**Comment by John0545** [comment]
Hi @lvid-ascent
This is the same issue that I'm also having for last few days, it seems there is issue with the vite 4.x.x. version. When you compile same dependencies with vite 3.2.7 it works.

**Comment by jaredperreault-okta** [comment]
Thank you for the report. You will look into this.

While we do, you may be able to work around this issue by explicitly defining what exported bundle Vite consumes.

Our default ESM bundle contains IDX (OIE), AuthN (Classic) and the MyAccount client. Depending on your use case, you may be able to consume a specific bundle (IDX or AuthN) and avoid the circular in the MyAccount client

Refs: 
- https://github.com/okta/okta-auth-js/blob/master/package.json#L13
- https://github.com/okta/okta-auth-js/tree/master/lib/exports

**Comment by denysoblohin-okta** [comment]
Internal ref: OKTA-664667

**Comment by denysoblohin-okta** [comment]
Release 7.5.0 will contain a fix for this issue
