### ISSUE TITLE
Add authorizationServer config property

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-auth-js#149]
I should be able to configure Auth.js for OIDC in this way:

```js
var config = {
  url: 'https://{yourOktaDomain}',
  authorizationServer: 'default'
}
```

We can add this as an enhancement, where specifying an `authorizationServer` will automatically configure `issuer` under the hood:

    issuer = url + '/' + authorizationServer

**Comment by nbarbettini** [comment]
Updated:

```
var config = {
  domain: '{yourOktaDomain}',
  authorizationServer: 'default'
}
```

**Comment by aarongranick-okta** [comment]
We have decided to use the full URI for `issuer`, which includes the authorization server id. `baseUrl` has been deprecated.
