### ISSUE TITLE
Migrate type tests to TSTyche

### ISSUE THREAD

**Issue by mrazauskas** [okta/okta-auth-js#1497]
### Describe the feature request?

To draw your attention `tsd-lite` is [deprecated](https://github.com/mrazauskas/tsd-lite/issues/364). Currently `tsd-lite` is used via `jest-runner-tsd` to test types.

I was maintaining `tsd-lite` and helping with the runner too. Unfortunately the inner architecture of `tsd` is very limiting. To improve it I had to write a type test runner from scratch.

### New or Affected Resource(s)

I would like to suggest migrating type tests to TSTyche. It is a new type testing tool which is replacing `tsd-lite` and `jest-runner-tsd`.

TSTyche has a lot of improvement:

- lightweight (no dependencies, TSTyche loads and uses TypeScript you already have installed),
- performant (just give it a spin),
- helpers like `test()` and `describe()` with `.only` and `.skip` run mode modifiers,
- familiar `expect` style assertions (with matchers like `.toHaveProperty()`),
- testing on specified versions of TypeScript: `tstyche --target 4.8,latest`.

Currently TSTyche is used by Immutable.js, Jest, Redwood and few more smaller projects (including my own packages).

### Provide a documentation link

Repo: https://github.com/tstyche/tstyche
Documentation: https://tstyche.org

### Additional Information?

I can open a migration PR, if this sounds interesting.

**Comment by mrazauskas** [comment]
Also I see that some other `@okta` packages are using `tsd` is some way. Probably this means you have to decide on tooling in organisation level. I can help migrating all tests to TSTyche, if you decide so.

I could find type tests in these packages:

- [okta/okta-auth-js](https://github.com/okta/okta-auth-js)
- [okta/okta-jwt-verifier-js](https://github.com/okta/okta-jwt-verifier-js)
- [okta/okta-oidc-middleware](https://github.com/okta/okta-oidc-middleware)
- [okta/okta-react-native](https://github.com/okta/okta-react-native)
- [okta/okta-sdk-nodejs](https://github.com/okta/okta-sdk-nodejs)
- [okta/okta-signin-widget](https://github.com/okta/okta-signin-widget)

**Comment by jaredperreault-okta** [comment]
Thank you for the notice!

Internal Ref: OKTA-711014

**Comment by mrazauskas** [comment]
Thanks for response. If you decide to use TSTyche, I can help to migrate the tests.

Here are few samples of migration PRs:

https://github.com/immutable-js/immutable-js/pull/1989
https://github.com/jestjs/jest/pull/14970
https://github.com/FloEdelmann/vue-ts-types/pull/507

**Comment by jaredperreault-okta** [comment]
@mrazauskas https://github.com/okta/okta-auth-js/pull/1510

**Comment by mrazauskas** [comment]
Closing because of low activity.
