### ISSUE TITLE
Cannot sign out when DSSO is enabled

### ISSUE THREAD

**Issue by mackankowski** [okta/okta-auth-js#1503]
### Describe the bug

Hello Team,

I struggle with the issue that I cannot sign out from the app anymore (I believe it's because of DSSO enabled). No codebase had been changed (after it stopped working correctly). Right now, when I trigger the [sign-out](https://github.com/okta/okta-auth-js/?tab=readme-ov-file#signout) action, it redirects to Okta pages, I can see my username for a second I'm back redirected to the app (without the previous/current user registered). There's no change to filling the form with new account credentials. The following bypass solution is mentioned a couple of times: [navigate-to-okta-login-page-when-agentless-dsso-is-enabled](https://support.okta.com/help/s/article/navigate-to-okta-login-page-when-agentless-dsso-is-enabled?language=en_US,) but it has an unintended side effect: the redirect to the app doesn't work (I've tried to use`post_logout_redirect_uri` param but no success). I've also tried to clear cookies and storage manually (and using the `okta-auth-js`). What's more, this issue is not reproducible for Incognito mode (Chrome).

Thank you for any tip!

Best regards,
Maciej

### Reproduction Steps?

1. Sign in the user 
2. Sign out the user
3. The sign in form isn't displayed - user is automatically redirected to the app (after couple Okta redirects)

### SDK Versions

  System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 149.88 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.4

**Comment by jaredperreault-okta** [comment]
@mackankowski You will have to direct this question to [Support](https://support.okta.com/). It seems you have already tried the suggestions I would have provided.
