### ISSUE TITLE
getTokens() - Add check to see if tokens are expired (or will in 30s) and try to refresh if so

### ISSUE THREAD

**Issue by coleleep** [okta/okta-auth-js#1506]
### Describe the feature request?

Add default behavior to perform a check to see if tokens are expired/expiring and perform a refresh if so. Currently getTokens() doesn't check for this.

We can write a method to do this but it would be idea if this was default behavior: 

```
async function getAccessToken() {
  if (!(await oktaAuth.isAuthenticated()) {
    return null;
  }
  return oktaAuth.tokenManager.getTokens().accessToken;
}
```

### New or Affected Resource(s)

getTokens();

**Comment by jaredperreault-okta** [comment]
https://github.com/okta/okta-auth-js?tab=readme-ov-file#getorrenewaccesstoken has been added
