### ISSUE TITLE
Update readme to indicate that parseFromUrl function verifies tokens automatically

### ISSUE THREAD

**Issue by dogeared** [okta/okta-auth-js#151]
The [parseFromUrl](https://github.com/okta/okta-auth-js#tokenparsefromurloptions) function includes token signature verification and validation.

```(parseFromUrl -> handleOAuthResponse -> verifyToken)```

This should be indicated in the documentation so that developers are clear that they don't need to manually verify/validate the tokens on their own.

**Comment by kthomas182** [comment]
@dogeared 

Can you provide an example of this? I'm actually invoking the getWithRedirect() and passing in the redirectUri. Once authenticated the redirectUri component has the parseFromURL and retrieves the tokens (id_token, access_token) but I'm not quite sure what to do after that.

**Comment by jmelberg-okta** [comment]
Resolved with #173
