### ISSUE TITLE
Separate token.getWithPopup from Enrollment when using Social

### ISSUE THREAD

**Issue by dwburkejr** [okta/okta-auth-js#1517]
### Describe the feature request?

We are trying to integrate Okta Auth JS into a modal experience and we currently allow the user to use an IDP or email to signup and login. When using an IDP, we use the `token.getWithPopup` method to authenticate the user and get the token, however we would like the users to return to the modal to fill out the consent step rather than having it in the popup. 

Currently the flow is 
1. User opens the modal and clicks on a social provider, ie. Google
2. They choose their account
3. That account does not exist and they are redirected in the popup to the okta hosted mfe to fill out the consent step rather than going back to the modal.
4. They fill out this step
5. The popup closes and the user is prompted to fill in additional fields that we require

While this is not breaking the way they are signing up, it makes for a disjointed experience by having them answer questions in the modal and the popup. Is there a way to get the user "started" in the popup and then finish the consent step in the original page that called `token.getWithPopup`? If not, it would be nice to have since that would allow us to complete things in one modal and just have the popup be reserved for selecting the google account etc. Maybe instead of returning just the token it could return the response or step that we could then try to proceed from. 

### New or Affected Resource(s)

https://developer.okta.com/docs/guides/request-user-consent/main/
https://github.com/okta/okta-auth-js/blob/master/lib/oidc/getWithPopup.ts

**Comment by jaredperreault-okta** [comment]
I do not believe this is possible. The popup window is loading our [/authorize](https://developer.okta.com/docs/reference/api/oidc/#authorize) page and we do not currently support continuing a flow in a difference client. I'll pass this feature request along, but I will close this issue for now

As an alternative, you could explore embedding our SignIn Widget within your modal and avoid the popup behavior altogether (https://github.com/okta/okta-signin-widget)
