### ISSUE TITLE
Okta magic link not working in different browser without OTP

### ISSUE THREAD

**Issue by dineshgvr** [okta/okta-auth-js#1522]
### Describe the bug

Hi Team,
I am sending email magic link from one browser. But my requirement is that activation link should work in different browser. I went through the document, and it says we will enter the OTP in Orginial browser.

But i want to continue to activate the link without go back in orignial browser. We are developing the application using interaction flow with okta and using @okta/okta-angular and @okta/okta-auth-js.

Please let me know if there is any solution for this. Thanks

### Reproduction Steps?

1. We are dynamically building the form using the interaction flow from Okta to create one form.
2. Users fill out the form.
3. Okta email magic link is sent to the user.
4. The user clicks the magic link from a different browser.
5. We don't want to fill out the OTP in the Original Tab.
6. We want to continue here
7. Please help out this issue.

### SDK Versions

@okta/angular@6.0.0 @okta/okta-auth0js@7.2.0 using to angular 14

**Comment by jaredperreault-okta** [comment]
This isn't supported with magic link for security reasons

https://developer.okta.com/docs/guides/email-magic-links-overview/main/#same-device-same-browser-only
