### ISSUE TITLE
How to remove or set expiry date or path value change the DT in cookies

### ISSUE THREAD

**Issue by dineshKumar-gvr** [okta/okta-auth-js#1536]
### Describe the bug

I am using okta auth js library in Angular version 14. using interaction flow based on response i am building the forms by angular. 

One of the requirement,  when the application is loaded, I can see the DT (Device token) in the cookies. But for example, when I click the button, I need to remove the particular DT from cookies, set the expiry date, or modify the path for specific this DT from cookie.

Please help me out any inbuilt methods are available or not 

Thanks

### Reproduction Steps?

I am using okta auth js library in Angular version 14. using interaction flow based on response i am building the forms by angular. 

One of the requirement,  when the application is loaded, I can see the DT (Device token) in the cookies. But for example, when I click the button, I need to remove the particular DT from cookies, set the expiry date, or modify the path for specific this DT from cookie.

Please help me out any inbuilt methods are available or not 

Thanks

### SDK Versions

@okta/okta-auth-js : 7.2.0

**Comment by jaredperreault-okta** [comment]
I don't believe removing a Device Token cookie is supported (by the backend, not specifically this SDK). Do you mind elaborating on your use case a bit more?
