### ISSUE TITLE
extraParams is not passed in /authorize request when initializing Okta

### ISSUE THREAD

**Issue by Roman-Kacharaba** [okta/okta-auth-js#1537]
### Describe the bug

When I'm trying to initialize Okta with extraParams: {.foo: 'bar' }, they are not visibly in /authorize call

### Reproduction Steps?

When I'm trying to initialize Okta with extraParams: {.foo: 'bar' }, they are not visibly in /authorize call

  const tokenParams = {
    clientId: oktaConfig.clientId,
    issuer: oktaConfig.issuer,
    redirectUri: `${window.location.origin}/login/callback`,
    pkce: true,
 
    scopes: [
      'email',
      'openid',
      'profile',
      'security-cloud',
      'feature-flag',
      'security:enterprise',
      'security:context',
      'security:scc',
    ],
    extraParams: {
      foo: 'bar'
    },
    tokenUrl,
    postLogoutRedirectUri: `${window.location.origin}/logout/callback`,
  };

  **const oktaAuth = new OktaAuth(tokenParams);**
 
 ![Screenshot 2024-09-09 at 16 09 50](https://github.com/user-attachments/assets/5d998639-88ca-4e7a-bae9-164c78d9c5fb)

### SDK Versions

Version 7.9.0

**Comment by jaredperreault-okta** [comment]
`extraParams` should be passed to the method you're using to send a request to `/authorize`, like `getWithRedirect`

**Comment by Roman-Kacharaba** [comment]
> `extraParams` should be passed to the method you're using to send a request to `/authorize`, like `getWithRedirect`

Can we pass extraParams to config when initialiazing Okta ( like new OktaAuth(config) )
without getWithRedirect or getWithoutPrompt ?

**Comment by jaredperreault-okta** [comment]
That is not currently supported. Do mind elaborating on your use case?

**Comment by Roman-Kacharaba** [comment]
> That is not currently supported. Do mind elaborating on your use case?

Is there any other way to pass extraParams except getWithoutPrompt or getWithRedirect ?

Maybe we can pass some addional field to config object to avoid calling getWithoutPrompt or getWithRedirect ?

**Comment by jaredperreault-okta** [comment]
That is not supported

**Comment by Roman-Kacharaba** [comment]
> That is not currently supported. Do mind elaborating on your use case?

Can you add support for this use case ?
