### ISSUE TITLE
Refresh flow not working at all

### ISSUE THREAD

**Issue by adrianbunea** [okta/okta-auth-js#1541]
### Describe the bug

Since the autoRenew functionality is known to be buggy the developers have suggested to instead this: https://github.com/okta/okta-auth-js/blob/master/docs/autoRenew-notice.md.

I have set up a React SPA, using React Okta, I use the `authorization_code` flow with PKCE and token rotation.

Most of the code is done exactly like in the examples from the library.

Okta config is:
```js
{
    issuer: 'issuer',
    clientId: 'clientId',
    redirectUri: `${window.location.origin}/auth/callback`,
    pkce: 'true',
    responseType: 'code',
    tokenManager: {
        storage: 'cookie',
        autoRenew: true
    },
    scopes: ['openid', 'email', 'offline_access'],
    services: {
        autoRenew: false,
        autoRemove: false
    }
}
```

Before a request, I set the Authorization header using `getOrRenewAccessToken()`.

For testing purposes I set my access token lifetime to 5 minutes, refresh token lifetime to 10 minutes and in case it isn't used, it expires in 8.

The app works fine for the first 4 minutes and 30 seconds. Then if I make a request between 4:30 and 5:00, a refresh to `/token` is made successfully, and the app works fine. But if I make a request after 5 minutes, and before 8 minutes, the refresh request gives a `400` Response with no details, if I log it in the console it says the Token is expired or invalid.

From here I kept investigating and I got lots of different cases:
- `RENEW` event of `TokenManagers` says it removed the old refresh token, and added a new refresh token that is identical to the old one
- The refresh token has the same expiration as the access token in the `TokenManager` but if I call the introspect endpoint in Postman it has the correct expiration time
- Sometimes the introspect endpoint responds with `{ active: false }`

I don't know what to make of all this. I would like to see a complete example, with refresh included that works. For this flow

### Reproduction Steps?

The library is inconsistent so I cannot provide any steps that would help reproduce this. The library is breaking down in multiple ways.

### SDK Versions

@okta/okta-auth-js: 7.7.1
@okta/okta-react: 6.9.0

**Comment by adrianbunea** [comment]
As I kept testing I hit another situation:
After a login, I refreshed after around 6 or 7 minutes, and it worked, then I did an introspect request on the new refresh token, and its expiration was 3 or 4 minutes from the moment it was refreshed. It's as if it only received the remaining time of the previous refresh token I just used.

**Comment by adrianbunea** [comment]
> I tried some more things. I turned off `tokenManager`'s `autoRenew` function because according to docs it tries to refresh the tokens on an expire event and it made things harder to understand.
> 
> As I kept testing I hit another situation: After a login, I refreshed after around 6 or 7 minutes, and it worked, then I did an introspect request on the new refresh token, and its expiration was 3 or 4 minutes from the moment it was refreshed. It's as if it only received the remaining time of the previous refresh token I just used. I tried a refresh almost 5 minutes after the last refresh and as expected, the refresh failed with a 400 status code

As it turns out from another conversation I read, the time difference is because the Refresh Token lifetime doesn't reset on every refresh, if you want that functionality you set the expiration time if not used. Refresh Token lifetime should be set to something like 1 day to make the user have to log in at least every day, and the refresh chain is kept alive by the second parameter.

**Comment by adrianbunea** [comment]
Closing this as it seems to be fixed now. It appears to have been a mix of inconsistencies caused by OktaAuth being instanciated twice (though I only stored one of the instances), and a misunderstanding of what the different timelines were supposed to do.

I also think disabling `autoRenew` on `tokenManager` helps simplify things and see what was happening.

**Comment by ashishbairwa** [comment]
@adrianbunea how do you identified that you are running two OktaAuth instances? Is there any way by which I can check that. I'm facing similar issue where my org's auth server keep on firing the `detect-reuse` of refresh token event.

**Comment by adrianbunea** [comment]
@ashishbairwa I put the OktaAuth service into a singleton. My singleton was faulty and the initialization method of my singleton was being called multiple times, that's how I knew the initialization method of Okta was done multiple times.

**Comment by jaredperreault-okta** [comment]
@ashishbairwa I'm happy to help if you'd like to provide a code snippet

**Comment by jaredperreault-okta** [comment]
@ashishbairwa Are you reproduce/cause a `detect-reuse` error in your development environment? Or are these reports from production environments?

**Comment by ashishbairwa** [comment]
This error is happening in app on all environments with the code snippets mentioned above. @jaredperreault-okta

**Comment by jaredperreault-okta** [comment]
Nothing jumps out at me in the snippets you provided. This problem could be related to multiple tabs trying to refresh the same token, or simultaneous fetch requests which both require a token and therefore both refresh at the same time

Since `autoRenew` is turned off, it's unlikely a "double instantiation" issue.

**Comment by ashishbairwa** [comment]
@jaredperreault-okta Yes, we use multiple tabs, and the likelihood of needing to refresh tokens across them is quite high. What would you recommend in this scenario?

**Comment by jaredperreault-okta** [comment]
Let's confirm multi-tab is the issue first, can you try trigger a refresh in a testing/local environment with only a single tab open and see if the triggers the issue

**Comment by ashishbairwa** [comment]
Hi @jaredperreault-okta , I'm not seeing this issue with single tab. This might be related to multiple tabs
