### ISSUE TITLE
Update jsonpath

### ISSUE THREAD

**Issue by milanmayr** [okta/okta-auth-js#1544]
### Describe the bug

Update jsonpath package

### Reproduction Steps?

https://security.snyk.io/vuln/SNYK-JS-JSONPATHPLUS-7945884

### SDK Versions

```
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M3
    Memory: 114.17 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Brave Browser: 128.1.69.168
    Chrome: 129.0.6668.91
    Safari: 18.0
  npmPackages:
    @okta/okta-signin-widget: 6.0.0 => 6.0.0
```

**Comment by chaitanyareddy-mula** [comment]
Hey @milanmayr, Any tentative timeline to fix this issue?

**Comment by boubou158** [comment]
Looking forward to the merge as well. It is blocking our pipelines at the yarn audit step.

**Comment by chaitanyareddy-mula** [comment]
@boubou158  Same here, It is blocking our pipeline.

**Comment by caglayan** [comment]
Same here.

**Comment by tj1206iu** [comment]
Same here, this is blocking our pipeline too. We are using @okta/okta-vue package and it uses this @okta/okat-auth-js.
Kindly update this transitive dependency.

**Comment by adamacrumb** [comment]
Same here, it would be nice to take care of critical vulnerabilities.

**Comment by jakub-m-sobczak** [comment]
Please take care of this issue, it is blocking a lot of people and it's been 5 days already...

**Comment by n4cho** [comment]
Me as well! Please, provide a solution! Thank you

**Comment by jaredperreault-okta** [comment]
https://github.com/okta/okta-auth-js/pull/1545#issuecomment-2411123107

**Comment by kdmiltner** [comment]
Following along as I'm interested in this getting merged in as well.

**Comment by dngconsulting** [comment]
same here

**Comment by chaitanyareddy-mula** [comment]
Hey @milanmayr, What does the eval key do within the jsonpath-plus? Is it something critical key that need to be passed or can be ignored?

**Comment by milanmayr** [comment]
> Continuing [#1545 (comment)](https://github.com/okta/okta-auth-js/pull/1545#issuecomment-2417507980),
> 
> Hey @milanmayr, What does the eval key do within the jsonpath-plus? Is it something critical key that need to be passed or can be ignored?

I don't use this package myself -- just advocating for a team that needs this done. Maybe the [docs](https://www.npmjs.com/package/jsonpath-plus) can help?

**Comment by rwreplog** [comment]
Following, thank you!

**Comment by chaitanyareddy-mula** [comment]
@milanmayr I see within the okta-auth-js, we are setting preventEval as true which will avoid evaluating the expression. So can i ask the developers to help me to answer whether it is fine to override the package of jsonpath-plus to ^10.0.1?

**Comment by chaitanyareddy-mula** [comment]
In jsonpath-plus 10.0.0 version, if the value of eval key is undefined, the value is being set to 'safe' by default. So wanted to check whether there will be any impact from okta end with the default value as 'safe' if i try to override the package to 10.0.0?

**Comment by chaluck-mm** [comment]
following.....

**Comment by milanmayr** [comment]
> Hey @milanmayr, Any tentative timeline to fix this issue?

It looks like this work is being done in a different PR. You can track the work [here](https://github.com/okta/okta-auth-js/pull/1547)

**Comment by chaitanyareddy-mula** [comment]
Hey @milanmayr , The issue is tagged to 7.8.1, so when can we expect the release for this issue?

**Comment by jaredperreault-okta** [comment]
Addressed in [7.8.1](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-7.8.1) (released on npm)

**Comment by chaitanyareddy-mula** [comment]
Thank you @jaredperreault-okta

**Comment by jakub-m-sobczak** [comment]
Thank you @jaredperreault-okta
