### ISSUE TITLE
Library configuration checks

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-auth-js#155]
To help avoid misconfiguration, this library should implement these checks against common errors: https://oktawiki.atlassian.net/wiki/spaces/PM/pages/552049922/Library+configuration+checks

For this library, these checks apply:

- [ ] Issuer or `url`
- [ ] Client ID

**Comment by aarongranick-okta** [comment]
configuration is being validated: https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/builderUtil.js#L18
