### ISSUE TITLE
Invalid Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by stormit-vn** [okta/okta-auth-js#156]
My development environment running at http://localhost:3000, the callback also set to http://localhost:3000/implicit/callback. However, I am receiving an error related to the Access-Control-Allow-Origin header when calling https://domain.oktapreview.com/oauth2/default/v1/keys API

Failed to load https://domain.oktapreview.com/oauth2/default/v1/keys: The 'Access-Control-Allow-Origin' header has a value 'https://myapp.example.com' that is not equal to the supplied origin. Origin 'http://localhost:3000' is therefore not allowed access.

Note, I am running two different environments, once at http://localhost:3000 and another one at https://myapp.example.com. I have already logged at https://myapp.example.com, so I think Okta is getting cached origin somewhere instead of the current login context.

This issue happens when I upgraded to the latest okta version 1.0.3, it does not appear in the previous version 1.0.1

**Comment by roski** [comment]
@stormit-vnI I have the same problem. Do you find the solution?

**Comment by YoniH** [comment]
#metoo
Did anyone find a solution?

**Comment by YoniH** [comment]
Sure

**Comment by jmelberg-okta** [comment]
Hi all,

Our API team is aware of this issue and working to resolve it this month. We're tracking and providing updates to this issue here: [#541](https://github.com/okta/okta-signin-widget/issues/541).

Closing this issue as a duplicate.
