### ISSUE TITLE
Browser closing causes tokenManager to not refresh access token after expiration

### ISSUE THREAD

**Issue by johnstew** [okta/okta-auth-js#169]
So I'm not sure if this is by design or I'm missing an implementation detail but we are experiencing the following scenarios.

**Browser Open**
- User logs in via Okta Sign In Widget
- `id_token` and `access_token` are set 👍 
- open some tabs, browse the internet
- come back to my page, 5 minutes(time to expiration) has gone by and `tokenManager` refreshes user `access_token` and I'm good

**Browser Close**
- User logs in via Okta Sign In Widget
- `id_token` and `access_token` are set 👍 
- open some tabs, browse the internet, **close my browser**
- open browser, come back to my page, 5 minutes(time to expiration) has gone by and `tokenManager` does not refresh the user `access_token`

Is this intended behavior? Feels like I'm missing a step.

**Comment by jmelberg-okta** [comment]
Hi @johnstew -

Thanks for the report!

When tokens are stored in the browser they being placed inside of `localStorage`, `sessionStorage`, or as a `cookie`. Depending on browser compatibility, we will fall-back to `sessionStorage` if `localStorage` isn't available - which would explain the session persistance issue.

When a user logs in using the Widget, can you verify that tokens are stored properly in `localStorage`?

**Comment by johnstew** [comment]
After reviewing our implementation we are storing the tokens properly but I think the issue is in how we are verifying the tokens. Here is the pseudocode.

**Token Storage**
```js
signInWidget.tokenManager.add('id_token', res[0]);
signInWidget.tokenManager.add('access_token', res[1]);
```

**User Logged In Check**
```js
const idToken = signInWidget.tokenManager.get('id_token');

oktaAuthClient.verify(idToken)
.then((claims) => console.log('Logged In!'))
.catch((error) => console.error('Not Logged In!', error);
```

[According to docs](https://github.com/okta/okta-auth-js#the-tokenmanager) if I call `.get('access_token')` that should help in keeping the `access_token` refreshed.

After speaking to an Okta rep it seems we should also be checking the session [via `session.exists`](https://github.com/okta/okta-auth-js#sessionexists) then make a call to [`session.refresh`](https://github.com/okta/okta-auth-js#sessionrefresh) as well.

So I'm thinking of doing something like this:

```
// if session.exists
// get(access_token), get(id_token)
// oktaAuth.verify(access_token), oktaAuth.verify(id_token)
// if tokens.verified
// session.refresh()
```

End goal is, access token and id token stay alive for longer than an hour. 

Open to any advice and suggestions. Thanks!

**Comment by jmelberg-okta** [comment]
@johnstew - Thanks for providing context in what you're trying to accomplish!

Couple of questions/suggestions:

1. How long is your Okta [Session Lifetime](https://support.okta.com/help/s/question/0D50Z00008C3jntSAB/okta-portal-session-timeout) configured? If you set this value to `> 1 hour`, the `tokenManager.get` method will continue to renew tokens as long as that session is **active**.
2. By default, this library will validate the `idToken` when it is returned via the `/authorize` endpoint. The client (your application for example) doesn't need to validate the `accessToken`. In practice, your application will pass this `accessToken` to another service, which will then need to validate it.
3. Instead of attempting to renew the Okta session using `session.refresh` (must be done when the session is still active), I'd suggest re-authorizing. For example:

```javascript
try {
  oktaAuth.tokenManager.get('accessToken')
  .then(token => console.log('I received an active token!'))
  .catch(err => console.error(err));
} catch (error) {
  // The Okta session has most likely ended. Lets prompt for login again via:
  // getWithRedirect or getWithPopup
  oktaAuth.token.getWithRedirect(..options);
}
```

Hope this helps!

**Comment by johnstew** [comment]
This is helpful, thank you!

1. Session Lifetime = 3 months
2. I will remove the `.verify` call that I have.

Are `session`'s and `token`'s supposed to be used together?

**Comment by aarongranick-okta** [comment]
@johnstew I realize this issue is old. We have made several releases to `okta-auth-js` including some fixes to the token renew logic which may have been affecting your application. Are you still experiencing any issues with token renew?

**Comment by swiftone** [comment]
Closing this issue as stale and out of date.  Anyone having a similar problem should open a new issue with details and can reference this one in it.
