### ISSUE TITLE
Changing origins causes unexpected CORS error

### ISSUE THREAD

**Issue by Daniel-Houston** [okta/okta-auth-js#170]
We are sharing an okta preview tenant for both local development and a staging environment.

If I switch origins in a browser session (from localhost to dev.srdev.io) without clearing the cache, I get a CORS error on the key retrieval request during token verification. I have to do a hard reload in order for the CORS error to go away.

Both origins have been whitelisted in Okta as trusted origins with CORS enabled.

The exact console error is: 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login-dev.solutionreach.com/oauth2/ausdhrfxghzE4BQHW0h7/v1/keys. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘http://localhost:3000’).
```

I believe the CORS error is happening because of some request caching that okta-auth-js does.

Any insights in how to fix this would be appreciated.

**Comment by jmelberg-okta** [comment]
Hi @Daniel-Houston,

Our API team is aware of this issue and working to resolve it this month. We're tracking and providing updates to this issue here: [#541](https://github.com/okta/okta-signin-widget/issues/541).

Closing this issue as a duplicate.
