### ISSUE TITLE
2.1.0 - AuthSdkError - errorSummary: "The full page redirect flow is not supported"

### ISSUE THREAD

**Issue by kthomas182** [okta/okta-auth-js#174]
When we upgrade our version to 2.1.0 and we try to authenticate we receive an AuthSdkError.

errorCauses: []
errorCode: "INTERNAL"
errorId: "INTERNAL"
errorLink: "INTERNAL"
errorSummary: "The full page redirect flow is not supported"
message: "The full page redirect flow is not supported"
name: "AuthSdkError"

![2018-11-07_07-19-50](https://user-images.githubusercontent.com/5391542/48158174-71ae7d80-e297-11e8-95e0-6adb3805b22d.jpg)

**Comment by robertsmith2** [comment]
I am also getting this error, it is intermittently happening when the token.js renewToken() is called. The flow type gets set as implicit and throws the error.

**Comment by webdeveloperninja** [comment]
Thanks

**Comment by jmelberg-okta** [comment]
Sorry for the bug all - this issue has been resolved with [`@okta/okta-auth-js@2.2.0`](https://github.com/okta/okta-auth-js/releases/tag/%40okta%2Fokta-auth-js%402.2.0).
