### ISSUE TITLE
Update changelog to show 2.1.0 changes

### ISSUE THREAD

**Issue by RacingTadpole** [okta/okta-auth-js#176]
Could you update the CHANGELOG to show the changes in 2.1.0? It would be a great help in deciding whether to upgrade or not (especially in light of #174).

Although I've just discovered your github release page shows the changes, https://github.com/okta/okta-auth-js/releases, including for 2.1.0.  Would it be worth putting a link to that page at the top of the changelog to help people discover it?

Thanks!

**Comment by jmelberg-okta** [comment]
Thanks for the report @RacingTadpole! Captured all recent changes with #179.
