### ISSUE TITLE
tokenManager.on('renew') not working

### ISSUE THREAD

**Issue by maniyarkj** [okta/okta-auth-js#181]
I'm using Okta and Angular with Custom Login Screen instead of okta-sign-in widget. After success of  .createAndSaveNonce() method, I'm calling .signIn() method with username & password which will return tokens. After receiving I'm adding token values to tokenManager with keys and then, added tokenManager.on('expired') and tokenManager.on('renewed') event. However, I found that when my token get expired, the tokenManager.on('expired') is called but renewed is never called.

I read everywhere that tokenManager will renew the token, but it's not happening here.

My code is as below..

```
import { Injectable } from "@angular/core";
import { JwksValidationHandler, OAuthService } from 'angular-oauth2-oidc';
import * as OktaAuth from '@okta/okta-auth-js';
import { BehaviorSubject } from "rxjs";

declare const window: any;
@Injectable()
export class OktaService {
    networkStatus$: BehaviorSubject<boolean> = new BehaviorSubject(true);
    baseOktaURL: string = 'my.oktapreview.com';
    rUri = window.location.origin;
    clientId: string  = 'myclientId';
    oktaScope: string = 'openid profile email groups';
    oktaIssurer = 'myIssuer';

    authClient = new OktaAuth({
        clientId: this.clientId,
        redirectUri: this.rUri,
        url: this.baseOktaURL, 
        issuer: this.oktaIssurer, 
        tokenManager: {
            storage: 'sessionStorage',
        }
    });

    constructor(private oauthService: OAuthService) {
        oauthService.redirectUri = window.location.origin; 
        oauthService.clientId = this.clientId;
        oauthService.scope = this.oktaScope;
        oauthService.issuer = this.oktaIssurer;
        oauthService.tokenValidationHandler = new JwksValidationHandler();

        this.oauthService.loadDiscoveryDocument().then(
            () => {
                this.oauthService.tryLogin();
            }
        )
    }

    login(username: string, password: string): Promise<any> {
        console.log('in login');
        return this.oauthService.createAndSaveNonce().then(nonce => {

            return this.authClient.signIn({
                username: username,
                password: password
            })
                .then(
                    resLogin => {
                        console.log(resLogin);

                        if (resLogin.status === 'SUCCESS') {
                            return this.authClient.token.getWithoutPrompt({
                                nonce: nonce,
                                responseType: ['id_token', 'token'],
                                sessionToken: resLogin.sessionToken,
                                scopes: this.oauthService.scope.split(' ')
                            }).then(
                                tokens => {
                                    this.authClient.tokenManager.add('myIdToken', tokens[0]);
                                    this.authClient.tokenManager.add('myAccessToken', tokens[1]);
                                    this.tokenManagement(); // This will add expire and renew event
                                    return tokens;
                                },
                                tokenErrors => {
                                    Promise.reject(tokenErrors.message || tokenErrors);
                                }
                            );
                        }
                    }
                )
                .catch(
                    err => {
                        console.log(err);
                        Promise.reject(err.message || err);
                    }
                );
        });
    }
    tokenManagement() : void {
        this.authClient.tokenManager.on('expired', function (myAccessToken, newToken, oldToken) {
            alert('hey expired'); // This is called
            console.log(myAccessToken);
            console.log(oldToken);
            console.log(newToken);
        });
        this.authClient.tokenManager.on('renewed', function (myAccessToken, newToken, oldToken) {
            console.log('Token with key', myAccessToken, 'has been renewed');
            console.log('Old token:', oldToken);
            console.log('New token:', newToken);
        });
    }
    logout() {
        this.authClient.tokenManager.clear();
    }
}
```

**Comment by recalcitrantje** [comment]
Nicw

**Comment by MarcusChamberlain** [comment]
I'm noticing the same behavior. My steps were:
1) Set the Session length in Okta to 3 hours
2) Set the access token lifetime to 5 minutes
3) Ran the sample app found at: https://github.com/okta/samples-js-angular 
4) Wait until the 'expire' event is emitted.

If I look at the 'expiresAt' value in local storage, the value remains unchanged. If I try and access the 'messages' protected route in the sample, I begin getting a 401.

It seems that the demo app usually works by calling 'isAuthenticated' in the route guard, which itself calls 'renew' in the tokenmanager and pushes the 'expiresAt' value forward. If you don't rely on that though (similar to the example above by maniyarkj) and just leave the page open, the token expires and the tokenmanager never renews it.

**Comment by haishengwu-okta** [comment]
> By default, the `tokenManager` will attempt to renew expired tokens. When an expired token is requested by the `tokenManager.get()` method, a renewal request is executed to update the token. If you wish to manually control token renewal, set `autoRenew` to false to disable this feature. You can listen to  [`expired`](#tokenmanageronevent-callback-context) events to know when the token has expired.

I think it means when `autoRenew` is on (by default), you don't need to worry about expiration. Every time invoke `tokenManager.get`, sdk will try to renew.
Otherwise, as you listen to the 'expired' event,  you need to invoke `tokenManager.renew` manually.

**Comment by johnstew** [comment]
I can confirm that this isn't working for me either with `autoRenew: false`. None of the events fire. Ever.

How are we supposed to manage the lifecycle of the tokens?

**Comment by aarongranick-okta** [comment]
Closing issue as it appears to be no longer relevant with current version. Here is the documentation for the TokenManager events: https://github.com/okta/okta-auth-js#tokenmanageronevent-callback-context
