### ISSUE TITLE
Question: EOL Plan for V1

### ISSUE THREAD

**Issue by jennasalau** [okta/okta-auth-js#190]
Hi,

I noticed on your readme you have the following next to V1

> ⚠️ Retiring on 2019-05-31

Can you please tell me what to expect post this date for those of us using V1?

It may take us some time to upgrade.

**Comment by jennasalau** [comment]
Hello?

**Comment by haishengwu-okta** [comment]
@jennasalau 
https://developer.okta.com/code/library-versions/

**Comment by jennasalau** [comment]
Thank you.
