### ISSUE TITLE
Okta CORS Headers Cached okta-auth-js

### ISSUE THREAD

**Issue by datadidit** [okta/okta-auth-js#191]
Having issues with `okta-auth-js` version 2.3.1 it appears that the library/browser is caching the CORS related headers in chrome. I'm running into this error because I have an application that I'm developing locally and access via `http://localhost:3005`. The Library/Browser caches that as the `Access-Control-Allow-Origin` for the `okta-auth-js` client. This is fine when doing development. Once I'm done a feature and do a deploy my `Access-Control-Allow-Origin` is no longer `http://localhost:3005` and instead has an actual host. If I try to login without clearing my history at this point I'll receive an error indicating that the `Access-Control-Allow-Origin` is still being set to `http://localhost:3005` instead of the proper host.

Here is my code for initializing the client:

```
let OktaAuth = require("@okta/okta-auth-js");

// Load redirect uri from window.href when possible else default to prod url
let redirectURI;
try {
    redirectURI = `${window.location.protocol}//${window.location.hostname}`;
    if (window.location.hostname === "localhost") {
        redirectURI = `${redirectURI}:3005`;
    }
    LOGGER.info(`Redirect URI computed as ${redirectURI}`)
} catch (err) {
    redirectURI = "<insert prod redirect uri>";
    LOGGER.error(`Unable to compute redirect uri from window using default ${redirectURI}`)
}

export const oktaClient = new OktaAuth({
    url: "<insert auth okta auth server>",
    clientId: "<insert client id>",
    redirectUri: redirectURI
});
```

**Comment by datadidit** [comment]
Also I'm using the same `clientId` and have multiple allowed redirectURIs for my application in this case. Haven't tried it yet but could this issue not occur if I had different Okta applications for my dev vs. prod environment apps.

Also it appears one way around this would be to use https://github.com/okta/okta-auth-js#optional-configuration-options . Is there a more fleshed out example of this if I need to go down this route.

**Comment by swiftone** [comment]
Managing the caching of CORS headers is being addressed by a feature flag that is cautiously making its way into general use.  In the meantime you can request access from support, see https://github.com/okta/okta-signin-widget/issues/541#issuecomment-451044362 for details.

I'm closing this issue as a duplicate - the main issue will remain open until the feature is generally available.

**Comment by datadidit** [comment]
@swiftone thanks for the update!
