### ISSUE TITLE
authClient.token.getWithoutPrompt

### ISSUE THREAD

**Issue by tonywong625** [okta/okta-auth-js#202]
Im building a prototype atm, trying to create a nodejs backend to authenticate users, store tokens etc.

This is my code:
```
        const config = {
          url: "https://<url>.okta.com",
          issuer: "https://<url>.okta.com/oauth2/default",
          clientId: "<clientId>",
          redirectUri: "https://<url>.okta.com",
          // TokenManager config
          tokenManager: {
            storage: "sessionStorage"
          }
        };
        const authClient = new OktaAuth(config);

        authClient.token
          .getWithoutPrompt({
            responseType: "id_token", // or array of types
            sessionToken: transaction.sessionToken,
            scopes: ["openid", "email"]
          })
```

However I am getting 
```
TypeError: Cannot read property 'getWithoutPrompt' of undefined
```

It looks like authClient.token is undefined. 
Anyone have any ideas?

**Comment by Sothos** [comment]
I'm having the same issue. OktaAuth 2.2.0 works fine, OktaAuth 2.3.0 is borked. At least if downloaded from the Okta CDN. I haven't tried the npm package.

`const authClient = new OktaAuth(config);` 

creates an object missing a bunch of properties including token in 2.3.0 or 2.3.1

**Comment by tonywong625** [comment]
Tried npm 2.1.0, 2.2.0, 2.3.1, 2.4.0 still not doing it for me. I wonder if token and tokenmanger needs to live on the client side

**Comment by swiftone** [comment]
Thanks for the detailed issue description!

The NodeJS backend doesn't support token management (without a frontend that does it)  
 see https://github.com/okta/okta-auth-js#node-js-usage- it supports any of the management APIs however.   I've sent this issue to our our product team to note the request.

**Comment by nbarbettini** [comment]
@tonywong625 @Sothos I'm really interested to get more information on what you're building and how we can make it easier. If you have time, shoot me an email: nate.barbettini@okta.com
