### ISSUE TITLE
Allow login_hint option for token authorization

### ISSUE THREAD

**Issue by mzbyszynski** [okta/okta-auth-js#214]
If I understand the documentation correctly, all the [/authorize](https://developer.okta.com/docs/api/resources/oidc/#authorize) parameters should be available for `token.getWithRedirect()`. But currently I don't think the `login_hint` parameter is supported.

I believe the easiest fix for this would be to add `login_hint` here:

https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L239-L251

```
var oauthQueryParams = util.removeNils({
    'client_id': oauthParams.clientId,
    'redirect_uri': oauthParams.redirectUri,
    'response_type': oauthParams.responseType,
    'response_mode': oauthParams.responseMode,
    'state': oauthParams.state,
    'nonce': oauthParams.nonce,
    'prompt': oauthParams.prompt,
    'display': oauthParams.display,
    'sessionToken': oauthParams.sessionToken,
    'idp': oauthParams.idp,
    'max_age': oauthParams.maxAge,
    'login_hint': oauthParams.login_hint // <- I added this
  });
```

Is this correct? I'm happy to submit a PR if you think this fix would be helpful.

**Comment by swiftone** [comment]
@mzbyszynski - Thanks for the report.  This has been corrected with v2.7.0 (note that it will be passed as `loginHint`, consistent with our other camelCase->snake_case variables)
