### ISSUE TITLE
npm module

### ISSUE THREAD

**Issue by kelly-vernon-volusion** [okta/okta-auth-js#22]
This is more of a feature request, but it would be great if you guys had npm registry item.

Thanks,
Kelly

**Comment by rchild-okta** [comment]
@kelly-vernon-volusion yep, nice timing - we're actually working on this now. It should be out soon - will update this issue when it's been published.

**Comment by rchild-okta** [comment]
@kelly-vernon-volusion published to NPM!
https://www.npmjs.com/package/@okta/okta-auth-js

**Comment by thurber** [comment]
It would be awesome if you bundled this npm package as a CommonJS and/or AMD module so that consumers could `import okta from @okta/okta-auth-js` or `var okta = require('@okta/okta-auth-js')`

**Comment by lboyette-okta** [comment]
You're in luck; we support CommonJS!

Install with `npm install @okta/okta-auth-js`

Then the following should work:
```
var OktaAuth = require('@okta/okta-auth-js`);

var client = new OktaAuth({url: 'https://your-org.okta.com'});
```

ES6 imports aren't yet supported.

**Comment by lboyette-okta** [comment]
@thurber Gotcha. It seems webpack doesn't allow requiring json by default. We should be able to remove the dependency on the json-loader in an upcoming version. Thanks for the feedback!

**Comment by lboyette-okta** [comment]
@thurber You won't need the json-loader in the next release (https://github.com/okta/okta-auth-js/pull/33)

**Comment by thurber** [comment]
@lboyette-okta beautiful, thanks!
