### ISSUE TITLE
getWithPopup infinite loop error

### ISSUE THREAD

**Issue by goatandsheep** [okta/okta-auth-js#221]
Popup blockers makes my browser print hundreds of errors because I first have to disable the popup blocker, which means the first `getWithPopup` is blocked and never resolved causing an infinite loop where the popup polls until it is resolved. Then the user allows popups, then a second popup can open.

**Comment by banjolina-jolie** [comment]
+1
It causes this error:
```js
 Uncaught TypeError: Cannot read property 'closed' of null
    at hasClosed (token.js?518d:470)
```
