### ISSUE TITLE
Authorization endpoint having existing query parameters

### ISSUE THREAD

**Issue by rcollette** [okta/okta-auth-js#223]
We have a company wide shared "login" page, rather than using an Okta hosted login page.

This page requires query string parameters (ex. an appId/Name being logged into, which may determine available locales,etc.)

The auth-js library presumes that there are no existing query string parameters on the configured authorizeUrl and appends its query string parameters prefixed with a question mark (?)

http://authUrlHost?applicationName=Something?client_id......

This prevents us from using the suite of Okta SDKs/Libraries (ex. Angular) because the query string parameters appended to the authorize endpoint url are not recognized.

Is there any reason the appending of the ? mark cannot be conditional based on whether or not there are already query parameters present in the provided endpoint URL?  I would be happy to generate a PR if there is no technical limitation.

**Comment by swiftone** [comment]
Hi @rcollette, and thanks for the comment.  

To address your core issue, it would be helpful to have a little more clarity (for example, you've posted this in our `okta-auth-js` library, but then mention some of our SDKs that live in `okta-oidc-js`).  Can you tell us what calls you're making (or wanting to make) where you see this lack of parameterization ?

If you're looking at `okta-auth-js`, you might be helped by setting the `responseMode` setting to `fragment`: https://github.com/okta/okta-auth-js#token.   (Or that might not be what you're looking for at all)

And to your direct question:  Is there a technical limitation barring extra query parameters on the url? That depends ON WHICH URL.  (for example, the redirect_uri from an OIDC login MUST be an exact match for a predefined URI, according to the OIDC spec).  So a better answer here depends on your answer to the above question about context.

Sorry I can't be more helpful just yet, but let me (us) know and we'll see if we can take care of your issue.

**Comment by rcollette** [comment]
Perhaps this hack provides some clarification?   The code is in Angular but it's monkey patching okta-auth-js ( I think?  I navigated this through debugger properties but it's possible it's auth-js relying on another library)

```typescript
import { Component, OnInit } from '@angular/core';
import { OktaAuthService } from '@okta/okta-angular';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  constructor(private _authService: OktaAuthService) {
    const getWithRedirect: any = (_authService as any).oktaAuth.token.getWithRedirect;
    // Monkey patch the private SDK method so we can call a custom login page that takes the original
    // authorization server that the SDK wants to call and passes it as a parameter to the login page.
    getWithRedirect._setLocation = AppComponent._setLocation;
  }
  private static _setLocation(url: string): void {
    // TODO - make this configurable
    window.location.href = 'https://loginPageHostName/login?productId=someApplicationId&TargetResource='
      + encodeURIComponent(url);
  }
  ngOnInit() {
  }
}
```

**Comment by swiftone** [comment]
Thanks for the detail @rcollette - 

Unfortunately, I don't think this is going to work as you desire.  The OIDC spec is fairly clear about not permitting arbitrary query parameters on redirects.

That said, you can do work arounds such as saving the data in the browser (localStorage, for example) before the redirect and then using that data after the redirect to take whatever action (another redirect, etc) you desire. 

Hope that helps!
