### ISSUE TITLE
Update readme to reflect retired version

### ISSUE THREAD

**Issue by mattwallx** [okta/okta-auth-js#227]
Readme states for v1.x: 

⚠️ Retiring on 2019-05-31

But this date has already passed.

**Comment by rMethre** [comment]
Sorry, I have 2.13.2 version running on production. Does retiring mean stop working or it will just stop supporting from 01-oct-2020?

It would be great if you can help me here

**Comment by aarongranick-okta** [comment]
@rMethre It will not stop working and we will not remove it from NPM. But we will not be releasing any updates or fixes on version 2. We do recommend updating to a newer version to take advantage of support for newer features, such as PKCE authentication or Typescript support.
