### ISSUE TITLE
Error with Login function

### ISSUE THREAD

**Issue by jphines57** [okta/okta-auth-js#228]
We are using 2.0.0 version, when calling oktaAuth.login() function an error is caught but when we try to examine the error, it's value is 'undefined'. What does this mean? Is there an issue connecting to the Okta Authorization server? 

![statusUndefined](https://user-images.githubusercontent.com/33983538/61217679-3265e580-a6de-11e9-84ac-bc872b9546ce.png)

**Comment by swiftone** [comment]
Hi @jphines57 - thanks for the report.  Is there a blocker to trying this with the latest published version of the module (2.6.0)?  Is the problem present there?

**Comment by shuowu** [comment]
@jphines57 Based on the [release status](https://github.com/okta/okta-auth-js#release-status), version 2.x has been retired. Can you try the latest version (5.x)?

Closing the issue, feel free to re-open it if any further issue is found.
