### ISSUE TITLE
IE11 token getWithRedirect is not redirecting

### ISSUE THREAD

**Issue by mpGitHub** [okta/okta-auth-js#240]
I have a legacy vanilla JS app that I am setting up OKTA authentication. I am referencing an external the okta-auth-js/dist folder that is up on a separate server.

The code works great in Chrome, but seems to choke in IE11. The code just stalls when it tries to call getWithRedirect. No errors in the console are thrown. 

```
 // Launches the login redirect.
   oktaAuth.token.getWithRedirect({
    responseType: ['id_token', 'token'],
    scopes: ['openid', 'profile']
  });
```

I'm guessing it has to do with polyfills or something of that sort. I was able to get my Angular 7 app to work by setting those up. 

This app is slightly different as it is an old vanilla jquery app that I am just referencing the OKTA app from. I ran the functions that reference ES6 promise functions through Babel which allows this part to work, but since the getWithRedirect is separately inside the okta js lib this isn't working here.

Thoughts?

**Comment by frbaroni** [comment]
Hello,

After hours of troubleshooting and having the same error, I fixed this issue.
Like you guessed, this is related to polyfills

```
function getWithRedirect(sdk, oauthOptions, options) {
  oauthOptions = util.clone(oauthOptions) || {};

  return prepareOauthParams(sdk, oauthOptions)
    .then(function(oauthParams) {
      // Dynamically set the responseMode unless the user has provided one
      // Server-side flow requires query. Client-side apps usually prefer fragment.
      if (!oauthOptions.responseMode) {
        if (oauthParams.responseType.includes('code') && !oauthParams.pkce) {
```

When Okta goes to the last line of that snipped, it will fail on IE11 because no .includes() function exists.
I fixed by adding a simple polyfill for that:

```
if (!Object.is) {
  // eslint-disable-next-line no-extend-native
  Object.is = function is(x, y) {
    if (x === y) {
      return x !== 0 || 1 / x === 1 / y;
    }
    return x !== x && y !== y; // eslint-disable-line no-self-compare
  };
}

if (!Array.prototype.includes) {
  // eslint-disable-next-line no-extend-native
  Array.prototype.includes = function includes(value) {
    for (let i = 0; i < this.length; i += 1) {
      if (Object.is(this[i], value)) {
        return true;
      }
    }
    return false;
  };
}
```

**Comment by swiftone** [comment]
Hi @frbaroni - thanks for the workaround!  

In general we are not bundling polyfills so as to avoid any complications with any polyfill bundling done by consuming developers.  

That said, we can definitely improve our documentation around this.  Thanks for sharing your solution!

**Comment by aarongranick-okta** [comment]
Created an internal issue to improve documentation for IE11: OKTA-263513

**Comment by aarongranick-okta** [comment]
https://github.com/okta/okta-auth-js#browser-compatibility
