### ISSUE TITLE
Improper override to explicit configuration

### ISSUE THREAD

**Issue by SteveByerly** [okta/okta-auth-js#241]
In `browser.js`
https://github.com/okta/okta-auth-js/blob/master/lib/browser/browser.js#L35

```
var usePKCE = args.pkce || args.grantType === 'authorization_code';
```

This overrides a configuration that explicitly sets `pkce: false`

If this is intentional behavior, the code should check for a configuration with `pkce: false` and `grantType: 'authorization_code` and throw an error that the configuration is invalid.

**Comment by swiftone** [comment]
@SteveByerly - Thanks for the report.  

Using `pkce: false` isn't a documented or supported concept, and we recommend against using grantType as 'authorization_code' - that's deprecated and everyone is happier if such code never exists.  

Use `pkce: true` to opt-in to using PKCE, and don't use grantType in PKCE situations.  

We considered allowing a more explicit `pkce: false`, but that creates painful corner cases that we want to avoid.  Follow the rule above and you'll be fine.
