### ISSUE TITLE
PKCE authorization code flow returns code in query, which library can't parse

### ISSUE THREAD

**Issue by SlvrEagle23** [okta/okta-auth-js#250]
I've switched to using the authorization code grant with PKCE, and as part of that implementation, it sends the `response_type=query` parameter to the OAuth2 server, which is also the default response type for auth code grant types.

However, when the redirect returns to the application, `token.parseFromUrl` seems to be incapable of parsing these query parameters, instead failing because there is no `#` present, indicating that a URL fragment is present.

This seems to suggest that, at least at the moment, the authorization code process using the query response type is not possible to implement fully via this library. Since this library is one of the best-fleshed-out client-side libraries that even touches the subject of PKCE, it would be immensely useful if it could close the loop and handle query parameters as well.

**Comment by swiftone** [comment]
>  it sends the response_type=query parameter

This should not be happening.

1) Are you using the latest version of the auth-js library?  PKCE support was only added recently.
2) Are you setting `pkce: true` in your config?
3) "authorization code grant with PKCE" refers to your org settings, correct?  Both the client and the okta org have to be set to use PKCE.

**Comment by SlvrEagle23** [comment]
@swiftone So after spending a little more time on this, it's clear that my OAuth server implementation is ignoring the `response_mode` parameter and sending over whatever the default is for the given grant method, i.e. "fragment" for implicit and "query" for auth code. I've spun up a new issue with them to resolve that on their end. I can verify that on the `okta-auth-js` repo's end, it is properly setting this to "fragment", which it can parse.

(I'm aware that it's likely not officially supported to use this library with OAuth/OIDC implementations that aren't Okta itself, but truth be told, it's one of very, very, very few JS client-side libraries that support PKCE, so it was a calculated risk on my end!)
