### ISSUE TITLE
Sign in/Sign out for deleted user

### ISSUE THREAD

**Issue by RamzesIX** [okta/okta-auth-js#258]
Hello.

We face an issue for deleted users in Okta. In our application administrator can delete user from the system. To do this we requests Okta API to deactivate and then delete the user. Everything is ok and we got correct response from the Okta API - user is deleted. Then, if this deleted user tries to sign out he got an 404 error: `Not found: Resource not found: SOME_ID (Principal)`. The main problem here is that user can't sign at all (same 404 error here) - no matter which credentials user provides. Looks like the issues in cookies used by Okta on every request so user is considered like existing user in Okta. The only way to resolve it - clear browser cookies and then sign in. Only after cookies deleting, Okta auth flow works correctly.

Reproduces on Chrome, FE browsers (didn't check the others).

**Comment by swiftone** [comment]
Hi @RamzesIX, thanks for the report.  This is how it works because the token needed for login (and log_out_) is deleted when the user is.  The issue is at the Okta service rather than at this SDK - I suggest you reach out to the support team at developers@okta.com with your report.
