### ISSUE TITLE
2.10 is missing file(s)

### ISSUE THREAD

**Issue by michmerr** [okta/okta-auth-js#275]
Builds with this package as a dependency fail with the following error:
```
18:23:57 ./node_modules/@okta/okta-auth-js/lib/browser/browserStorage.js
18:23:57 Cannot find module: '../config'. Make sure this package is installed.
```
config.js is not present in 2.10 (it is present in previous versions).

**Comment by sirohiwebdev** [comment]
Same issue in the latest **2.10.0** version.
I think '**lib**' folder does not have '**config.js**' file which is included in '**lib/browser/browserStorage.js**'

**Comment by rluncasu** [comment]
I can confirm it's broken, you've made recent changes, renaming config.js to constants.js.(2.11). Can you please just publish 2.11 ? It would fix the issue above, while also providing me with the much needed custom storage for token manager. Really need that feature :).

**Comment by swiftone** [comment]
Working on getting the correct file published.  Thanks for the report, @michmerr.

**Comment by swiftone** [comment]
While we are getting an update out, another user has listed the steps to workaround in interim for anyone that is blocked.  https://github.com/okta/okta-auth-js/issues/278#issuecomment-553955446

**Comment by RyanCCollins** [comment]
This broke our production app unfortunately :( . We are going to have to add a hard resolution to 2.9.0 from now on and remove any careting.  Just mentioning this to let you know we had an impact from it.  Hope it gets fixed soon.

**Comment by swiftone** [comment]
@okta/okta-auth-js 2.10.1 has been published to npm, which should address this error.  This error resulted from a problem where our build system released an incorrect version.

We apologize for any inconvenience, and thank you for your patience, with particular thanks to the developers that reported the bug and helped each other with workarounds.
