### ISSUE TITLE
2.10 is missing dist folder

### ISSUE THREAD

**Issue by ashokagni001** [okta/okta-auth-js#277]
There is a recent update in Okta-auth-js (upgrade from v 2.9.0 to 2.10.0) in which there is no dist folder. 
we need to access the okta-auth-js.min.js in dist folder.

no such file or directory, open '*****\node_modules\@okta\okta-auth-js\dist\okta-auth-js.min.js'

**Comment by swiftone** [comment]
Thanks for the report @ashokagni001 - we're working on publishing an update.  If you need an immediate workaround, see this comment.  https://github.com/okta/okta-auth-js/issues/278#issuecomment-553955446

I'm closing this particular issue in favor of the earliest report: #275
