### ISSUE TITLE
2.10.0 - Missing /okta-auth-js/lib/config.js

### ISSUE THREAD

**Issue by cKiril** [okta/okta-auth-js#278]
v2.10.0 release is broken.

Please see the attached screenshot.

![okta-auth-js-bug---Annotation-2019-11-14-131835](https://user-images.githubusercontent.com/43804678/68853089-d76eea00-06e1-11ea-953e-f6c0276ecd3e.png)

**Comment by cevcode** [comment]
I have the same problem.

**Comment by cevcode** [comment]
https://github.com/okta/okta-auth-js/pull/279 It should fix the issue

**Comment by gennadiy-dubina** [comment]
any workarounds?

**Comment by cevcode** [comment]
> any workarounds?

I just bumped to 2.6.0 for now. It works. Waiting for fixes in new -v

**Comment by gennadiy-dubina** [comment]
@cevcode we have got issue with okta-react module: `"@okta/okta-react": "1.2.3"` from `package.json`
it just download fresh version of `okta-auth-js`

is it possible to exclude transient dependency in npm? (sorry i'm new in js)

**Comment by cKiril** [comment]
For now, you can fix this by explicitly specifying the last version:
`npm i @okta/okta-auth-js@2.9.0`
Then running DDP to fix the dependency graph
`npm ddp`

**Comment by swiftone** [comment]
Thanks @cKiril for the report and workaround.  We are working to publish a correction.   I'm closing this issue in favor of the earliest report: https://github.com/okta/okta-auth-js/issues/275
