### ISSUE TITLE
URL location hash being cleared when it isn't authentication params

### ISSUE THREAD

**Issue by d3k4r** [okta/okta-auth-js#285]
### Steps to reproduce:
1. Login to application (e.g. http://localhost:3000)
2. Logout of application (post logout redirects to application URL which then shows the okta login page)
    * `okta-oauth-redirect-params` set here
3. Paste deep link (e.g. http://localhost:3000/#/customer/orders/1234) into URL bar and navigate to it (redirects to okta login screen)
4. Login as normal on the okta login screen
5. Page will display the deep link's root path (http://localhost:3000/), not the full deep link path (react-router hash portion of the path is removed)

What's happening is that the application domain session cookie `okta-oauth-redirect-params` is set from a previous instance of the application navigating to the login page (token.getWithRedirect).

Since that cookie is there then `token.parseFromUrl` does not throw the `Unable to retrieve OAuth redirect params cookie` error and removeHash is called (ref. https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L695).

After removeHash is called, validateResponse inside of handleOAuthResponse fails with `OAuth flow response state doesn\'t match request state` (ref. https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L165) The response URL's state param will never match the cookie's state because http://localhost:3000/#/customer/orders/1234 does not contain authentication parameters.

### Workaround
The current workaround for this is to just check to see that the url contains a matching state value before calling `token.parseFromUrl` and if it doesn't then the cookie is removed. If the cookie isn't there then parseFromUrl throws before calling removeHash and then the application calls token.getWithRedirect to login which in turn sets the cookie with a valid state.

### Potential fix?
It seems like removeHash should only ever be called if the 'response' URL location hash  contains authentication params.? i.e. check to make sure that the location hash is actually authentication information before calling removeHash.

**Comment by swiftone** [comment]
Hi @d3k4r - thanks for the detailed report, this will really improve our ability to recreate and diagnose this bug.  Much appreciated.

**Comment by aarongranick-okta** [comment]
@d3k4r As you have seen, the cookie set by `getWithRedirect` and it is read (and cleared) by `parseFromUrl`. This cookie should only exist for the length of time between these two calls which are expected to be balanced. A call to `getWithRedirect` which is not followed by a call to `parseFromUrl` would leave a cookie unexpectedly in place.

What value are you using for the `redirectUri` used by `getWithRedirect` ? It looks like it may be passing through a common app route. Generally, we recommend having a dedicated route for the auth callback, such as `/callback`. It only exists to process tokens from Okta and then redirect back to the ORIGINAL route which began the process. We do this by:


1. Just before login, save the current route (with hash fragments) or entire URL somewhere (we recommend sessionStorage or localStorage) https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/Auth.js#L107
2. call `getWithRedirect` using your callback route as the `redirectUri`
3. Only when the app loads on the callback page, call `parseFromUrl`. This will clear the hash! https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/Auth.js#L51
4. Save the tokens in the TokenManager: 
5. Still on the callback page, read the route information that was saved before and redirect the browser back to the original page, with any original hash or query params (use window.location,replace() to avoid a history entry)

Using this method, the parameters in the hash fragment on the callback are unrelated to any parameters used by your application on the other routes.  If you'd like to have the callback URI on a route which may contain application parameters, you will have to use some other logic to determine when to call `parseFromUrl` (as you are currently doing by looking for "state").

**Comment by d3k4r** [comment]
@aarongranick-okta thanks for the guidance. 

> What value are you using for the redirectUri used by getWithRedirect ?

Yea that's correct, we are not using a dedicated callback route per application. I will look into why we haven't gone with that approach and get back to you. Seems like that would help for this scenario.

We currently call parseFromUrl on any page then if it succeeds we set the URL to whatever we have stored in session storage using the state parameter as the key.

**Comment by d3k4r** [comment]
> Generally, we recommend having a dedicated route for the auth callback, such as /callback. This route exists to process tokens from Okta and then redirect back to the ORIGINAL route which began the login process.

We aren't doing this. As for why, I'm not sure. My guess is that it was just easiest to not do that at the time. We're using IIS to serve up our UI applications and using react-router's hash routing for internal application routes. The new callback route should be easily doable once we switch to using browser router instead of hash router. (We may have been defaulting to hash router to for some legacy browser support). Can it be done using react-router's HashRouter somehow? Doesn't seem like it because our okta instance can't redirect to the hash portion of the url and then also include the hash for the authentication params.

For the time being we'll use the state check logic workaround but once we get this callback route going and switch to browser router then we'll remove it. Once we isolate the usage of  parseFromUrl to just be in the callback route this should not longer be an issue for us. The only way to hit this bug is if parseFromUrl is run when it shouldn't be run sounds like.

Close this bug?

Thanks again for the help!

**Comment by aarongranick-okta** [comment]
@d3k4r Thanks for following up. It sounds like looking for "state" in the URL as the signal to call `parseFromUrl` is a good workaround. This should work fine as long you don't use "state" for anything else.

You will still want to remember/store the full route somewhere before calling `getWithRedirect` so that the correct route can be restored after `parseFromUrl` clears the hash. Otherwise, the unauthenticated deep link scenario won't work, and the user will always end up on the homepage after logging in.
