### ISSUE TITLE
SameSite Issue in Chrome using the okta-auth-js

### ISSUE THREAD

**Issue by jphines57** [okta/okta-auth-js#296]
When using the okta-auth-js to interact with our Okta Org, we are now seeing this in the developer consoles.
A cookie associated with a cross-site resource at https://[REMOVED].okta.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by swiftone** [comment]
Thanks for the report @jphines57 - We're aware of the issue and have tested the impact of the change.  There will be no functional impact of the looming Chrome change, and we're considering the impact to all browsers (they do not all treat this the same way Chrome does/will) in seeing how we change the setting for the future.

For now Chrome will continue to emit these warnings, but they should present no problems.
