### ISSUE TITLE
How to do sso to other user from admin account?

### ISSUE THREAD

**Issue by dipakdas99** [okta/okta-auth-js#298]
I will explain to so far what I've done.

When a user tries to access to our portal, first it will check whether the user is authenticated or not? if authenticate then it will redirect to our dashboard, if not it will automatically redirect to Okta login page for authenticating themself.

The above explanation is for the user. Now I've also admin users when they will try to access our portal the same way they have to follow.

Here is what I wanted to implement is after admin logged in to our portal they will have the special authority to see the other user dashboard without knowing their credential it should be using sso by putting their email id or username. So that if any customer is having any problem in their dashboard admin can see that.

So, how can I implement that above sso thing using okta?
Any ideas. Thanks!

**Comment by swiftone** [comment]
Thanks for the question @dipakdas99.  These kinds of "proxy/impersonation" questions involve a lot of security issues and analysis of use-case, so I recommend you contact developers@okta.com to get in touch with our support staff that will be able to give you a more detailed and timely response.
