### ISSUE TITLE
"The client specified not to prompt, but the user is not logged in." in Safari

### ISSUE THREAD

**Issue by thethirdheat** [okta/okta-auth-js#301]
Hi,
I am working on an Angular project and its is giving me an error saying:
"The client specified not to prompt, but the user is not logged in." for Safari.

I have the latest version of okta-auth-js at version 2.11.0 .
I am using okta-auth-js without any other SDK wrapers. 

To produce the issue I go on private window for safari then log in. First I login with the Okta then I get stuck in a redirection loop going from okta back to my site.
 I've tried changing how the token is stored from "cookie", to "sessionStorage", to "memory", to "localStorage". The data does not seem to get passed through the redirect back to my site.

I put a debugger in client config's custom setItem function. However the value being sent back is an empty hash. When I console log the window.location, I can see in the url has `access_token=`
These are the Client_config settings to be passed to the new OktaAuth(CLIENT_CONFIG). I've
```
const CLIENT_CONFIG = {
  url: '',
  clientId: '',
  issuer: '',
  storage: 'localStorage',
  redirectUri: window.location.origin,
  tokenManager: {
    autoRenew: false,
    storage: {
      getItem: function (key) {
        window.localStorage.getItem(key);
      },
      setItem: function (key, val) {
        console.log(window.location)
        let accessTokenFromURL = window.location.href.split("access_token=")
        accessTokenFromURL = accessTokenFromURL[accessTokenFromURL.length - 1].split("&")[0]
        console.log(key, val) //val here is empty hash
        debugger
        window.localStorage.setItem(key, accessTokenFromURL);
      }
    }

  }
  ```

This redirect loop is also happening for other users but it seems to only be an issue with safari desktop and mobile. It appears to function fine on Chrome and Firefox on both Private and Non-Private sessions.

**Comment by swiftone** [comment]
```
 getItem: function (key) {
        window.localStorage.getItem(key);
      },
```
Should this have a `return` in it?

Are you getting this issue only in private Safari?  Prior to Safari 11 localstorage/sessionStorage would exist but not actually store anything in private browser mode.

**Comment by swiftone** [comment]
It sounds like your issue is only Safari related, but in case you are confused on the rest of the app you can check against our angular guide: https://developer.okta.com/code/angular/okta_angular_auth_js/

**Comment by thethirdheat** [comment]
> It sounds like your issue is only Safari related, but in case you are confused on the rest of the app you can check against our angular guide: https://developer.okta.com/code/angular/okta_angular_auth_js/

We've seen different behavior on different devices. One of our users enters the redirect loop only in a non-private window, but private browsing works fine. Another gets the exact opposite, entering the redirect loop in a private window. One user on mobile Safari also enters the redirect loop only in a non-private window. All are on latest Safari builds and have consistent repro.

**Comment by thethirdheat** [comment]
@swiftone So it seems like the redirection loop issue was due to not following the proper authorization flow. 
However we are running into a logout issue with Private Safari. 
I tested it by making a test up with exactly the process outlined here:
https://developer.okta.com/code/angular/okta_angular_auth_js/

Deploying in local testing going to private window Safari: Logging in is fine but logging out only redirects back to the page without logging out the user.
It logs out fine in Chrome, Incognito and non-Incognito. It logs out fine in Safari non-private.

It seems like the request is not being sent correctly. I've tested by sending a revoke token request for logging out does not seem to be received by the server and stills allows the user to view Auth guarded pages.

```  
async logout() {
    try {
      await this.oktaAuth.tokenManager.clear()
      await this.oktaAuth.signOut({
        postLogoutRedirectUri: window.location.origin,
        revokeAccessToken: 'true',
        accessToken: this.receivedToken
      });
      window.location.reload()
    } catch (e) {
      debugger
      console.log(e)
    }
  }
```
For the Private Safari it only goes to the catch portion and gives this error:
```
errorCode: "E0000007"

errorId: "oae68dqB6b9RCa_Bg8XnTg0kw"

errorLink: "E0000007"

errorSummary: "Not found: Resource not found: me (Session)"

message: "Not found: Resource not found: me (Session)"

name: "AuthApiError"

xhr: XMLHttpRequest

__zone_symbol__xhrURL: "https://dev-662053.oktapreview.com/api/v1/sessions/me"

readyState: 4

response: "{\"errorCode\":\"E0000007\",\"errorSummary\":\"Not found: Resource not found: m…"

responseText: "{\"errorCode\":\"E0000007\",\"errorSummary\":\"Not found: Resource not found: m…"

responseURL: "https://dev-662053.oktapreview.com/api/v1/sessions/me"

responseXML: null

status: 404
```

**Comment by swiftone** [comment]
Internal ref: OKTA-272692

**Comment by shuowu-okta** [comment]
> Deploying in local testing going to private window Safari: Logging in is fine but logging out only redirects back to the page without logging out the user.

@thethirdheat I cannot reproduce the `logout issue` in my local environment.
For my local, I have
```
Safari: Version 13.0.5 (14608.5.12)
@okta/okta-auth-js: 2.11.0

dependencies from package.json
"dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@okta/okta-auth-js": "^2.11.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  }
```

Can you please provide information of your local env, then I can look further into the issue?

**Comment by thethirdheat** [comment]
I've just tested myself. And we are now able to log out of Private Window in Safari. With no changes on our end.
