### ISSUE TITLE
okta-oauth-redirect-params Cookie not being set on same domain 2.12.0 during authorize redirect.

### ISSUE THREAD

**Issue by Itachi-Ichigo** [okta/okta-auth-js#318]
Hi @aarongranick-okta,

We recently moved to using version 2.12.0 in our application. Our application is a SPA which relies on the authorize callback (PKCE) for our user authentication. We noticed that the `okta-oauth-redirect-params` cookie is now being set to `strict` which causes issues on safari and firefox, where the redirect to our `callback` route which receives the authz. code, does not have the `okta-oauth-redirect-params` cookie set even though its technically the same domain, causing issues from within `parseFromUrl`.

`errorSummary: Unable to retrieve OAuth redirect params cookie`

**Comment by aarongranick-okta** [comment]
@Itachi-Ichigo Thanks for the report. I have confirmed this is broken on Firefox and can be fixed by setting `sameSite` to `lax`. We are working on the fix to be released asap.

**Comment by Itachi-Ichigo** [comment]
@aarongranick-okta Great, thank you!

**Comment by swiftone** [comment]
@aarongranick-okta has fixed this in record time with #319.  Now released on npm as 2.12.1.
