### ISSUE TITLE
signOut not working and revokeAccessToken is not a function

### ISSUE THREAD

**Issue by m-stern** [okta/okta-auth-js#348]
I am trying to figure out how to revoke an access token while signing out. 
The docs say that `signOut()` should revoke an access token if you supply it with an `idToken` and/ or an `accessToken` (it isn't clear if you need one or both). It says that it will look in the specified tokenManager for items matching those names. 
I tried supplying both of these as objects, as strings of just the token, and I tried not supplying them at all and letting the tokenManager get them. They are definitely in the tokenManager because I can get them and I can see them in local storage.
However none of these attempts seems to clear the tokenManager or revoke the access token, I can still make requests with it. 

I also tried using `authClient.revokeAccessToken()` directly and got a `TypeError: revokeAccessToken is not a function`. 

Is there another way I should revoke the access token or am I trying to use either of these incorrectly? I am struggling to figure out what is going on here. 

Version info:
`"@okta/okta-auth-js": "~2.9.0"`

**Comment by swiftone** [comment]
Hi @m-stern - The docs on this site reflect the latest version, while you are a few versions behind, so there can be some differences.

We recommend using the latest version (either 2.13.2 for the 2.x series, or the newest 3.x version).  Revoking the accessToken was explicitly one of the changes made.

**Comment by m-stern** [comment]
@swiftone Upgrading to 3 fixes the issue with `revokeAccessToken` thanks so much! I didn't realize how far my version was out of date, sorry for the noise!
