### ISSUE TITLE
Forgot password by passcode

### ISSUE THREAD

**Issue by rodrigowpl** [okta/okta-auth-js#349]
I'm trying `forgotPassword` function, it's working ok, but the email that is coming is Okta Password Reset Requested to reset by Okta reset password page instead of sending passcode, what isn't make sense according to this documentation:
https://github.com/okta/okta-auth-js#forgotpasswordoptions

example: From where can I get this `passcode` by EMAIL?
![image](https://user-images.githubusercontent.com/18172307/76905589-03150300-6881-11ea-8d23-1a407d4237fd.png)

Thanks

**Comment by swiftone** [comment]
Hi @rodrigowpl!  A few questions so we can better address your question:

- Are you passing `factorType: 'EMAIL'` in your call?
- Are your users set up to use MFA in your Okta admin dashboard?

Email shouldn't send a passcode, email will give you a link with embedded tokens.   If you're requesting SMS but getting an email, the odds are that your accounts aren't set up for SMS recovery on the admin side.

Let us know and we can help, or you can reach out to our support team at developers@okta.com with specifics of your case.

**Comment by swiftone** [comment]
Closing this issue as stale - feel free to reopen with details.
