### ISSUE TITLE
IE 11 won't redirect to Okta login

### ISSUE THREAD

**Issue by ddelapasse2** [okta/okta-auth-js#358]
We are trying to run the Angular app with Okta-Auth-JS(V2.13.2) in IE 11 but the app is not redirecting to okta authentication.   As per https://github.com/okta/okta-auth-js#browser-compatibility we have included required packages in polyfills as follows:

import 'core-js/es7/array';
import { TextEncoder } from 'text-encoding-polyfill';
if (typeof (window as any).TextEncoder === 'undefined') {
    (window as any).TextEncoder = TextEncoder;
}

Package.json:
"subtle-crypto": "0.0.0",
"text-encoding-polyfill": "^0.6.7",
"webcrypto-shim": "^0.1.5",

Please let us know if any other package is missing.

**Comment by swiftone** [comment]
@ddelapasse2 - thanks for the report.

Are you polyfilling `Promise`?

Our samples have been tested in IE11 ( https://github.com/okta/samples-js-angular ) - do they work for you?

**Comment by ddelapasse2** [comment]
@swiftone   those samples do not work for us either.  We get an empty screen with no errors in the dev tools.  It never redirects to the company okta login page.

Which specific package should be used for polyfilling Promise?  Maybe we chose the wrong one.

**Comment by swiftone** [comment]
Internal note: revisit after OKTA-291504

**Comment by swiftone** [comment]
@ddelapasse2 - While we investigate, you might check https://github.com/okta/okta-auth-js/issues/359, as it has some recommendations about polyfills from another user.  

Any well-written polyfill should work - we've used es6-promise, but anything with a good download/star rating on npm should work fine.

**Comment by swiftone** [comment]
Internal ref: OKTA-291509

**Comment by Visha01** [comment]
Any words on this?

**Comment by aarongranick-okta** [comment]
@ddelapasse2 We now provide a polyfill for compatibility with IE 11+. It is available either through our NPM module or via CDN to be included as a script tag. See here for more information: https://github.com/okta/okta-auth-js#browser-compatibility--polyfill

**Comment by shuowu** [comment]
Issue has been fixed since v3.2.0
