### ISSUE TITLE
README.md shows incorrect stable version

### ISSUE THREAD

**Issue by patrickdemers6** [okta/okta-auth-js#361]
The latest stable version is 3.0.1 but the readme file shows the latest version to be 2.x.

**Comment by swiftone** [comment]
Thanks @patrickdemers6, good catch - We'll update that in our next PR.

**Comment by swiftone** [comment]
PR to correct: https://github.com/okta/okta-auth-js/pull/362

**Comment by swiftone** [comment]
Merged, thanks @patrickdemers6
