### ISSUE TITLE
AuthSdkError: The current page is not being served with the HTTPS protocol.

### ISSUE THREAD

**Issue by ey52fpv** [okta/okta-auth-js#368]
errorCauses: []
errorCode: "INTERNAL"
errorId: "INTERNAL"
errorLink: "INTERNAL"
errorSummary: "The current page is not being served with the HTTPS protocol.↵For security reasons, we strongly recommend using HTTPS.↵If you cannot use HTTPS, set "cookies.secure" option to false."
message: "The current page is not being served with the HTTPS protocol.↵For security reasons, we strongly recommend using HTTPS.↵If you cannot use HTTPS, set "cookies.secure" option to false."
name: "AuthSdkError"

Getting this error while rending the OKTA sign-in widget in localhost with an IP

**Comment by lukekhamilton** [comment]
I'm having this issue too.
I have a nginx server serving my frontend and have set the following and its still not working too:

```
add_header Set-Cookie "secure=false";
```

**Comment by lukekhamilton** [comment]
I believe this merge has broken the option to turn off the usage of https: https://github.com/okta/okta-auth-js/pull/313

**Comment by lukekhamilton** [comment]
And is the cookie being set: 
https://i.imgur.com/HImIMHT.png

Here is my issue: 
https://i.imgur.com/Si8Ywxo.png

**Comment by swiftone** [comment]
@lukekhamilton - the `cookies.secure` refers to the property you pass to okta-auth-js, see https://github.com/okta/okta-auth-js#additional-options and scroll down to 'cookies'.  It is not a cookie value you set.

You will also need to set `pkce: false`, as pkce requires HTTPS for webcrypto.

**Comment by swiftone** [comment]
@ey52fpv - "localhost with an IP" means a domain that is not "http://localhost"?  special exceptions are made for the localhost domain explicitly, both by Okta and by most browsers, and those exceptions are NOT allowed for IP addresses-as-domains nor other domains (and because the browsers set some of these rules, we couldn't change them even if we wanted to).

You will have to use http://localhost or use https even in development

**Comment by aarontanzk** [comment]
@swiftone Hi i'm having this AuthSdkError issue over HTTP as well. Understand that under config we should set cookies to false. However i have tried many times still unable to get it to work.
 
Could you please help provide a sample config for us to try out?

Thanks !

**Comment by aarontanzk** [comment]
Hi resolved,
For those who are facing serving over HTTP issues: 
{
     clientId: xxxxxxx,
    issuer: xxxxxx,
    redirectUri: xxxxx,
    scopes: [xxx, xxx ,xxx],
    pkce: false,
    cookies: {
         secure: false
   }
   ...
}

**Comment by lukekhamilton** [comment]
Thanks @aarontanzk that worked for me!

**Comment by aarongranick-okta** [comment]
We have released an update (`3.1.1`) which automatically sets the secure cookie setting based on the protocol. If you are running on HTTP, you should no longer see an error related to secure cookies.

If using PKCE OAuth flow (which is the default), there is a requirement related to `crypto.subtle` which requires HTTPS. There is a narrow exception (provided by the browsers) for "localhost", but this exception does not apply to IP addresses.  If you intend to serve your application on HTTP, you should not use the PKCE flow. This can be done by setting `pkce: false` in your config.

https://github.com/okta/okta-auth-js#pkce-oauth-20-flow
