### ISSUE TITLE
Revoke AccessToken from SinglePage App

### ISSUE THREAD

**Issue by patluri43** [okta/okta-auth-js#375]
**Current Behavior:**
RevokeAccessToken method is passing Authorization header with client_id

**Expected Behavior**
When rovoking accessToken from SinglePage App, there is no client secret  and require the "client_id" to be passed in the request body.

**API Reference:**

**None** 
Specify none when the client is a public client and doesn't have a client secret. Only the client_id is sent in the request body.

https://developer.okta.com/docs/reference/api/oidc/#client-authentication-methods

**Comment by swiftone** [comment]
Internal ref: OKTA-300064

**Comment by aarongranick-okta** [comment]
For those running into this issue, be aware that `revokeAccessToken` is an async method. Be sure that you are waiting for the promise to resolve by using the `await` keyword or by adding a `.then()` block.
