### ISSUE TITLE
Using okta-auth-js to log in and issue MFA factor

### ISSUE THREAD

**Issue by thuannh1027** [okta/okta-auth-js#376]
I can't find the way to issue MFA factor. After login using /authn, I got a response with status "MFA_REQUIRED" and don't know how to proceed. Could anyone help me with this?

Note: after research, it appears that using the [Factors API](https://developer.okta.com/docs/reference/api/factors/) would work. However, I stuck to find how to retrieve the API token by code.

**Comment by swiftone** [comment]
@thuannh1027 - Can you clarify if you are using the okta-auth-js SDK or talking to the API endpoints directly?

If you are using the SDK, you can respond to MFA_REQUIRED as shown in the readme: https://github.com/okta/okta-auth-js#mfa_required

Hope that helps!

**Comment by thuannh1027** [comment]
thank you thank you so much. And sorry for late response.
