### ISSUE TITLE
AuthSdkError happens every time after login

### ISSUE THREAD

**Issue by yugra** [okta/okta-auth-js#381]
Hi there,

We're using okata-react for login, our developer has updated to @okta/okta-react 3.0.1. After update, the error **‘AuthSdkError: The redirectUri passed to /authorize must also be passed to /token’** happens every time after I login to my application in Chrome, and only if I delete the "implicit/callback" in URL and refresh the page (or to say reopen my app), then I can login to my app properly and go to the homepage. Could you please assist to solve this issue? We've been stuck on this problem and communicated with your support team for a couple of days but there is no solution until now...

The following is my app component:
![image](https://user-images.githubusercontent.com/65998364/82999748-117b5a00-a03c-11ea-8c05-a5fae5e219d0.png)

And okta config:
![image](https://user-images.githubusercontent.com/65998364/82999838-2ce66500-a03c-11ea-909c-cdb38d620db1.png)

Our developer found that every time this issue occurs, accessToken is missing in okta-token-storage local storage. Normally, both idToken and accessToken should appear, then user can login successflully. But now, accessToken isn't generated intermittently, suppose that's why we cannot login normally. Not sure if it's the point, we're waiting for your assistance, thank you!

**Comment by swiftone** [comment]
@yugra - Thanks for the report.  Your usage looks correct, and I would recommend continuing to work with the support team, but let's see if we can generate any ideas.

- If you run your app with `pkce:false`, does the problem still occur?  (this requires the Okta app be configured in the admin ui to allow that)
- If you debug and point a breakpoint on this line: https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L202, 
  - do you see the call happen more than once?  
  - Is the `redirectUri` param missing in one of those occurrences?

**Comment by Dewar0019** [comment]
I am also experiencing the same issue and have traced the error down to this line.

https://github.com/okta/okta-auth-js/blob/okta-auth-js-3.1.2/packages/okta-auth-js/lib/browser/browserStorage.js#L43

Digging further down we see that browserHasSessionStorage is being tested by adding and removing an item but it doesn't test to see if there are any contents within the storage.

https://github.com/okta/okta-auth-js/blob/9a5117df755a33bb6937b56c9c55e73907e07331/packages/okta-auth-js/lib/browser/browserStorage.js#L102

<img width="592" alt="Screen Shot 2020-06-05 at 6 31 12 PM" src="https://user-images.githubusercontent.com/8000202/83933124-c60f2d00-a75a-11ea-8409-e10b83def2a1.png">

<img width="811" alt="Screen Shot 2020-06-05 at 6 35 19 PM" src="https://user-images.githubusercontent.com/8000202/83933198-58afcc00-a75b-11ea-9a78-f6df618b4619.png">



I do see in my local storage that these keys are set though
<img width="803" alt="Screen Shot 2020-06-05 at 6 35 47 PM" src="https://user-images.githubusercontent.com/8000202/83933202-6a916f00-a75b-11ea-94a8-2c41f470966e.png">

Perhaps the contents of SessionStorage should be tested first or maybe LocalStorage takes priority over SessionStorage?

**Comment by jason-s-wang** [comment]
Similar issue in my app.

Debug as required:
Set pkce to false(app and okta admin).
Error didn't happen.(Didn't try a lot times, can not be sure)
1.do you see the call happen more than once?
Called only once.(With or without error)
2.Is the redirectUri param missing in one of those occurrences?
Not missing.(With or without error)
![image](https://user-images.githubusercontent.com/46334208/84006100-c4cf4180-a9a0-11ea-88a3-ae9d69c8059d.png)

@swiftone , please let me know if any more info is needed.

**Comment by aarongranick-okta** [comment]
@Dewar0019 We have released a new version of `okta-auth-js` (3.1.3) which should fix the issue involving local/session storage. Please update to this latest version and let us know if this resolves your issue.

@yugra @jason-s-wang I am not sure if the issue you are seeing is the same as that reported by @Dewar0019 but please try updating to the latest version of `okta-auth-js` and see if it has resolved your issue.

**Comment by Dewar0019** [comment]
Thanks! @aarongranick-okta It has fixed my issue.

**Comment by yugra** [comment]
Same issue, @jason-s-wang and me are in one team, thanks for debugging the problem Jason.
@aarongranick-okta the new version solves our issue, thank you!
