### ISSUE TITLE
Typo in the README documentation (onSessionExpired)

### ISSUE THREAD

**Issue by gtupak** [okta/okta-auth-js#383]
I am looking to change the default behaviour when the session expires and found [in the README](https://github.com/okta/okta-auth-js#example-client) an example on how to use it. 

The function assigned to `onSessionExpired` however uses `authClient` which has not been declared yet (it is declared below). Is that a typo, or we get `authClient` as a parameter in the callback function?

Thank you in advance!

**Comment by shuowu** [comment]
@gtupak As it's a customized callback function, `onSessionExpired` will only be called after authClient initialized. Also, from js syntax perspective, hoisting will put declarations into memory first. https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

**Comment by gtupak** [comment]
Oh wow, I learned something today! Thank you for your answer!
