### ISSUE TITLE
unable to load okta-auth-js in angular

### ISSUE THREAD

**Issue by egshyam10** [okta/okta-auth-js#389]
is there any way or method to make okta-auth-js working in angular, as it is looking for type definitions of the library.

**Comment by aarongranick-okta** [comment]
@egshyam10 This is an often requested feature and we are currently working on adding type definitions. In the meantime, you can add "ambient" type declarations within your project to make it work.

**Comment by Taras-R** [comment]
@egshyam10 Maybe this will help https://developer.okta.com/code/angular/okta_angular_auth_js/

**Comment by shuowu** [comment]
okta-auth-js starts supporting types since version 4.
