### ISSUE TITLE
I am getting invalid_client error while calling token api using parseFromUrl() method of okta-auth

### ISSUE THREAD

**Issue by anandadvisory** [okta/okta-auth-js#401]
{"error":"invalid_client","error_description":"Client authentication failed. Either the client or the client credentials are invalid."}

**Comment by anandadvisory** [comment]
Any update on this?
Anyone have faced this issue with React JS?

**Comment by swiftone** [comment]
@anandadvisory - This is most likely the result of the parseFromUrl() being called twice, as the first call will remove the client info from the url/storage.

Without more details on how you are invoking this I'm afraid we can't give you more information.  If you supply the information requested in the GH Issue template (such as library versions and a minimal reproduction example) we can see if there is more help we can offer.

Be sure to check out our samples ( https://github.com/okta/samples-js-react/ ) and guides ( https://developer.okta.com/docs/guides/ )

**Comment by BenMGilman** [comment]
I just got this same error. @anandadvisory did you end up fixing this issue?

**Comment by shuowu** [comment]
@anandadvisory @BenMGilman What's the type of your application? It looks like you are using a `web` application instead of a `SPA` application.

**Comment by anandadvisory** [comment]
@shuowu you are absolutely correct.
I was trying to get token with web application client keys.
I have created new SPA application and checked the same flow & Bingo! It's working fine now.

@BenMGilman Please verify the type of your application in the okta console.

**Comment by BenMGilman** [comment]
Yes that exactly my issue as well, thank you

**Comment by YamilDiaz** [comment]
Is it possible to use an Okta Web Application and use it with React.JS?
