### ISSUE TITLE
token.getWithRedirect does not immediately redirect

### ISSUE THREAD

**Issue by jasonrberk** [okta/okta-auth-js#403]
after a call to `authClient.token.getWithRedirect`, which doesn't document any return value, doesn't appear to cause a redirect immediately.  I'm seeing the rest of my code run...and fail in the console before the browser redirect (Chrome).  Is there some trick to getting the redirect to happen immediately?

**Comment by swiftone** [comment]
@jasonrberk - The method is returns a promise (you are correct, this appears to be undocumented - we'll fix that!  https://github.com/okta/okta-auth-js/blob/master/packages/okta-auth-js/lib/token.js#L666).  If you `await` the `authClient.token.getWithRedirect()` call, that should be the trick you are looking for.  

If you are unfamiliar with async/await, you can read more about it here: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

**Comment by shuowu** [comment]
Readme is updated with `async` flag now.
