### ISSUE TITLE
Password security issue - When okta user will signin using okta sdk, password are showing as open. How can we hide password from payload?

### ISSUE THREAD

**Issue by anandadvisory** [okta/okta-auth-js#404]
I am using below okta method to sign in
```
authClient.signIn({
  username: 'some-username',
  password: 'some-password'
})
.then(function(transaction) {
  if (transaction.status === 'SUCCESS') {
    authClient.session.setCookieAndRedirect(transaction.sessionToken); // Sets a cookie on redirect
  } else {
    throw 'We cannot handle the ' + transaction.status + ' status';
  }
})
.catch(function(err) {
  console.error(err);
});
```

When I see payload by inspecting network call, It's showing user's username and password as shown below:
{"username":"email_id@gmail.com","password":"user_password"}

How can I encrypt user credentials?

**Comment by swiftone** [comment]
Encrypting the password in transit is the job of HTTPS - I'm not aware of any authentication methods sending a password that encrypts a sent password/passcode in any other way.

**Comment by aarongranick-okta** [comment]
As @swiftone mentioned, the payload is encrypted by the HTTPS connection. All Okta API endpoints are secured by HTTPS. Credentials are visible to you on the client, before they have been sent to Okta's servers. The HTTPS channel between the client and server is encrypted so the credentials will not be visible to a "man in the middle".

Okta also supports "passwordless" authentication using various authentication factors which can replace a standard password:
https://developer.okta.com/product/authentication/
https://help.okta.com/en/prod/Content/Topics/Security/mfa-factor-sequencing.htm
