### ISSUE TITLE
Incorrect storage key for access token in signOut method

### ISSUE THREAD

**Issue by E-Kuerschner** [okta/okta-auth-js#422]
Library version: 3.1.4

Offending line: https://github.com/okta/okta-auth-js/blob/75d5a72f7d126e7aeb82119acb202c4604ac0f3d/packages/okta-auth-js/lib/browser/browser.js#L296

In literally every other piece of documentation online the access token is shown being stored under the key "accessToken". What this means is if a dev is following the official Okta guides (as one would assume they would do) then the revokeAccessToken feature will work incorrectly.

**Comment by swiftone** [comment]
@E-Kuerschner - Good catch, the definitely looks wrong.  We'll fix and add tests.

Internal Ref:  OKTA-315806

**Comment by shuowu** [comment]
Link the fix PR here: https://github.com/okta/okta-auth-js/pull/436
Pending for release.
