### ISSUE TITLE
When using revokeAcccessToken() the token is not revoked

### ISSUE THREAD

**Issue by staffordp** [okta/okta-auth-js#427]
I have posted on another thread with this issue but instead of continuing to hijack that topic, I am opening a new one with this.

Simply put, here is our code:

```
  async signOut() {
      await this.authClient.revokeAccessToken(); // strongly recommended
      this.authClient.closeSession()
      .then(() => {
        console.log('Session closed.');
      })
      .catch(e => {
        if (e.xhr && e.xhr.status === 429) {
          console.error('Too many requests.');
          // Too many requests
        }
      })
  }
```
I watch the whole signin process and copy the accessToken.value to a text file.  I then watch as this flow happens (I dump the accessToken to console to ensure it's the same one).  After this call completes, I see the in the network tab that it makes two successful calls:

revoke: https://cartus.oktapreview.com/oauth2/xxxxxxxxxxxxx/v1/revoke (POST)
 - with this call it looks like it's sending two form items:

1. token_type_hint: access_token
2. token: (correct accessToken value)

delete: https://cartus.oktapreview.com/api/v1/sessions/me (DELETE)

Yet when I use this same accessToken after in an API call to our App, it works just fine.  I am not sure what to do as I believe I am following the official documentation and have been struggling with this over a week now.

Any help appreciated.

**Comment by staffordp** [comment]
I noticed there was an update to the library to 3.20. I updated:
    "@okta/okta-auth-js": "^3.2.0",

However, it still doesn't resolve the issue.

**Comment by staffordp** [comment]
So is there no fix for this? Is there no way to currently sucessfully revoke a token with this library?

**Comment by swiftone** [comment]
> Yet when I use this same accessToken after in an API call to our App,

Can you expand on this a bit?  The accessToken itself is still an accessToken (A JSON file that is signed) Only if something checks the revocation list will it notice that the token should not longer be trusted, but if something looks only at the token itself the token appears fine.  

Can you tell us what API call is saying the accessToken is fine?  Is this a call to your backend or to Okta?

**Comment by staffordp** [comment]
@swiftone We are currently using this library on our API to verify the token: https://www.npmjs.com/package/@okta/jwt-verifier

The code in the API that checks looks like this:

import { NextFunction, Response } from 'express';
const OktaVerifier = require('@okta/jwt-verifier');
import config from '../config';

```
export class TokenValidator {
    static async validateToken(req: any, res: Response, next: NextFunction) {
        const token: string = req.header('AuthorizationToken');
        if (!token) {
            return res.status(403).json({
                code: 'INVALID_TOKEN_ERROR',
                message: 'Invalid token'
            });
        } else {
            const oktaJwtVerifier = new OktaVerifier({
                issuer: config.OKTAISSUERURL
            });

            try {
                const jwtResult = await oktaJwtVerifier.verifyAccessToken(token, config.OKTATOKENAUD);
            } catch (oktaErr) {
                console.log('okta error in token validator', oktaErr);
                return res.status(401).json({
                    code: 'UNAUTHORIZED_ERROR',
                    message: 'Unauthorized Access'
                });
            }
        }
        next();
    }
}
```

**Comment by staffordp** [comment]
I spoke with Okta support this morning and was able to confirm the token is being revoked.  The problem rests with the library we are using to verify the token; it is not checking for revocation.  Introspect would do that. As such, I am closing this.
