### ISSUE TITLE
When using okta-react, the user is redirected to login on unsecured Routes when their session expires.

### ISSUE THREAD

**Issue by andredigenova** [okta/okta-auth-js#429]
Behaviour:
If a user's session is expired and they navigate to a non-secure route, the user gets redirected to the Okta login page. 

Expected behavior:
Since the route isn't a SecureRoute, the user should just be able to view the page without logging in.

I suspect something in withOktaAuth is causing the redirect on expired session. I use it on non-secure routes because I need access to the authState/authService objects within the React component to determine what to show to the user.

**Comment by swiftone** [comment]
@andredigenova - By current default, when a session expires we will attempt to login the user again (this has nothing to do with the secure, non-secure route, but you likely aren't seeing the impact until a re-render is performed).

Are you providing an override for the onSessionExpired() callback?   (https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#configuration-options ).  If not, try passing in a callback that overrides the default behavior (https://github.com/okta/okta-oidc-js/blob/master/packages/okta-react/src/AuthService.js#L38 ).

The intent is that what you are doing should work just fine - The authState should be fully visible to non-secure routes regardless of whether the user is logged in, both before a login and after an expiration.

**Comment by andredigenova** [comment]
Ah thanks. I wasn't aware it was just a simple call to login on expiration. I'll implement a custom callback to detect if I'm on a SecureRoute or not.
