### ISSUE TITLE
revokeAccessToken Basic Auth popup on Chrome

### ISSUE THREAD

**Issue by hicaro** [okta/okta-auth-js#439]
Hi there, guys 👋 . I am having an issue when calling `revokeAccessToken` in Chrome in an edge situation. 

If `/v1/revoke` is called with a token that has already been revoked in another window, the endpoint will return the 401 HTTP status, which is expected since the token no longer valid. However, as the request is using the `Basic` authorization header value, Chrome will display a "Sign In" popup. This has been a bit cumbersome since I call `revokeAccessToken` amidst the logout process and showing a sign in popup in there will confuse the user. 

⚠️ **This does not happen with other browsers. Only Chrome.**

I am currently using @okta/okta-auth-js version 3.2.0 and I was wondering whether there is some work around for this? I would appreciate any way to mitigate this issue.

<img width="439" alt="Screen Shot 2020-07-30 at 2 28 53 PM" src="https://user-images.githubusercontent.com/1482851/88976497-ffeb4400-d270-11ea-9aa2-a4d9d2c1cef8.png">

**Comment by swiftone** [comment]
@hicaro - Thanks for the report!  This should not be happening, per the docs at https://developer.okta.com/docs/guides/revoke-tokens/overview/ - attempting to revoke a token that is already revoked should return a 200.

Can you check the Network tab of the Chrome DevTools and share any details (minus the tokens and any authorization info) about the request?  If you'd prefer to do so outside of this public forum, you can reach out to our support team at developers@okta.com

**Comment by hicaro** [comment]
@swiftone I apologize for not including more details in the first time. Thank you for looking into it.

These are the request headers (I verified that the `Authorization: Basic ...` is the correct base64 representation generated by the package):

<img width="546" alt="Screen Shot 2020-07-30 at 3 15 10 PM" src="https://user-images.githubusercontent.com/1482851/88980114-d681e680-d277-11ea-93d1-e05bde46d5f1.png">

This is the request body:

`token_type_hint=access_token&token={my access token}`

These are the response headers:

<img width="541" alt="Screen Shot 2020-07-30 at 3 12 44 PM" src="https://user-images.githubusercontent.com/1482851/88980145-e7325c80-d277-11ea-8bd9-e061e2307fdd.png">


This is what I get as the response body:

```json
{
  "error": "invalid_client",
  "error_description": "Client authentication failed. Either the client or the client credentials are invalid."
}
```

**Comment by hicaro** [comment]
I also followed the package's code until [here](https://github.com/okta/okta-auth-js/blob/208e3390bbbb61db3533f2ab5e421b94a2c7d614/packages/okta-auth-js/lib/token.js#L26)

**Comment by swiftone** [comment]
I haven't had a chance to test this theory, but based on the API docs I'm guessing this is not caused by the token already being revoked, but instead your session with the issuer domain being invalidated.  

What is the sequence of steps involved?  Is the user being logged out of the issuer session before the second revoke call?

**Comment by hicaro** [comment]
@swiftone this is the order of the calls:

```js
// revoke token
await this._oktaAuth.revokeAccessToken(accessToken);

// close session
await this._oktaAuth.closeSession();
```

But you are correct, since the other tab has successfully called both functions, the other tab would fail on the `revokeAccessToken` once the session was previously closed.

However, I thought that `revokeAccessToken` did not depend on the session itself. Is this a bug or it is a case that I should check for the session validity before trying to revoke the token?

Do you think this would also happen within `signOut` once it internally calls `revokeAccessToken` before redirecting?

**Comment by hicaro** [comment]
@swiftone have you had the chance to check on this issue?

**Comment by swiftone** [comment]
I'm running some experiments today and tomorrow, time permitting - I hope to have an answer soon.

**Comment by swiftone** [comment]
@hicaro - I've been unable to reproduce this case.  I can call `.revokeAccessToken(accessToken);` and follow with `.closeSession()`, and then can call `.revokeAccessToken(accessToken);` again without issue (getting a 200 response).  I've tried with and without calling tokenManager.get() in between (which will return undefined) and get a 200 response in both cases.

Something is definitely up though - If you can reach out to our support team at developers@okta.com you can share details of your configuration and they can help us find out what is happening.

**Comment by CharlieDieter** [comment]
I have this issue calling signOut, and have been able to reproduce by calling revokeAccessToken as well. Any updates here?

**Comment by hicaro** [comment]
@CharlieDieter thanks for always validating the issue I am encountering. Looking at their [code](https://github.com/okta/okta-auth-js/blob/92ed9c126cd1e89d988d16d19b8aab0ec64ad0da/lib/browser/browser.ts#L264), `signOut` internally calls `revokeAccessToken`. I kept following the call chain and his will ultimately result in the call of [revokeToken](https://github.com/okta/okta-auth-js/blob/92ed9c126cd1e89d988d16d19b8aab0ec64ad0da/lib/token.ts#L69) from the token handler.

My guess is that `withCredentials: false` is missing in the options of the [post](https://github.com/okta/okta-auth-js/blob/92ed9c126cd1e89d988d16d19b8aab0ec64ad0da/lib/token.ts#L87) function call, which would prevent a session cookie from being attached to the request.

**Comment by peter-chan-hkmci** [comment]
Is there any updates?

**Comment by shuowu** [comment]
@peter-chan-hkmci No update for now. I have created an internal ticket and our team will investigate on it.

Internal Ref: OKTA-403546
