### ISSUE TITLE
Missing Properties in Initialized Auth Object [4.x]

### ISSUE THREAD

**Issue by ConderS** [okta/okta-auth-js#454]
Currently when I try to initialize an OktaAuth instance with the AuthJS API, I get an instance that’s missing a lot of core properties like `token`. These properties are initialized fine when using the previous release (v3.2.3), but disappear when using 4.0.0.

I believe I’m initializing this correctly with the following configuration:
```
const oktaConfig = {
  issuer: `${process.env.OKTA_ORG_URL}/oauth2/default`,
  redirect_uri: `https://localhost:3001/login`,
  client_id: process.env.OKTA_CLIENT_ID,
  scopes: ['openid', 'profile', 'email'],
 pkce: false
}
const authClient = new OktaAuth(oktaConfig);
```
Afterwards, trying to do something like `authClient.getUserInfo` or `authClient.token.parseFromUrl()..` results in either `getUserInfo` or `token` not existing.

I believe this could be a bug, but would be curious to hear if others have ran into this issue.

**Comment by swiftone** [comment]
@ConderS - What is the config you are using now?  How you're consuming okta-auth-js will impact how to make sure it uses the correct version.

**Comment by ConderS** [comment]
@swiftone Gotcha. I included the config I used to initialize the `OktaAuth` instance above in my initial post, is that what you meant? I don't think I'm using any other configs besides that.

**Comment by shuowu** [comment]
@ConderS It mostly depends on how your bundler is configured. Also, the env will pick the server bundle by default if you are in node/test env. I saw it mostly happened if the app is doing SSR (server-side-rendering).
Here is how Webpack configure different bundles from a package( https://webpack.js.org/concepts/targets/ ), it can be similar idea if you are using other bundlers for your app.

**Comment by shuowu** [comment]
Close this issue as okta-auth-js exposes isomorphic APIs since version 5.x.
