### ISSUE TITLE
Active Auto Renewal before token expiration

### ISSUE THREAD

**Issue by federicopezzola** [okta/okta-auth-js#463]
Hi!
I was willing to update to version 4.0. And use the active autoRenewal of the token, but although the current token has not expired, the autorenewal tries to get the token with the session cookie instead of using the current token to renew it. 
And this could be an issue for browsers that blocks 3rd party cookies...
Am i correct? I know i could workaround this handling the renewal myself... but this is a nice to have feature
Thanks!

**Comment by shuowu** [comment]
@federicopezzola Your understanding is correct. In the current implementation, the renewal process is actually to get a new token through a hidden iframe (session cookie) when the token is about to expire. And Yes, it has issues with browsers like safari. 
We are working on a solution now to renew tokens with the refresh token, it's on our roadmap.

**Comment by federicopezzola** [comment]
Right... I don't know why i thought you were refreshing the tokens without using the tokens, but i just realized i was wrong... Thank you very much for the answer @shuowu!
