### ISSUE TITLE
Unable to retrieve OAuth redirect params cookie

### ISSUE THREAD

**Issue by sethen** [okta/okta-auth-js#475]
Getting this error when trying to use the `OktaAuth` SDK in React.  Here is very basic sample of the code:

```typescript
import * as React from 'react';
import { Button } from 'antd';
import { OktaAuth } from '@okta/okta-auth-js';

interface OktaReactProps {
	issuer: string;
	oidcClientID: string;
}

class Okta extends React.Component<OktaReactProps> {
	private authClient: any;

	componentDidMount(): void {
		const { issuer, oidcClientID } = this.props;
		const { origin } = window.location;

		this.authClient = new OktaAuth({
			clientId: oidcClientID,
			issuer,
			redirectUri: `${origin}`
		});

		if (this.authClient.token.isLoginRedirect()) {
			this.authClient.token.parseFromUrl().then((data: any) => {
				// Errors here
			});
		}
	}

	handleOnLoginClick = (): void => {
		this.authClient.token.getWithRedirect({ responseType: 'id_token' });
	};

	render(): React.ReactNode {
		return (
			<div id='okta'>
				<Button onClick={ this.handleOnLoginClick } type='primary'>
					okta
				</Button>
			</div>
		);
	}
}

export default Okta;
```

The redirect to the sign in page and the redirect uri are working fine.  It redirects properly and then throws this error after about 5 seconds:

```
Unhandled Rejection (AuthSdkError): Unable to retrieve OAuth redirect params cookie
```

Is this because I am using the developer account that I configured my app with?

I am using `@okta/okta-auth-js": "^4.0.0"`

I searched around for an answer to no avail.  Am I doing something wrong or is this a bug?

**Comment by sethen** [comment]
On an additional note, I tried to use the React package but ran into an issue:

1.  Using the `withOktaAuth` doesn't actually do anything for my component.  When I try to use `this.props.authService.login` I get an `undefined` error, hence why I started using this JS SDK.  I plan on making another issue as well.

**Comment by swiftone** [comment]
Hi @sethen - As with the other issue, I suspect the problem is okta-auth-js 4.x with okta-react 3.x.  Can you see if using the latest 3.x okta-auth-js (which should be installed with okta-react) fixes your issue?

**Comment by sethen** [comment]
Hello there,

Changed my dependencies to the following:

```
    "@okta/okta-auth-js": "^3.2.3",
    "@okta/okta-react": "^3.0.7",
```

Logging in worked and so did the redirect -- still same error unfortunately.

**Comment by shuowu** [comment]
@sethen Looks like you were running into login race condition issues. Right now oauthStateParams are store in shared storage (the cookies) for the client-side after login validation, but if more than one flows running concurrently, it would cause the first succeed flow to delete the state cookie then cause the following flows to throw errors.
This issue normally causes by running multiple AuthJs instance in one single tab, or login to OKTA from multiple tabs.

From the code above, you may check if multiple `<Okta>` component has been created or if `this.authClient.token.parseFromUrl`has been triggered more than one time after redirecting back.

**Comment by aarongranick-okta** [comment]
@sethen Were you able to find a resolution to this issue? Since the time of this issue we have released several updates to auth-js and the signin widget and we believe this issue has been corrected.

**Comment by sethen** [comment]
I went with another solution and am not using the okta SDK directly any longer.  Thanks for looking into this though.
