### ISSUE TITLE
Property 'verify' does not exist on type 'AuthTransaction'

### ISSUE THREAD

**Issue by DeepBhat** [okta/okta-auth-js#490]
`authClient.forgotPassword({
  username: 'dade.murphy@example.com',
  factorType: 'SMS',
})
.then(function(transaction) {
  return transaction.verify({
    passCode: '123456' // The passCode from the SMS or CALL
  });
})
.then(function(transaction) {
  if (transaction.status === 'SUCCESS') {
    authClient.session.setCookieAndRedirect(transaction.sessionToken);
  } else {
    throw 'We cannot handle the ' + transaction.status + ' status';
  }
})
.catch(function(err) {
  console.error(err);
});`

I was trying to replicate the code in the documents and I realized that forgotPassword() returns an AuthTransaction object which does not have "verify" as its function.

**Comment by aarongranick-okta** [comment]
@DeepBhat Thanks for the submission. Unfortunately the `AuthTransaction` object is not well documented. We are trying to improve this. The methods on the object will vary depending on the current state of the transaction. Where in the documents is it indicated that the object has a `verify` method?

**Comment by DeepBhat** [comment]
![image](https://user-images.githubusercontent.com/33815709/94499893-7817ac80-01c3-11eb-9e57-ad9cba111543.png)
This code in the [forgot password](https://github.com/okta/okta-auth-js#forgotpasswordoptions) section uses `.verify()` method on `transaction`, which is of type `AuthTransaction`. 

Is there a workaround for me to use meanwhile?

**Comment by aarongranick-okta** [comment]
@DeepBhat I believe this example assumes you have SMS enabled as an authentication factor. Have you enabled SMS under MFA settings in the Okta Admin, and added it to the Authentication Policy? There are more details here: https://developer.okta.com/docs/reference/api/authn/#forgot-password where it notes:

```
SMS recovery Factor must be enabled via the user's assigned password policy to use this operation.
```

One way to test everything is enabled is to try doing the "forgot password" flow from your Okta-hosted organization page. This will do the flow through our "signin widget" https://github.com/okta/okta-signin-widget

**Comment by DeepBhat** [comment]
@aarongranick-okta Oh I changed the authentication to Email authentication, but I was following this example otherwise.

**Comment by aarongranick-okta** [comment]
@DeepBhat With email authentication the flow would be a little different (probably caling verify is the end of the flow until the user clicks a link in the email which will open a new app instance). Were you able to get your app working?

**Comment by DeepBhat** [comment]
Oh I am sorry, the email authentication method did not require a verification code. Thank you for your help, I will close this issue.
