### ISSUE TITLE
Recent Notice: Auto-blocking third party cookies via "Enhanced Tracking Protection"

### ISSUE THREAD

**Issue by chrismllr** [okta/okta-auth-js#502]
Received an email from Okta Support today, regarding the introduction of features like "Intelligent Tracking Protection" and "Enhanced Tracking Protection" in most modern browsers (Eg Firefox, Safari)

I noticed the documentation for this addon, the section on [third party cookies](https://github.com/okta/okta-auth-js#third-party-cookies) includes a note on `getWithoutPrompt` and `renew` being methods that will potentially be blocked by these new features. It also mentions to "rewrite your application" to avoid these methods.

From my understanding, there is no way to extend a user's session beyond 1 hour without these methods, as `renew` calls `getWithoutPrompt` under the hood implicitly, regardless. 

Based on the email received, how does that affect the usage of this library, and if affected, what steps are being taken (with timelines if possible) to work towards features to make renewing tokens functional?

**Comment by swiftone** [comment]
Hey @chrismllr, thanks for the questions.

I'm afraid I can't give you specific timelines as a matter of policy, but I can assure there is very active work on this issue.  

In terms of how it impacts the library, you can see where we're working on increasing the specific information here: https://github.com/okta/okta-auth-js/pull/460.  The guidance there is in addition to, not in place of, broader technical approaches we are taking.
