### ISSUE TITLE
token.parseFromUrl(options) docs links to a 404

### ISSUE THREAD

**Issue by mraible** [okta/okta-auth-js#505]
`token.parseFromUrl(options)`

Parses the authorization code, access, or ID Tokens from the URL after a successful authentication redirect. Values are parsed from either the search query or hash fragment portion of the URL depending on the responseMode.

If an authorization code is present, it will be exchanged for token(s) by posting to the tokenUrl endpoint.

The ID token will be verified and validated before available for use.

"verified and validated" links to https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L186-L190, which is a 404.

**Comment by swiftone** [comment]
@mraible - Thanks for the ticket, we'll get that cleaned up.

This points to the code, so our options for a direct link will either easily break again, or we point to a possibly-out-of-date code snippet.  For anyone looking, here is a (currently correct) version of the link: https://github.com/okta/okta-auth-js/blob/master/lib/token.ts#L112 (the `verifyToken` function)

When we fix this, though, we'll remove the link to the code and link elsewhere in the documentation (such as: https://github.com/okta/okta-auth-js#tokenverifyidtokenobject )

Internal ref: OKTA-336852
