### ISSUE TITLE
IE11: AuthSdkError: Unable to parse OAuth flow response error

### ISSUE THREAD

**Issue by DesigningStudios** [okta/okta-auth-js#516]
We are trying to implement in Okta-Auth in Angular5 project, with JS approach (not via npm import or require) and we ran in to below issue, specific to IE11 browser and the version number if it helps: 11.726.15063.0

1. Download below js files at ngAfterViewInit
https://global.oktacdn.com/okta-auth-js/4.0.2/okta-auth-js.polyfill.js
https://global.oktacdn.com/okta-auth-js/4.0.2/okta-auth-js.min.js

2.  declared global variable like below in the component "ts" file
declare var OktaAuth: any;

3. On button click, we are trying to open Okta login in a popup and return "key"
oktaCall() {
	const oktaAuth = new OktaAuth({
		issuer: 'AAA',
		clientId: 'BBB',
		authorizeUrl: 'CCC',
		pkce: false,
		redirectUri: 'DDD'
	});
	oktaAuth.token.getWithPopup({
		scopes: [
			'openid',
			'profile'
		],
		responseType: 'code'
	}).then(function (res) {
		console.log(res, 'response');
	}).catch(function (err) {
		console.log(err, 'error');
	});
}

4. In IE11, as soon as we click the button, below information, printed in console
AuthSdkError: Unable to parse OAuth flow response error
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to parse OAuth flow response",
      errorCauses: [ ],
      errorCode: "INTERNAL",
      errorId: "INTERNAL",
      errorLink: "INTERNAL",
      errorSummary: "Unable to parse OAuth flow response",
      message: "Unable to parse OAuth flow response",
      name: "AuthSdkError",
      stack: "AuthSdkError: Unable to parse OAuth flow response
   at Anonymous function (https://global.oktacdn.com/okta-auth-js/4.0.2/okta-auth-js.polyfill.js:13:35223)
   at Anonymous function (https://global.oktacdn.com/okta-auth-js/4.0.2/okta-auth-js.polyfill.js:13:30458)
   at e (https://global.oktacdn.com/okta-auth-js/4.0.2/okta-auth-js.polyfill.js:13:33611)
   at ZoneDelegate.prototype.invoke (eval code:386:13)
   at Zone.prototype.runGuarded (eval code:151:21)
   at Anonymous function (eval code:129:17)",
      Symbol()_j.s6y9vtv9ow3: undefined,
      Symbol()_k.s6y9vtv9ow3: undefined,
      Symbol(observable)_i.s6y9vtv9ow3: undefined,
      Symbol(react.element)_g.s6y9vtv9ow3: undefined,
      Symbol(rxSubscriber)_h.s6y9vtv9ow3: undefined
   }
   "error"

**Current behavior:**
Above message printing in console at the same time after login success, popup is not closing automatically.

**Expected behavior:**
After login success, popup should close automatically and return "res"

**Note:** In other browsers like IE Edge (Old), IE Edge (New) and Firefox, Chrome its working as expected.

**Comment by aarongranick-okta** [comment]
@DesigningStudios I notice that your config is specifying `pkce: false` and also `responseType: code` in the call to `getWithPopup`. Is the clientId you are using a `web` or `SPA` type? (It looks like a "web" type. This is probably not the cause of your error, but typically angular applications use a `SPA` type and perform all logic client-side).

I think the source of the error may have to do with how the polyfill is being included. Since the polyfill will modify global objects in the browser, it should be included before any other script is run. I recommend putting it in a `<script>` tag in the HEAD of the document. For example: https://github.com/okta/okta-auth-js/blob/master/samples/generated/static-spa/public/index.html#L6

**Comment by DesigningStudios** [comment]
@aarongranick-okta clientId is a "web" type. I tried loading JS files at "index.html" instead of component level, but problem remains same.

**Comment by aarongranick-okta** [comment]
@DesigningStudios My next guess is that it may be related to the "document mode". From our testing we have found that IE11 will not work if it is using an older document mode, even with the polyfill. If you are able to open the developer tools in IE, can you see what document mode it has selected for the page? This page may be useful for reference: https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/deprecated-document-modes

**Comment by DesigningStudios** [comment]
@aarongranick-okta For the IE11, I am using "document mode" is <!DOCTYPE html> which is as defined in "index.html" in our SPA Angular project.

**Comment by aarongranick-okta** [comment]
@DesigningStudios We will investigate this issue and try to reproduce using the internal test app included in `okta-auth-js`: https://github.com/okta/okta-auth-js/tree/master/test/app It may be several days before we are able to conclude our investigation, in the meantime you may also find it useful to try your configuration in the test app.  Internal ref: OKTA-338991

**Comment by denysoblohin-okta** [comment]
@DesigningStudios 
Hi. Let me help you with this issue. I have several questions:

1. Does the browser ask you for permission to open a popup window? If yes, do you allow it once or permanently? Does the page reload when you allow permissions?
2. Press F12 and in developer console type `document.documentMode`. Will it return `11` as on the screenshot?
![VirtualBox_my win10_30_10_2020_14_28_19](https://user-images.githubusercontent.com/72614880/97706902-1b0f5f00-1abf-11eb-9dbf-671479501e96.jpeg)
3. To clarify the exact time when `AuthSdkError: Unable to parse OAuth flow response error` is printed in the console.
   - Is it printed at the same time as the popup window opens (before you type credentials)?
   - or after you type credentials in the login popup and press "Sign in"?
   - or after you manually close the popup window (which is not closed automatically)?
4. Have you tried on other versions of IE11 (besides 11.726.15063.0)?

**Comment by DesigningStudios** [comment]
@denysoblohin-okta Here are the answers to your Q's
1. Browser did not ask for permission.
2. Returned 11 when I executed.
3. After manually closing popup.
4. Other versions of IE we tried (11.1082.18362.0)

**Comment by denysoblohin-okta** [comment]
@DesigningStudios 
Can you please try to use test app?
Open https://okta-auth-js-test.herokuapp.com/
Click "Login using POPUP"
User: test@okta.com
Password: Passw0rd

I wasn't able to reproduce the issue with this test app on IE11, but maybe you have a bit different setup/internet options.

If you don't have issue with test app, can you please share the part of your project responsible for auth?

**Comment by DesigningStudios** [comment]
@denysoblohin-okta testApp modal got closed after sign in success but as soon I replace OKTA configurations with our site it did not close.

At getWithPopup we are sending idp and responseType: 'code' along with "scopes" that's the only difference from originally shared code, on how we are initializing OktaAuth.

**Comment by denysoblohin-okta** [comment]
@DesigningStudios What idp are you using?

**Comment by denysoblohin-okta** [comment]
@DesigningStudios Could you please reach out to our support team at developers@okta.com  with this issue?

**Comment by denysoblohin-okta** [comment]
We are going to close this issue because we haven't heard back, but please re-open this issue if you want to continue working on it with us

**Comment by mfaradzheva-hubble** [comment]
@denysoblohin-okta 
In a message above.

> To clarify the exact time when `AuthSdkError: Unable to parse OAuth flow response error` is printed in the console.
> * Is it printed at the same time as the popup window opens (before you type credentials)?

This is actually a case in my situation I get error `Unable to parse OAuth flow response error` before credentials.  
@okta/okta-auth-js: ^6.9.0
Chome: Version 118.0.5993.88
I noticed that in this part of the code.
https://github.com/okta/okta-auth-js/blob/eeac1d1ebc4c9cc5179d438c4fd9c715f1b885a4/lib/oidc/getToken.ts#L172
```
var closePoller = setInterval(function () {
              if (!popupWindow || popupWindow.closed) {
                clearInterval(closePoller);
                reject(new AuthSdkError('Unable to parse OAuth flow response'));
              }
            }, 100);
```
On first interval **popupWindow.closed** is **false**. On second interval **popupWindow.closed** is **true**.
Would you be able to help and figure out what causes **popupWindow.close** = **true**?
Thank you

**Comment by jaredperreault-okta** [comment]
@mfaradzheva-hubble Can you please create a new issue? This thread is almost 3 years old

**Comment by mfaradzheva-hubble** [comment]
@jaredperreault-okta Resolution found: On the first sign-in, when the cache and local storage are empty, the COOP header was triggering a reject.
