### ISSUE TITLE
Custom Storage setItem loops

### ISSUE THREAD

**Issue by DavidLozzi** [okta/okta-auth-js#521]
We have a custom setItem for our tokenManager. We are adding a little bit of code in there to also set a unique id to our cookies, we need this unique id to pair with our access token.  We notice that our unique id is changing in the cookie every second, we also see in the network tab a request to `authorize?client_id=xxx` which seems to correspond to our cookie changing. Is the library looping on purpose? Is this a bug? 

```
    setItem: (key, val) => {
      try {
        let options = { expires: 1 };
        if (env !== 'local') { // localhost has some restrictions
          options = Object.assign(options, { secure: true, domain: '.bcg.com' });
        }

        const value = JSON.parse(val);

        Object.keys(value).forEach((k) => {
          const storageKey = `${key}_${k}`;
          delete value[k].value; // unncessary and makes cookie heavy
          Cookies.set(storageKey, value[k], options);
        });

        //we want to save id info separately because the id token will expire faster than access token
        Cookies.set('okta-user-claims', value.idToken.claims, options);

       // here we want to set another cookie with a unique GUID
       Cookies.set('okta-psid', uuidV4(), options);
      } catch (e) {
        console.error('OKTA tokenManager storage setItem', e);
      }
    }
```

![image](https://user-images.githubusercontent.com/3543383/97007892-17ecff80-1510-11eb-910d-79ef9443fe52.png)

**Comment by aarongranick-okta** [comment]
@DavidLozzi Are you using the `expiresEarlySeconds` option?

**Comment by DavidLozzi** [comment]
YYyyup, that'll do it. Thanks!
