### ISSUE TITLE
Mismatch between `verifyRecoveryToken` documentation and type definition

### ISSUE THREAD

**Issue by ryanhachtel** [okta/okta-auth-js#530]
The [documentation](https://github.com/okta/okta-auth-js#verifyrecoverytokenoptions) for `verifyRecoveryToken` details the option parameter as `{recoveryToken: '00xdqXOE5qDZX8-PBR1bYv8AESqIFinDy3yul01tyh'}` but the type definition for this function is `VerifyRecoveryTokenOptions` which is defined as:
```Javascript
export interface VerifyRecoveryTokenOptions {
    relayState?: string;
}
```
Image of what I see in my editor:
![image](https://user-images.githubusercontent.com/5600230/97643852-00c57a80-1a06-11eb-991b-76146565218a.png)

Details:
Using Okta-auth-js version `4.0.3`

**Comment by swiftone** [comment]
@ryanhachtel - Thanks for the report.  You are correct, we'll be pushing out a fix.  If you need help with a work-around in the meantime, please let us know.

**Comment by ryanhachtel** [comment]
@swiftone Great, thanks! What is the correct usage?

**Comment by shuowu** [comment]
@ryanhachtel Based on  [recovery transaction](https://developer.okta.com/docs/reference/api/authn/#verify-recovery-token), the readme should have the correct information.

Internal Ref: OKTA-343152

**Comment by ryanhachtel** [comment]
@shuowu Thank you!

**Comment by denysoblohin-okta** [comment]
Fixed with https://github.com/okta/okta-auth-js/pull/541
