### ISSUE TITLE
MFA Typescript Definitions

### ISSUE THREAD

**Issue by sdenardi** [okta/okta-auth-js#539]
Hi there, I've been able to successfully implement the MFA enroll/verify and required/challenge workflows into our Typescript project. However, it seems like the Typescript definitions are incomplete for the various fields and methods used for MFA operations. The ones I'm specifically getting errors where they do not exist (despite existing in the documentation and working fine in our project) are:

- `AuthTransaction.factors` (would assume to return an array of `Factor` or something with `enroll()`, `verify()`, etc.)
- `AuthTransaction.verify({ passCode: string })`

I would be happy to submit a PR to add these types, but I'm also having trouble finding the source for the MFA calls.

Thanks for your help.

**Comment by shuowu** [comment]
@sdenardi Thanks for reporting the issue! Unfortunately, I am not aware of any documentation defines the types. We will add the missing types in the near future.

Internal Ref: OKTA-343852

**Comment by sdenardi** [comment]
@shuowu Thanks for the reply.

Out of curiosity, where are those functions and fields defined in this repository? I can see the test fixtures for them, but not the definitions themselves.

**Comment by shuowu** [comment]
@sdenardi Those are functions generated from transaction response. You can check [tx/AuthTransaction.ts](https://github.com/okta/okta-auth-js/blob/master/lib/tx/AuthTransaction.ts) for more details.

**Comment by sdenardi** [comment]
Ahh I didn't know they were generated dynamically depending on the response. Makes sense why they aren't in the Typescript definitions currently getting shipped. Thanks again for your help.

**Comment by shuowu** [comment]
MFA Types has added in #554
