### ISSUE TITLE
What's the okta-auth-js way of authenticating with an activation token?

### ISSUE THREAD

**Issue by ilyakam** [okta/okta-auth-js#547]
I am in the process of refactoring the application from raw API calls to `"https://${yourOktaDomain}/api/v1/authn"` to using this library. One of the features that the `/authn` API provides is the ability to authenticate with an activation token, as seen in the Authentication API docs » Authentication Operations » Primary Authentication » …with activation token ([direct link](https://developer.okta.com/docs/reference/api/authn/#primary-authentication-with-activation-token)).

I cannot find a way to pass the `${activationToken}` value, as seen on the bottom of the first table [on this Email » Custom variables » User Activation page](https://help.okta.com/en/prev/Content/Topics/Settings/settings-EL-activation.htm), to this library. The backend that I'm calling is acting as a proxy and it's hiding the secret `Authorization: SSWS ${api_token}` header, so it is not exposed in any way.

Here's the full use-case:

1. User signs up for a new account via [this API call](https://developer.okta.com/docs/reference/api/users/#create-user-without-credentials)
1. User receives email that contains the aforementioned `${activationToken}`
1. Application authenticates user from that token and gets access to their profile

I am currently stuck on step 3. Alternatively, I am open to suggestions on how to accomplish all of the above while using [transactions](https://github.com/okta/okta-auth-js#transactionstatus). Thanks in advance!

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the submission @ilyakam. This is not documented(and not recommended for Prod use), but you might be able to pass the activationToken via `token` property, for example: `oktaAuthInstance.signInWithCredentials({token: activationToken})`. This is being done under the hood by the [sign-in-widget](https://developer.okta.com/code/javascript/okta_sign-in_widget/).

adding this to triage list 
Internal ref: OKTA-347409

**Comment by ilyakam** [comment]
Hello @oleksandrpravosudko-okta,

I just wanted to follow up and say that your suggestion worked as expected, thank you! Since we're still using v3.2.4, we ended up using [`oktaAuthInstance.signIn(credentials)`](https://github.com/okta/okta-auth-js/tree/okta-auth-js-3.2.4#signinoptions) where `credentials` is:

```ts
interface IOktaSignInCredentials {
  password?: string;
  token?: string;
  username?: string;
}
```

This was so we could use the same method to sign in with the `username` and `password` combination or with just the `token`.

> adding this to triage list to see if we can have documented support for authenticating with activationToken
Internal ref: [OKTA-347409](https://oktainc.atlassian.net/browse/OKTA-347409)

Thank you for doing that. Since https://oktainc.atlassian.net/ is not accessible to the public, please update this ticket when you've resolved it internally. I'm going to close the issue for the time being.

**Comment by matijagrcic** [comment]
For anyone using SPA with PKCE and want to customize the flow fully you can leverage

[Primary authentication with activation token](https://developer.okta.com/docs/api/resources/authn#primary-authentication-with-activation-token) which when called will result in the same response as the workaround mentioned.

In our case [Response example for activation token (success - user without password)](https://developer.okta.com/docs/reference/api/authn/#response-example-for-activation-token-success-user-without-password).

This won't work in SPA apps

`const register = await oktaAuth.idx.register({ activationToken: activationToken });`
 //will result in OAuthError: Only confidential clients can use the activation token flow.

If you do

` const signInWithCredentialsResponse = await oktaAuth.signInWithCredentials({ token: activationToken });`
// you can proceed and the response would be same as above

![image](https://github.com/okta/okta-auth-js/assets/3612395/9dc4a299-ce24-42c2-a09b-afad7c589565)
