### ISSUE TITLE
Can't build the SDK locally

### ISSUE THREAD

**Issue by DavidLozzi** [okta/okta-auth-js#552]
I am attempting to build the SDK locally, and getting countless errors. After I clear one, another library errors. Before I start reporting every error, I am guessing I am on the wrong version of a few apps. What version of node, npm, yarn, webpack-cli, etc should I be on?

I also noticed that build.js is referring to libraries that were not installed when I ran `yarn install`, like `shelljs` and `chalk`. Could be a version issue, as noted before, or something missing in `package.json`? 

Any help would be greatly appreciated!

**Comment by aarongranick-okta** [comment]
@DavidLozzi I am assuming you are on Mac or Linux - if you are on Windows there may be another issue.

We have seen some issues when `npm` and `yarn` are both used on the same project. For this SDK we use `yarn` (I am running version 1.21.0). On a clean clone of the repo (remove node_modules or run `yarn clean`), you should be able to install and build by simply running `yarn` (it will install everything then run the `prepare` script which will build the SDK and samples).

```
 "engines": {
    "node": ">=10.3",
    "yarn": "^1.7.0"
  },

```

**Comment by DavidLozzi** [comment]
I am on Windows :( 
However, I'll give a clean install another try just using Yarn (I had tried npm first).

**Comment by DavidLozzi** [comment]
It errored on generateSample, which I think is okay? I don't need it, I hope, I just want to debug some stuff using `yarn link`. moving forward

```
[13:37:55] 'generateSample' errored after 11 s
[13:37:55] Error in plugin 'gulp-compile-handlebars'
Message:
    The partial spa/README.md could not be found
Details:
    description: undefined
    fileName: undefined
    lineNumber: undefined
    endLineNumber: undefined
    number: undefined
    domainEmitter: [object Object]
    domainThrown: false
[13:37:56] 'default' errored after 13 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by aarongranick-okta** [comment]
It may be a problem with forward vs. backward slashes. We all work on Macs and rarely build on Windows. But if you are able to find/fix the problems I can get the fixes merged in.

**Comment by DavidLozzi** [comment]
This all worked, the link worked and I could see my code changes in my project. I'm not going to chase down the samples, don't need them right now ;) Thanks for the help!
