### ISSUE TITLE
question: Is it possible to get transaction object from existing Okta session?

### ISSUE THREAD

**Issue by yuhui-lin** [okta/okta-auth-js#564]
Hey,
   Our use case is  that we allow users to reset their MFA when they logged in. According to the [API](https://developer.okta.com/docs/reference/api/authn/#enroll-okta-verify-totp-factor), we need the `stateToken` of a transaction to be able to re-enroll the users to Okta Verify. When they already logged in, we don't have user password so `SigninWithCredential` cannot be used to get transaction. So I wonder if there is a way to create a transaction(and its stateToken) from existing session?
Thanks.

**Comment by shuowu** [comment]
@yuhui-lin In your use case, you can call the [Enroll factor API](https://developer.okta.com/docs/reference/api/factors/#factor-lifecycle-operations) directly. It doesn't need to be wrapped in an auth transaction.

**Comment by yuhui-lin** [comment]
@shuowu Good to know. Thanks!
