### ISSUE TITLE
ES6 Module Support

### ISSUE THREAD

**Issue by PaulHMason** [okta/okta-auth-js#568]
Hi

Does okta-auth-js support ES6 modules? I'm trying to wrap everything in a native custom element but I can't seem to get importing OktaAuth to work (it blows up on node-ponyfill.js).

Thanks

Aside: Providing the sign-in widget as a native custom element with shadow dom would be very handy.

**Comment by oleksandrpravosudko-okta** [comment]
hi @PaulHMason - thanks for reaching out

okta-auth-js does provide [esm](https://github.com/okta/okta-auth-js/blob/master/package.json#L10) entry point - can you please share a few details on the platform producing this error and the way OktaAuth is imported?

re: sign-in-widget as a native custom element - would you mind opening a separate issue in the [okta-signin-widget](https://github.com/okta/okta-signin-widget) repo?

**Comment by shuowu** [comment]
@PaulHMason Currently, okta-auth-js only exposes ems for the server-side bundle. You'll need to use the [browser bundle](https://github.com/okta/okta-auth-js/blob/master/package.json#L11) (umd bundle) to build your custom element.

**Comment by milesje** [comment]
I'm also attempting to use this library in a LitElement (PolymerJS) based SPA and have been unsuccessful in getting the library to work. I've tried to import both `import { OktaAuth } from '@okta/okta-auth-js'` and `import { OktaAuth } from '@okta/okta-auth-ja/dist/okta-auth-js.umd.js'` both of which error out.
The first results in `Uncaught SyntaxError: import not found: default`
The second results in `Uncaught SyntaxError: import not found: OktaAuth`

**Comment by shuowu** [comment]
UPDATE: the okta-auth-js ES module bundle is isomorphic for both browser and server side since version 5.x. 

Close this issue, please reopen or create a new issue if you have further questions.
