### ISSUE TITLE
feat request: add option to persist `okta-cache-storage` in session storage

### ISSUE THREAD

**Issue by lfurzewaddock** [okta/okta-auth-js#571]
```
"@okta/okta-auth-js": "^4.1.2",
"@okta/okta-react": "^3.0.8",
```

```
        new OktaAuth({
          issuer,
          clientId,
          redirectUri,
          pkce,
          tokenManager: {
            autoRenew: true,
            secure: true,
            storage: 'sessionStorage',
            expireEarlySeconds: 120,
            cookies: {
              secure: true,
              sameSite: 'none',
            },
          },
        })
```

We can sign into our app with multiple accounts in the same web browser window **(using 1 tab per user account)** when token manager storage = `sessionStorage`

The problem is, the most recent sign in by any tab is saved in local storage with key: `okta-cache-storage` which is shared by all tabs. So, 1 hour later for each tab when the tokens are auto renewed all tabs sign into the same account last stored in `okta-cache-storage`.

Is it possible to set `okta-cache-storage` to persist in session storage?

**Comment by swiftone** [comment]
@lfurzewaddock - Thanks for the request.  Unfortunately, there would be problems with the autorenew regardless - it relies on a session cookie on the issuer domain to decide to mint new tokens, and cookies are not tab-specific.

I do have good news though - Okta is releasing one-time refresh tokens for SPA applications, removing the need for that session cookie to "renew" tokens.   While I don't recall testing this specific use-case, it may be that this resolves the issue you are facing (so long as you are using sessionStorage as your token manager storage).

This feature is still in early access, so I suggest reaching out to developers@okta.com to make sure of the timing.

**Comment by lfurzewaddock** [comment]
Thanks @swiftone for your response. I've upgraded libs to the latest version and although as you know my issue remains, v4 is a big improvement over v3, so thanks for that. 

```
 "@okta/okta-auth-js": "^4.5.0",
 "@okta/okta-react": "^4.1.0",
```

I'll request Okta support to enable early access to the one-time refresh tokens feature you mentioned.  Could you point me somewhere to any dev docs?

**Comment by swiftone** [comment]
@lfurzewaddock - check step 4 on this guide: https://developer.okta.com/docs/guides/sign-into-spa/react/create-okta-application/
