### ISSUE TITLE
Dependecy (Base64.js) license is not enterprise safe

### ISSUE THREAD

**Issue by aklinker1** [okta/okta-auth-js#588]
We're using `@okta/okta-react-native`, and `@okta/okta-auth-js` is a transient dependency.

Our enterprise dependency scanner has flagged [`Base64.js`](https://github.com/davidchambers/Base64.js) (a transient dependency of `@okta/okta-auth-js`, because it uses the WTFPL license, and our company doesn't want any explicit language in our third party library list.

> GitHub states it's Apache 2.0, but if you open the license, it's a dual license between Apache and "WTFPL"

Is there a way the dependency on [`Base64.js`](https://github.com/davidchambers/Base64.js) could be dropped? We have had lots of issues getting the login flow working, and don't want to refactor to another auth library again...

**Comment by swiftone** [comment]
@aklinker1 - before diving any deeper into this, and speaking as a non-lawye: Okta is using the Apache version of the two licensing options, can you not do the same?  Then the terms are not explicit.  (Well, the terms are explicit, but the language is not :) )

**Comment by aklinker1** [comment]
> Then the terms are not explicit. (Well, the terms are explicit, but the language is not :) )

Haha nice. TBH, I didn't know that you got to choose which license you want to use for dual license. Not sure how I thought they worked. But thanks for answering that, I'll go ahead and close this now.
