### ISSUE TITLE
Session Support For Cookie Support

### ISSUE THREAD

**Issue by jpspringall** [okta/okta-auth-js#592]
We would like the ability for our tokens to be session based, so that if a user closes their browser without logging out then the tokens are disposed of.

Meaning that a user is forced to re authenticate when re visiting the site.

I presume the expected way of achieving this is to use session storage. However in our case this is not possible due to the fact that are utilizing SSR.

We are still authenticating client side, but we need to pass up the tokens to the SSR server in subsequent requests.
It appears that the standard way of achieving this is by using cookies, here is a link to the article we used as a guide:
https://dev.to/igorfilippov3/angular-universal-boilerplate-setup-239e

So we are required to use cookie storage.
However cookie storage is hard coded to use the expiry date of  '2200-01-01T00:00:00.000Z'

So I have introduced a new setting called sessionCookie at tokenManager level, that if set to true will create your tokens with session based cookies rather than a specific date.

This setting also gets automatically applied if you have explicitly requested sessionStorage.

I have added tests, and manually tested with getWithoutPrompt and getWithRedirect

The only thing I haven't been able to do is run the e2e tests.
It appears that the tests really don't like running on windows, so I'm using WSL, and having issues I keep getting timeouts

PR is here: https://github.com/okta/okta-auth-js/pull/591

Thanks

James

**Comment by aarongranick-okta** [comment]
@jpspringall Thanks for bringing this to our attention. The scenario you describe makes sense, and doesn't seem directly supported by the current options. However, you can pass a custom `StorageProvider` to the `tokenManager` options: https://github.com/okta/okta-auth-js#storage

This allows you to customize the token storage in any way, including using session cookies.

We will evaluate adding a `sessionCookie` option to make this easier (I think it's a good idea). 

Internal ref: OKTA-367497

**Comment by shuowu** [comment]
Fixed since v5.0
