### ISSUE TITLE
v4.1.0 handle login redirect deprecation 

### ISSUE THREAD

**Issue by lawandothman** [okta/okta-auth-js#593]
Hi, 

I'm trying to implement the OktaSignInWidget into my react app. Everything seems to be working fine but I'm getting the following warning in my console on login : 
 
![image](https://user-images.githubusercontent.com/58405138/104716168-71d02080-571f-11eb-82ad-d5368974e59b.png)

I have followed the official documentation, this is the code for the OkatSignInWidget: 
```javascript
const OktaSignInWidget = ({ config, onSuccess, onError }) => {
  const widgetRef = useRef();

  useEffect(() => {
    if (!widgetRef.current) {
      return false;
    }
    const widget = new OktaSignIn(config);
    widget
      .showSignInToGetTokens({
        el: widgetRef.current,
      })
      .then(onSuccess)
      .catch(onError);

    return () => widget.remove();
  }, []);

  return <div ref={widgetRef} />;
};

export default OktaSignInWidget;
``` 
And the code for the login component: 
```javascript

const Login = ({ config }) => {
  const { oktaAuth, authState } = useOktaAuth();
  const dispatch = useDispatch();

  const onSuccess = (tokens) => {
    oktaAuth.handleLoginRedirect(tokens);
    const accessToken = tokens.accessToken.value;
    dispatch(login(accessToken));
  };

  const onError = (err) => {
    console.error('error logging in', err);
  };

  if (authState.isPending) return null;

  return authState.isAuthenticated ? (
    <Redirect to={{ pathname: '/' }} />
  ) : (
    <OktaSignInWidget config={config} onSuccess={onSuccess} onError={onError} />
  );
};

export default Login;
```

I am using `@okta/okta-react v4.1.0` ,  `@okta/okta-auth-js v4.5.0`, `@okta/okta-signin-widget v5.2.0`

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report @lawandothman 

This warning is triggered by sign-in widget [code](https://github.com/okta/okta-signin-widget/blob/master/src/models/PrimaryAuth.js#L119) invoking the deprecated method.
A story for upgrading to `signInWithCredentials` It is already logged in our backlog:

Internal Ref: OKTA-354782
