### ISSUE TITLE
State not being returned when using getWithoutPrompt

### ISSUE THREAD

**Issue by thetif** [okta/okta-auth-js#598]
I am use v.4.6.1. I have been using getWithoutPrompt for a while and it was returning state, now I'm getting undefined when I try to get it from the response. I have tried this on two different Okta instances, so it's not my environment.

**Comment by swiftone** [comment]
@thetif - Thanks for the report, can I ask some clarifying questions?

- Are you seeing this when you changed versions, or did the same code, same version, just start returning a different response one day?  (If so, when)

- Can you share the code for a simple reproduction case?

**Comment by thetif** [comment]
It was working on Friday and it wasn't working this morning. I'm not sure at what point over the long weekend it stopped working. We didn't touch the code though.

Here is the token code we are using:
`export const setTokens = sessionToken => {
  const stateToken = uuidv4();
  return oktaAuth.token
    .getWithoutPrompt({
      // responseType: ['id_token', 'token'],
      scopes: ['openid', 'email', 'profile'],
      sessionToken,
      state: stateToken
      // prompt: 'none'
    })
    .then(async res => {
      const { state: responseToken, tokens } = res;
      if (stateToken === responseToken) {
        await oktaAuth.tokenManager.setTokens(tokens);
        const expiresAt = await getSessionExpiration();
        return expiresAt;
      }
      throw new Error('Authentication failed');
    });
};`

You can see the code that I changed to work around the issue here https://github.com/CMSgov/eAPD/pull/2789

**Comment by swiftone** [comment]
@thetif - Thanks for the example.  You definitely should not be seeing any change like you describe, I'll see if I can get it to reproduce and find out what happened.

**Comment by aarongranick-okta** [comment]
@thetif are you still experiencing this issue, or were you able to find a resolution?

**Comment by shuowu** [comment]
Issue is addressed in [v5.3.0](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.3.0).
