### ISSUE TITLE
Okta signInWithCredentials is failing the call.

### ISSUE THREAD

**Issue by staffordp** [okta/okta-auth-js#599]
We use the okta-auth.js library v4.5.0 for a customized update Password page we have created.  After a user has changed their password, a function is called to re-login the user with the new credentials to issue a new set of tokens.  We also use the Okta-widget v5.0.0 for the initial login.  This issue started cropping up sometime near the time where we integrated the widget into the repo.  Not entirely sure if it happened before or after as we noticed after the widget had already been in place.

Currently, this call is failing.  Here are the details of the function for the call: (I have replaced the domain with somedomain.com for the purpose of this example):

```
  reLogin() {
    this.spinner.show();
    this.token.email = this.cookieService.get('ses-username');
    this.token.password = this.passwordCredential.newPassword;
    this.authSvc.login(this.token).then(data => {
      if (!!data.transaction) {
        if (data.transaction.status === 'SUCCESS') {
          if (this.appConfig.getConfig('local')) {
            this.cookieService.set('token-claims', (data.tokens && data.tokens.idToken && data.tokens.idToken.claims) ?
            JSON.stringify(data.tokens.idToken.claims) :
            undefined);
            this.cookieService.set('ses-tok',  data.tokens.accessToken.accessToken); // Developer
            this.cookieService.set('ses-time', (new Date().getTime() + (this.idleTimeoutMinutes * 60000)).toString());
          } else {
              this.cookieService.set(
                'ses-tok',
                data.tokens.accessToken.accessToken,
                null, // We are relying on Okta session expiration
                '/',
                '.somedomain.com',
                true
              );
              this.cookieService.set(
                'ses-time',
                (new Date().getTime() + (this.idleTimeoutMinutes * 60000)).toString(),
                null,
                '/',
                '.somedomain.com',
                true
              );
              this.cookieService.set('token-claims',
                data.tokens.idToken.claims ? JSON.stringify(data.tokens.idToken.claims) : undefined,
                null,
                '/',
                '.somedomain.com',
                true);
              this.cookieService.set('token-expiresat',
                data.tokens.idToken.expiresAt,
                null,
                '/',
                '.somedomain.com',
                true);
              this.cookieService.set(
                'token-idtoken',
                data.tokens.idToken.idToken,
                null,
                '/',
                '.somedomain.com',
                true
              );
            this.cancel();
          }
        }
      }
      this.spinner.hide();
    });
  }
```

and okta config:

```
    this.authClient = new OktaAuth({
      clientId: this.appConfig.getConfig('oktaClientId').toString(),
      issuer: this.appConfig.getConfig('oktaUrl').toString(),
      redirectUri: this.appConfig.getConfig('oktaRedirectUri').toString(),
      postLogoutRedirectUri: this.appConfig.getConfig('oktaRedirectUri').toString(),
      tokenManager: {
        storage: 'sessionStorage',
        autoRenew: false
      },
    });
```

and the call to login in the authSvc:

`  async login(user: TokenPayload) {
    try {
      const data = {
        username: user.email,
        password: user.password
      };

      this.transaction = await this.authClient.signInWithCredentials(data);
      return await this.getToken(this.transaction);
    } catch (err) {
      return err;
    }
  }`

our call to getToken:

```
  async getToken(transactions) {
    let receivedTokens;
    if (transactions && transactions.status === 'SUCCESS') {
      await this.authClient.token.getWithoutPrompt({
        responseType: ['code', 'token', 'id_token'],
        sessionToken: transactions.sessionToken,
        scopes: ['openid', 'offline_access', 'email'],
      })
      .then(res => {
        receivedTokens = res.tokens;
        this.authClient.tokenManager.add('idToken', receivedTokens.idToken);
        this.authClient.tokenManager.add('accessToken', receivedTokens.accessToken);
      });
    }
    return {
      transaction: transactions,
     tokens: receivedTokens
    };
  }
```
![error2](https://user-images.githubusercontent.com/12960670/105189936-80458000-5b03-11eb-90bd-29781d7ec252.JPG)
![error1](https://user-images.githubusercontent.com/12960670/105189937-80458000-5b03-11eb-8acc-6f870ab479cc.JPG)

The details of the failed call are in the attachments.

**Comment by denysoblohin-okta** [comment]
@staffordp Can you please share details of the failed call to `authn` ? I don't see an attachment in your post.

**Comment by staffordp** [comment]
Sorry, please find the attachments here. It looks like it is a POST and is canceled for some reason.

![failed-call2](https://user-images.githubusercontent.com/12960670/105220119-45ecda80-5b25-11eb-8a2a-1de9f49aa4a6.JPG)
![failed-call1](https://user-images.githubusercontent.com/12960670/105220120-45ecda80-5b25-11eb-8b67-944c54d3d2ea.JPG)

**Comment by staffordp** [comment]
Anyone?  Is there a fix for this?

**Comment by oleksandrpravosudko-okta** [comment]
Hi @staffordp,

Unfortunately there are no immediate suggestions available on what causes the error.
I will recreate your setup and see if I can get more insights on the problem.

**Comment by staffordp** [comment]
Thank you, @oleksandrpravosudko-okta.  If you cannot find a fix after recreating the scenario, kindly let me know.

**Comment by oleksandrpravosudko-okta** [comment]
@staffordp It don't think I can reproduce this issue without the details on how password update is performed. Are you using [changePassword](https://github.com/okta/okta-auth-js#changepasswordoptions) to update expired user password?

In case this something you would rather not share in public and/or this is a pressing issue, please contact [Okta support](https://support.okta.com/help/s/?language=en_US).

If you chose to share the details here, I will add a backlog item for further investigation. Please note that it might take a while before it gets prioritised.

**Comment by staffordp** [comment]
@oleksandrpravosudko-okta 

We are not using the changePassword call built into the AuthJS library.  We had tried several releases back and could not get it working.  We currently have an API in place that is manually making a POST call to the Okta change password endpoint.

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for elaborating @staffordp.

Issue logged: 
Internal Ref: [OKTA-364519](https://oktainc.atlassian.net/browse/OKTA-364519)

One small question to clarify - any chance `reLogin` is invoked as `onSubmit` form handler? I noticed `/authn` requests being canceled while attempting to reproduce and having mistakenly omitted `preventDefault()` call in form handler.

**Comment by staffordp** [comment]
Here is the button in the HTML which is part of the form:
```

                <button type="submit" (click)="changeUserPassword(false)" [disabled]="!updatePasswordSetupForm.valid">
                                        {{templateString.CHANGE_PASS_BTN}}
                                    </button>
```

Note: we are using Angular's Material design.

**Comment by oleksandrpravosudko-okta** [comment]
Would it be possible for you to test `reLogin` code isolated from password update API call but still being invoked during form submission handling?

**Comment by staffordp** [comment]
@oleksandrpravosudko-okta I'm not sure I understand.  Do you want me to remove the call to the API which actually handles the changepassword function?  If I do that, the relogon will fail as it will be trying to use the new password.  Or is it you would like to me to just try to relogin with the old password and skip the whole password change call to the API?

**Comment by oleksandrpravosudko-okta** [comment]
> Or is it you would like to me to just try to relogin with the old password and skip the whole password change call to the API?

@staffordp  Yes, this is what I was hoping to check. The intent here is  to make sure there are no issues with code responsible for handling form submission.

**Comment by staffordp** [comment]
@oleksandrpravosudko-okta I just removed the entire call to the API and just perform a religion.  I still see the same error:

![Capture](https://user-images.githubusercontent.com/12960670/106040875-0be18280-60a9-11eb-81ae-9cae26590cba.JPG)

**Comment by oleksandrpravosudko-okta** [comment]
It looks like Angular [documentation](https://angular.io/start/start-forms) suggests placing form submit handler in `ngSubmit` directive: 
`<form [formGroup]="formGroupName" (ngSubmit)="onSubmit()">`
If that is not an option, you might want to pass an event object to `(click)="changeUserPassword($event, false)"` and call `preventDefault()` on it.

**Comment by staffordp** [comment]
@oleksandrpravosudko-okta Thanks for noticing that.  You are correct. It should be fixed. I am making that change now (along with upgrading the library to 4.6.1 to check if it makes a difference.

**Comment by staffordp** [comment]
@oleksandrpravosudko-okta even with that change and an update to the 4.6.1ibrary I am still encountering the same error.

![Capture](https://user-images.githubusercontent.com/12960670/106143923-7219e400-6141-11eb-8956-41fe1f102d01.JPG)

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for taking the time to test some assumptions @staffordp.

A few more questions:
* There seem to be >1 non-failed `/authn` request on the latest screenshot - are any of those successful POST requests?
* Is there a chance of page reload happening while `/authn` request is in progress?
* Would you be willing to create a minimal example of failing request? (e.g. single page with a basic form)

**Comment by staffordp** [comment]
@oleksandrpravosudko-okta I believe I found the issue in some code I didn't paste here as I didn't suspect it until I was doing some cleanup. It appears the crux of the issue was it was calling the login function and immediately doing a redirect without waiting for a reply.

I apologize for the wasted time.  Thank you for all your help!

**Comment by staffordp** [comment]
Issue resolved.
