### ISSUE TITLE
Token refresh will always request access token in non-PKCE mode

### ISSUE THREAD

**Issue by khitrenovich** [okta/okta-auth-js#600]
We have an app that uses only `id_token` with implicit flow. Accordingly, our `oktaAuth` instance is created with
```
  pkce: false,
  responseType: [ 'id_token' ],
```
I spotted that both ID token and access token are requested when token is auto-refreshed by the SDK. 

This leads to some unwanted side effects. The first and the obvious - we end up with an unused access token in the browser that our application did not request. On top of that, the SDK will attempt to revoke this access token on sign out - which requires additional CORS settings under Trusted Origins configuration. This may cause logout failures and lead to the situation when the tokens were cleaned up from the browser, but stay valid from Okta point of view.

----

I did some research, and I suspect that the following code is to blame - 
* https://github.com/okta/okta-auth-js/blob/eb7d70d902e1cccf767325dcbe3710d9f2da4be6/lib/token.ts#L850
* https://github.com/okta/okta-auth-js/blob/eb7d70d902e1cccf767325dcbe3710d9f2da4be6/lib/token.ts#L655

On the first line, `response_type` is explicitly set to `['token', 'id_token']` for non-PKCE flow.
On the second line, default response type (provided during creation) is replaced by the new value from above.

**Comment by swiftone** [comment]
Hi @khitrenovich!   This is an interesting problem - thank you for your detective work, that is very helpful, and I suspect you've nailed it.  

I'll take a look at writing some tests to verify the fix and see about getting this in.  Is this blocking for you so we should investigate a workaround in the meantime?

**Comment by swiftone** [comment]
Internal ref: OKTA-362425

**Comment by khitrenovich** [comment]
> Is this blocking for you so we should investigate a workaround in the meantime?

It depends on the ETA for the fix. Do you have something to share already?

**Comment by khitrenovich** [comment]
I see this is fixed in #614 and released in 4.7.0, closing. Thanks for the quick turnaround!
