### ISSUE TITLE
Custom Storage Example

### ISSUE THREAD

**Issue by garrettmac** [okta/okta-auth-js#606]
Is this actually wired up? https://github.com/okta/okta-auth-js#storage

Getting
```
 TypeError: e.getItem is not a function
    at Object.n [as getStorage] (okta-auth-js.umd.js:146)
    at e.L (okta-auth-js.umd.js:134)

```

Can you improve your docs or add an example.

And how do i set/get items... via https://github.com/okta/okta-auth-js#tokenmanageraddkey-token or `authClient.tokenManager.getItem`?

**Comment by shuowu** [comment]
@garrettmac The custom storage functions should be provided as config when initialize the oktaAuth instance.

https://github.com/okta/okta-auth-js#the-tokenmanager

**Comment by garrettmac** [comment]
yep, like this, right?
```js
var config = {
  url: 'https://{yourOktaDomain}',
 tokenManager: {
  storage: {
    getItem: function(key) {
      // custom get
    },
    setItem: function(key, val) {
      // custom set
    }
  }
}
};
var authClient = new OktaAuth(config);

```

then i would `authClient.tokenManager.setItem("name", value)` to add, as apposed to the tokenManager.add function? Is that correct?

**Comment by shuowu** [comment]
@garrettmac The custom functions are not added to tokenManager instance, but they are called when tokenManager.add/set is triggered.

You can check the implementation [here](https://github.com/okta/okta-auth-js/blob/master/lib/TokenManager.ts#L516) for details.

**Comment by garrettmac** [comment]
got it thanks
