### ISSUE TITLE
AuthSdkError: Unable to parse a token from the url

### ISSUE THREAD

**Issue by kthomas182** [okta/okta-auth-js#611]
Angular version: ^9.1.12
"@okta/okta-auth-js": "^4.6.1",

In my config I am passing in:

      clientId: '#####',
      redirectUri: 'http://localhost:4300/auth/callback',
      logoutUri: 'http://localhost:4200/auth/logout',
      issuer: 'https://myokainstance/oauth2/default',
      url: 'https://myokainstance',
      response_type: 'code',
      response_mode: 'fragment',
      state: 'something goes here',
      scopes: ['openid profile email'],

Here is a flow of what I'm doing:
- :4200/login -> invoke the signInWithCredentials(un/pw)
- This gives me a sessionToken fine and a stats => SUCCESS
- I invoke the this.authClient.session.setCookieAndRedirect(transaction.sessionToken, this.config.redirectUri);
- This redirects me to :4300/callback
- In my callback I'm invoking
authClient.token
  .parseFromUrl()
- This throws an AuthSdkError:
AuthSdkError: Unable to parse a token from the url

**Comment by shuowu** [comment]
@kthomas182 Your flow looks good to me. Just wondering why you need two ports for the app?

I'll also investigate on the issue.
Internal Ref: OKTA-365921

**Comment by kthomas182** [comment]
@shuowu they're (2) different angular apps. I'm trying to reproduce our environment.

We're authenticating in one application and doing a authClient.token.getWithRedirect() or authClient.session.setCookieAndRedirect() to the protected application.

This is where it is failing.

**Comment by kthomas182** [comment]
@shuowu the error I get when I change my call from:

this.authClient.session.setCookieAndRedirect(transaction.sessionToken, this.config.redirectUri)
to
            this.authClient.token.getWithRedirect({
              clientId: this.config.clientId,
              redirectUri: this.config.redirectUri,
              scopes: this.config.scopes,
              sessionToken: transaction.sessionToken,
              state: this.config.state,
              responseType: this.config.response_type,
            });

` AuthSdkError: Could not load PKCE codeVerifier from storage. This may indicate the auth flow has already completed or multiple auth flows are executing concurrently.`

**Comment by shuowu** [comment]
@kthomas182 The error looks like your two apps ran into race condition when starting the PKCE flow, as both apps save PKCE meta in localStorage under the same domain (localhost).

**Comment by swiftone** [comment]
@kthomas182 - on further review, I'm afraid there's a fundamental issue with the setup you describe.  OAuth saves information before a redirect and then uses that information after the flow redirects back to the app to ensure the data the app is operating on is coming from the trusted source (and with PKCE, also that the app receiving authorization is the same as the app that requested).  

This information is stored in the client, be that in cookies, localStorage, or sessionStorage.  All of these options are dependent on what browsers consider "origin", and application port is part of the definition.  This means that an app on one port will never be able to read data saved by a different app on a different port.

If your desire is to have a different app receive the authorization than requests it (which we don't generally recommend), those two apps will have to run on the same port (with different url routes, as decided by your backend system).  The alternative we'd recommend would be to have one app perform the entire authorization process, then send the user (with their authorization) to any application relying on that authorization.  How this is best set up for you and your backend is a wide-ranging topic outside the scope of the SDKs - for that I'd steer you towards our support team at developers@okta.com, who can look at your specific use-cases and tailor recommendations based on your backend/frontend systems.

**Comment by kthomas182** [comment]
Thanks @swiftone and @shuowu 

I will try your recommendations.
