### ISSUE TITLE
Why is doesn't this support User Creation?

### ISSUE THREAD

**Issue by garrettmac** [okta/okta-auth-js#621]
Why is @okta/okta-sdk-nodejs required?

**Comment by swiftone** [comment]
@garrettmac - Hope I can help.  This Auth SDK is, per the README: 

> The Okta Auth JavaScript SDK builds on top of our Authentication API and OpenID Connect & OAuth 2.0 API to enable you to create a fully branded sign-in experience using JavaScript.

As such it's all about authentication, not the full range of account and user management options that our okta-sdk offers.  The authorization requirements required to perform those actions are more involve as well.

To cover the various options for account creation, I suggest reaching out to our support team at developers@okta.com.  One option is to use the okta-signin-widget to allow Self Service Registration, which is covered in a guide here: https://developer.okta.com/docs/guides/set-up-self-service-registration/before-you-begin/

**Comment by garrettmac** [comment]
Thanks very helpful thank you explaining, ill go ahead and close @swiftone
