### ISSUE TITLE
Dependecy (Base64.js) license is not enterprise safe 

### ISSUE THREAD

**Issue by onnenon** [okta/okta-auth-js#624]
As stated in #588 the license of the 0.3.0 version of Base64.js is not Enterprise save due to language. The previous issue concluded that it was a non-issue because of the dual license, but upon looking further into the 0.3.0 release, it does not appear to be dual licensed.

[0.3.0 LICENSE](https://github.com/davidchambers/Base64.js/blob/52bd13075d9fdc82035330e5b8c79b05f023e394/LICENSE)

The license change to be a dual license of Apache 2.0 and WTFPL happened about a year and a half after 0.3.0 in this [PR](https://github.com/davidchambers/Base64.js/pull/20).

Looks like the first release using this license is 1.0.0

[1.0.0 LICENSE](https://github.com/davidchambers/Base64.js/blob/a0100ccc2e0945d2b8445b68187de2a17ab2b4d0/LICENSE)

**Comment by aarongranick-okta** [comment]
@onnenon Thank you for bringing this to our attention! We will investigate and follow up. internal ref: OKTA-369733

**Comment by onnenon** [comment]
Thanks for the quick response!

**Comment by swiftone** [comment]
@onnenon, @aklinker1 - We have updated the version of Base64 that we use to 1.1.x, so the Apache License is formally available without potentially offensive language. (https://github.com/okta/okta-auth-js/pull/637) - Note our CI system merges the code but not the PR, so the PR shows as "closed".

This change will roll out with the next minor version of okta-auth-js.

**Comment by onnenon** [comment]
Hey thank you for the update! I'll go ahead and close this Issue, thanks for the help.
