### ISSUE TITLE
Moving from 4.6.2 to 4.7.0 introduce typescript errors in type declarations

### ISSUE THREAD

**Issue by antoine-morvan** [okta/okta-auth-js#626]
Hello, 

While instantiating a fresh typescript project, I noticed the update from 2 days ago to 4.7.0. 

However my usual boilerplate that used to work before now fails with:

```
$ npm run tsc

> fresh-project@1.0.0 tsc
> tsc --outDir target/tsc

node_modules/@okta/okta-auth-js/lib/types/Storage.d.ts:79:5 - error TS2411: Property 'token' of type 'StorageOptions | undefined' is not assignable to string index type 'StorageOptions'.

79     token?: StorageOptions;
       ~~~~~

node_modules/@okta/okta-auth-js/lib/types/Storage.d.ts:80:5 - error TS2411: Property 'transaction' of type 'StorageOptions | undefined' is not assignable to string index type 'StorageOptions'.

80     transaction?: StorageOptions;
       ~~~~~~~~~~~


Found 2 errors.
```

I've been able to reproduce with typescript 3.9.9 and 4.1.5. If I roll back to 4.6.2 the errors do not show up.

Here is a minimal project to reproduce: https://github.com/antoine-morvan/okta-minimal-30dff9

**Comment by aarongranick-okta** [comment]
@antoine-morvan Thanks for the report! We are aware of this issue and there is [a user PR ](https://github.com/okta/okta-auth-js/pull/623)which might fix the issue. We will get this fixed and updated very soon! internal ref: OKTA-369625

**Comment by antoine-morvan** [comment]
4.7.1 fixes the issue :)

**Comment by swiftone** [comment]
Thanks to @javierdp for the PR for this fix!
