### ISSUE TITLE
Unable to fetch openid-configuration from issuer

### ISSUE THREAD

**Issue by langfordG** [okta/okta-auth-js#640]
Hi there,

I am trying to run the Okta-Sample app with my own configuration, but after replacing the 'issuer' and 'client ID' I get the following error:

Access to fetch at 'https ://api.<my_company>.com/v1/qa/.well-known/openid-configuration' from origin 'http ://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

It seems that the Okta SDK is trying to fetch configuration from my issuer, but this cross domain request is causing a CORS error. Is there a way to prevent the SDK from sending 'Access-Control-Allow-Credentials' header along with the request, to resolve the CORS wildcard issue?

Thanks!

**Comment by swiftone** [comment]
@langfordG - thanks for checking in.  This could be a few different issues.

First, have you configured your settings in Okta to send the CORS headers for your domain?  This guide describes the required steps https://developer.okta.com/docs/guides/enable-cors/granting-cors/

Second, are you using a configuration that is type "web" or type "spa"?  We've seen this error in the past when a "web" type application (intended to make all calls from the backend) is used as a "spa" type application (making calls in the browser).  

Third, if those are not the issue, can you look at the Response headers in your browser DevTools for the request?  If there are two, both an OPTIONS and a GET request, check both, and see what value the `Access-Control-Allow-Origin` header has for each.

Hope that helps!

**Comment by swiftone** [comment]
Note: likely similar problem to https://github.com/okta/okta-auth-js/pull/631

**Comment by langfordG** [comment]
Hello! Thanks for the reply.

Currently I'm running from localhost, which is listed as a trusted origin and returns a CORS header. 

I do see that the application is of type 'WEB', so that could certainly be the issue. I will request a change to type 'SPA'.

I also double checked the Response headers in the DevTools, and see two requests to https ://api.<company>.com/v1/qa/api/v1/authn. The OPTIONS request has an 'access-control-allow-origin: *' as a response header, but I don't see the same for the second request. 

If there is an issue even after changing the application to 'spa', will surely reach out, otherwise I think we can close this issue.

Thanks again!

**Comment by aarongranick-okta** [comment]
@langfordG where did this URL come from?  'https ://api.<my_company>.com/v1/qa/.well-known/openid-configuration' This does not match the format of an Okta URL, which would be `https://<your okta org url>/oauth2/<auth server id>/.well-known/openid-configuration`.  Your issuer should follow the format either `https://<your okta org` (for apps which only need to use Okta API). or `https://<your okta org/oauth2/<auth server id>`

**Comment by langfordG** [comment]
@aarongranick-okta @swiftone When I replace this url with https://<org_url>/oauth2/<server_id>, in addition to changing the application from 'web' to 'browser', authentication works fine using PKCE flow with no CORS error. Thanks very much for your support! I will go ahead and close this issue.
