### ISSUE TITLE
tokenManager.setTokens triggers updateAuthState async warning in the console

### ISSUE THREAD

**Issue by salocinhawk** [okta/okta-auth-js#655]
Okta package versions:

- okta/okta-auth-js: 4.7.1
- okta/okta-react: 4.1.0

Hello, I have a single-page-application and am using the okta-react and okta-auth-js packages with an Okta-hosted widget; utilizing the redirect protocol. I have a custom `/callback` component which follows the [token.parseFromUrl()](https://github.com/okta/okta-auth-js/tree/eb7d70d902e1cccf767325dcbe3710d9f2da4be6#tokenparsefromurloptions) example of parsing the tokens from the URL and then using `oktaAuth.tokenManager.setTokens()` to set the Access and ID tokens. I also use the same `setTokens()` function in my custom token refresh component.

Each time my application calls `tokenManager.setTokens()` I receive two duplicate warnings in the console that read as follows:
> [okta-auth-sdk] WARN: updateAuthState is an asynchronous method with no return, please subscribe to the latest authState update with authStateManager.subscribe(handler) method before calling updateAuthState.

I do not encounter any errors, the tokens are parsed from the URL correctly and stored in local-storage, but I don't believe this warning is a true warning. I am not doing anything extra between parsing the tokens from the URL and storing them in the local storage, but it is important that I follow this `parseFromUrl -> setTokens` pattern because I am using those tokens outside the basic Okta login protocols. 

I tried looking for a similar issue online and only found a [github issue](https://github.com/okta/okta-auth-js/issues/584) that suggested to change the `autoRenew` in `tokenManager` to false:
```
tokenManager: {
  autoRenew: false
}
```
However this did not get rid of the duplicate warning for me. I do think that this is an erroneous warning and want to make sure that I am not doing anything to cause it. 

Please look into this and let me know what you find, thank you.

**Comment by shuowu** [comment]
@salocinhawk The warning message basically is to suggest you to listen on the `authStateChange` event, so you can react to the latest authState accordingly when token/authState changes in your app.

Looks like you are using the okta-react SDK, which has implemented the listener internally, you can follow the sample [here](https://github.com/okta/samples-js-react/tree/master/okta-hosted-login) fro okta hosted login.

**Comment by salocinhawk** [comment]
Thank you for the quick reply. By listener, are you referring to the useEffect in `Home.jsx`  that is dependent on `authState` and `oktaAuth` which are derived from the `useOktaAuth()` hook call?

**Comment by shuowu** [comment]
The listener is added in okta-react's Security component. https://github.com/okta/okta-react/blob/master/src/Security.tsx#L59

**Comment by shuowu** [comment]
The LoginCallback component basically is calling `handleLoginRedirect` method from auth-js: https://github.com/okta/okta-auth-js/blob/07b9e89227e8efedfbee2251ef211a680fbef3a3/lib/browser/browser.ts#L520-L553

You probably can customize the logic from there.

**Comment by salocinhawk** [comment]
Thank you for directing me to that piece of code. I was able to customize the logic to my needs and I am no longer seeing the warnings because I have set up the listener correctly. Closing the issue.
