### ISSUE TITLE
signInWithCredentials doest not handle AuthSdkError with try catch

### ISSUE THREAD

**Issue by palaniichukdmytro** [okta/okta-auth-js#658]
During implementation sign in using `signInWithCredentials` I do not see in catch error_code . 

Code example: 

```
const onSubmit = async (data: SignInFromData) => {
    try {
      const response = await oktaAuth.signInWithCredentials({
        username: data.username,
        password: data.password,
      });

      const sessionToken = response?.sessionToken;

      setSessionToken(sessionToken);
      // sessionToken is a one-use token, so make sure this is only called once
      await oktaAuth.signInWithRedirect({
        sessionToken: response?.sessionToken,
        responseType: 'token',
      });
    } catch (error) {
      // signInWithCredentials doest not return response with code requires to handle errors. (error_code)
      notificationsContext?.setNotificationState?.({
        type: NOTIFICATION_TYPES.ERROR,
        description: oktaErrors['E0000004'],
      });
    }
  };
```

In catch error I see

AuthApiError: Authentication failed at ...file path

but in network response on  `POST https://truverisexternal.okta.com/api/v1/authn` there is
`{"errorCode":"E0000004","errorSummary":"Authentication failed","errorLink":"E0000004","errorId":"oaeKyzu0cpcS6OCmvcxHME_rQ","errorCauses":[]}`

Looks like  postToTransaction doest not handle the by AuthApiError. 
Is there a way to retrieve errorCode from signInWithCredentials?

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reaching out @palaniichukdmytro.

I can see `errorCode` [available](https://codesandbox.io/s/infallible-robinson-tf42l) on error instance - does accessing it return unexpected value in your setup?

**Comment by palaniichukdmytro** [comment]
@oleksandrpravosudko-okta looks good for me now , we can close the ticket, I've expected as error_code, cuz on one place we did via axios and expeted result error?.response?.data.

Thanks
