### ISSUE TITLE
handleLoginRedirect should not throw

### ISSUE THREAD

**Issue by darkowic** [okta/okta-auth-js#663]
In our application, we are displaying a nice error screen when a user has no access to the application. Unfortunately, after upgrade okta to v4 instead of the nice error screen, we had a white screen of death.

In the console:
```
Uncaught (in promise) OAuthError: User is not assigned to the client application.
```

After debugging and checking the okta-react reference I found that this is a not handled error from [`handleLoginRedirect`](https://github.com/okta/okta-auth-js#handleloginredirecttokens). I have described the workaround [here](https://github.com/okta/okta-react/issues/77#issuecomment-801096217).

Since the OktaAuth is keeping the state with error and returning the `authState`, I would expect this function to never throw. If this is expected and can not be handled differently - at least we need a note about it in docs or good practices about handling authorization errors.

**Comment by arvindkrishnakumar-okta** [comment]
@shuowu-okta Can you help with this?

**Comment by shuowu** [comment]
@darkowic 
Thanks for reporting the issue! As you found in the `okta-react` repo, we are currently working on a fix to handle the thrown error in okta-react SDK. For this particular method in auth-js, we do still want to throw the error to make it can work even without the authStateManager. We will definitely improve the README to provide better information on the thrown error.

Internal Ref: OKTA-379501

**Comment by darkowic** [comment]
> we do still want to throw the error to make it can work even without the authStateManager. 

how about parameterizing it? ;)

**Comment by shuowu** [comment]
@darkowic Thanks for the suggestions! We will analyze the potential options and make the method more intuitive in the recent releases.

**Comment by oleksandrpravosudko-okta** [comment]
Note added in https://github.com/okta/okta-auth-js/commit/a1818656e81b0100f0b089ecdc6471b832762e72
