### ISSUE TITLE
How do you mock the parseFromUrl method?

### ISSUE THREAD

**Issue by jeffrey-vang** [okta/okta-auth-js#664]
With the new typings in 4.x, `parseFromUrl` is now a property on `OktaAuth`. Please provide some guidance on how to actually mock, using jest, the function on the `parseFromUrlInterface` type.

https://github.com/okta/okta-auth-js/blob/3599bb103318eb6752bd4197b8e3f468cf31cc34/lib/types/api.ts#L145

**Comment by arvindkrishnakumar-okta** [comment]
@shuowu-okta / @aarongranick-okta Can you help with this?

**Comment by aarongranick-okta** [comment]
@jeffrey-vang The method exists under the `token` object: `authClient.token.parseFromUrl`

The method returns a Promise that resolves to a `TokenResponse`. This response will contain tokens (for implicit flow) or a code (for PKCE / authorization code flow)

```
const authClient = new OktaAuth({...config});
const pkceResponse = {
  tokens: {
    idToken: {},
    accessToken: {}
  },
  state: 'fake',
  code: 'fake'
 }

const implicitResponse = {
  tokens: {
    idToken: {},
    accessToken: {}
  },
  state: 'fake',
 }

let tokenResponse = pkceResponse;
jest.spyOn(authClient.token, 'parseFromUrl').mockReturnValue(Promise.resolve(tokenResponse));
```

Hope this helps!

**Comment by jeffrey-vang** [comment]
@andriizhegurov-okta This worked. Thank you for the quick response.
