### ISSUE TITLE
Unable to retrieve groups via getWithPopup

### ISSUE THREAD

**Issue by intmainvoid** [okta/okta-auth-js#668]
I'm attempting to get information on the Okta groups my user is a member of. I've set up the sample application in Okta following [this guide](https://developer.okta.com/docs/guides/customize-tokens-groups-claim/add-groups-claim-org-as/).

I've made sure that the user is a member of two groups in my Okta (Single Page App) application.

My config:

``` Javascript
const oktaAuthClient = new OktaAuth({
  clientId: '0oaatpkMYCLIENTIDd5',
  issuer: 'https://dev-1234567.okta.com/oauth2/default',
  redirectUri: 'http://localhost:8000/implicit/callback',
  responseType: ['id_token token'],
  scopes: ['openid', 'email', 'profile', 'groups'],
  pkce: true,
  tokenManager: {
    autoRenew: false,
  },
});
```

My code:

``` Javascript
oktaAuthClient.token.getWithPopup().then((response) => {
  console.log('Response received');
  console.log('Response: ', response);
}).catch(e => {
  console.error("ERROR: ", e);
});
```

The login is successful and I receive the following response:
``` JSON
{
   "token_type":"Bearer",
   "expires_in":28800,
   "access_token":"<access token>",
   "scope":"openid profile groups email",
   "id_token":"<id token>"
}
```

I then decode the access token and the id token but neither includes any information about the groups of the user I log in with. I'd expect to see a result similar to the result I see [here](https://developer.okta.com/docs/guides/customize-tokens-groups-claim/add-groups-claim-org-as/).

Decoded access token:
```
{
 "ver": 1,
 "jti": "...",
 "iss": "https://dev-1234567.okta.com/oauth2/default",
 "aud": "api://default",
 "iat": 1234567890,
 "exp": 0987654321,
 "cid": "...",
 "uid": "...",
 "scp": [
  "openid",
  "profile",
  "groups",
  "email"
 ],
 "sub": "myemail@mydomain.com"
}
```

Decoded id token:

```
{
 "sub": "...",
 "name": "My Name",
 "email": "myemail@mydomain.com",
 "ver": 1,
 "iss": "https://dev-1234567.okta.com/oauth2/default",
 "aud": "...",
 "iat": 1234567890,
 "exp": 0987654321,
 "jti": "...",
 "amr": [
  "pwd"
 ],
 "idp": "...",
 "nonce": "nEuDo4gu1WHwW8g1VilQE0yyjfGqUxqxFxdwLkNo9luG1yAKj1x8ZSbPoJGKJbhn",
 "preferred_username": "myemail@mydomain.com",
 "auth_time": 1616459569,
 "at_hash": "VzMcYBjAZgM5hAiLRYvItg"
}
```

What am I missing?

**Comment by mraible** [comment]
You need to [Add a `groups` claim to your authorization server](https://developer.okta.com/docs/guides/customize-tokens-groups-claim/add-groups-claim-org-as/). For most developer accounts, this is the "default" server.

**Comment by intmainvoid** [comment]
Thanks @mraible - I have actually already configured this.
![Screen Shot 2021-03-23 at 2 10 58 pm](https://user-images.githubusercontent.com/719151/112087256-b9709e00-8be1-11eb-909f-5955f70e6a78.png)

**Comment by intmainvoid** [comment]
Interestingly, I DO get groups returned in my id token when I do a direct REST request:
```
https://dev-1234567.okta.com/oauth2/v1/authorize?
client_id=<myClientId>&
response_type=id_token&
scope=openid%20groups&
redirect_uri=http%3A%2F%2Flocalhost:8000%2Fimplicit%2Fcallback&state=myState&nonce=myNonceValue
```

Result:
```
{
 "sub": "...",
 "ver": 1,
 "iss": "https://dev-1234567.okta.com",
 "aud": "...",
 "iat": 1234567890,
 "exp": 0987654321,
 "jti": "...",
 "amr": [
  "pwd"
 ],
 "idp": "...",
 "nonce": "myNonceValue",
 "auth_time": 1616564579,
 "groups": [
  "Everyone",
  "MyGroup"
 ]
}
```

What is this library doing differently?

**Comment by intmainvoid** [comment]
Ok, managed to get groups. Here's how:

1. I noticed that the configuration on the authorization server is different to the configuration on the SPA "Open Connect ID Token". Setting the issuer correctly defines whether it will use the group claim settings from the application or the auth server.
1. Once the application or auth server is configured correctly, adding the following code will retrieve the group information for the user:
``` Javascript
await oktaAuthClient.token.getUserInfo(...);
```
