### ISSUE TITLE
Add support for cookie value conversion

### ISSUE THREAD

**Issue by garrettmac** [okta/okta-auth-js#676]
My system is having issues with default encoder for cookies, can you add support for a options value in the config to do the following https://www.npmjs.com/package/js-cookie#converters, i noticed that was a package you use. Or can i open a PR for it?

**Comment by bryanapellanes-okta** [comment]
@garrettmac,
Thanks for reaching out!  Feel free to submit a PR for your proposed change(s).  Our JavaScript developers will review and comment.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
@garrettmac @shuowu-okta @aarongranick-okta I've opened an issue internally for tracking (OKTA-383725); this will go into the backlog for prioritization.

**Comment by aarongranick-okta** [comment]
@garrettmac We do provide the option for a custom storageProvider, which can implement any custom logic: https://github.com/okta/okta-auth-js#storageprovider

**Comment by garrettmac** [comment]
I saw that but was the scope kept getting bigger as i way trying to copy your getCookieStorage with this tweak i then had to start using your storageUtil.storage.get, that you dont export so i had to copy that too in your lib/browser/browserStorage.ts

**Comment by garrettmac** [comment]
I dont need this cookie conversion anymore tho, turns out it the issue wasnt the conversion, its https://github.com/okta/okta-auth-js/blob/236a4a4e54e634a36e004be93a4cda2580198dd2/lib/browser/browserStorage.ts#L161 the cookie size limitations because you're storing the values as objects and that makes cookie sizes too big for the browser. We need the accessToken only as a cookie so im using your events instead to listen for chagnes to the accessToken and stripping the value to set as cookie as another copy

**Comment by garrettmac** [comment]
in that discovery i came across some of the docs needed updating as i dug in your code https://github.com/okta/okta-auth-js/pull/674

**Comment by shuowu** [comment]
Internal Ref (only store encoded token in cookie): OKTA-413942

**Comment by scott-kennedy** [comment]
Adding to this thread. The cookies being stored are too large due to the fact that they contain a bunch of redundant data pulled from the decoded tokens. This has caused issues for multiple applications requiring different application teams to make updates to their apps to allow much larger header sizes than the defaults. Please add support for a way to only store token values inside cookies, we can decode the token on our own.

**Comment by jaredperreault-okta** [comment]
@scott-kennedy as of auth-js v6.0.0 we store the property values of token objects in individual cookies to avoid hitting the cookie size limitation. If you're still hitting size limits, it might mean your tokens themselves are too large for cookies (this can happen if a token contains a large number of claims).

If you'd still prefer to only store the raw token, I believe you can achieve this by writing a custom storageProvider which only writes the raw token value to storage and then decodes the token upon retrieval
