### ISSUE TITLE
Unable to use "Don't repeat MFA for X time" workflow

### ISSUE THREAD

**Issue by SebMarson** [okta/okta-auth-js#687]
We have configured our Okta tenant to only ask users to verify with MFA once a day. Now when you go to log in on the tenant there is a checkbox that a user must tick to say "Do not ask me for MFA again within X time". There doesn't appear to be any way to handle this work flow if you're using this library though. This means users logging in with the library cannot ask for no MFA prompt next time they log in for X time.

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reaching out @SebMarson.

You might be able to use [`rememberDevice`](https://github.com/okta/okta-signin-widget/blob/master/src/models/Factor.js#L263) property when handling sign-in transaction.

**Comment by SebMarson** [comment]
Ah, I spoke to some other Okta engineers and they said it wasn't available. How do I fit in using the rememberDevice property with the .signInWithCredentials work flow?

**Comment by oleksandrpravosudko-okta** [comment]
You could add MFA policy rule at the org level (hxxps://dev-org-admin.okta.com/admin/access/policies#sign-on), but that doesn't seem to have options for requiring MFA within X time - it only allows to remembering per device which is not what you asked about. Apologies for leading you astray.

**Comment by shuowu** [comment]
@SebMarson Closing the issue as it turns out this is an unsupported feature from okta-auths-js SDK. Feel free to re-open it if you have any further questions.
