### ISSUE TITLE
IdToken not getting clear from local storage on session timeout

### ISSUE THREAD

**Issue by ankurmungekar** [okta/okta-auth-js#690]
Hello,
When the browser is idle for more than the expiration time and I make an API call, it clears the accessToken from local storage but does not clear the idToken, and if I make an API call again then it clears idToken from local storage.
I'm using React and Axios.

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
What API calls trigger tokens removal in your case? Token removal/renewal process should be done on timer if auth client is  configurated with `autoRemove: true` or `autoRenew: true` (be default).
What config values of `autoRemove` and `autoRenew` are you using?
Do you use latest version of okta-auth-js?

**Comment by ankurmungekar** [comment]
oktaAuth.tokenManager.clear(); 
Triggers tokens removal.

**Comment by ankurmungekar** [comment]
I'm using 3.1.0 version

**Comment by aarongranick-okta** [comment]
@ankurmungekar Are you able to upgrade to a newer version of `okta-auth-js`?

**Comment by aarongranick-okta** [comment]
@ankurmungekar We are no longer supporting the 3.x version. We recommend upgrading to the latest version which has all fixes and features. Token auto renew happens automatically in the background and by default all tokens will be cleared on failure.  If you have any problems with the latest version, please open a new issue here on Github. Thanks for using Okta!
