### ISSUE TITLE
Error logging in with PKCE in automated test environment

### ISSUE THREAD

**Issue by langfordG** [okta/okta-auth-js#701]
Hello,

I'm trying to login with the PKCE flow to my application using an automated test script (via TestCafe). As this test is running in a simulated browser, it shows the following error: 
![image](https://user-images.githubusercontent.com/11727106/115584084-57a66100-a27f-11eb-8c7f-bcdba6f65d39.png)

I was hoping to see if OktaJS supports signing in with PKCE within a simulated browser, or if there is a suggested workaround?

Thanks,
Grayson

**Comment by bretterer** [comment]
Hi @langfordG!  Could you please let us know what the simulated browser environment is so we can help guide this?

**Comment by bretterer** [comment]
A little more detail here.  The way we determine if a browser supports PKCE, we check for `webcrypto` and `TextEncoder`.  Can you confirm both of these are available in your browser?

**Comment by langfordG** [comment]
> Hi @langfordG! Could you please let us know what the simulated browser environment is so we can help guide this?

Hi there! This test was run on Chrome: 'testcafe chrome:headless src/e2e'. I just tried on Safari and there it actually is working. Interesting!

**Comment by langfordG** [comment]
It looks like this also occurs in Firefox. I believe Chrome and Firefox support webcryto and TextEncoder, as PKCE login works in a regular (non-simulated) window. Is there a way of enabling PKCE in these browsers, for simulated browsers as well?

**Comment by oleksandrpravosudko-okta** [comment]
Hi @langfordG - is there a chance tests are run against a site served in a non-secure context? (i.e. invalid or expired cert)
In such case [Crypto.subtle](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) module won't be available for PKCE.

**Comment by langfordG** [comment]
> Hi @langfordG - is there a chance tests are run against a site served in a non-secure context? (i.e. invalid or expired cert)
> In such case [Crypto.subtle](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle) module won't be available for PKCE.

It looks like the site we are testing has a valid https certificate. We are using okta-auth-js version 4.7.1 and okta-react version 4.1.0. Is logging with PKCE inside of an automated test environment is supported by these versions?

![image](https://user-images.githubusercontent.com/11727106/115905144-899ffa80-a41a-11eb-8046-f872e5b89b4b.png)

**Comment by oleksandrpravosudko-okta** [comment]
There seem to have been no issues discovered on PKCE + automated test environment setup (e.g. there is a PKCE [test](https://github.com/okta/okta-auth-js/blob/master/test/karma/spec/pkce.js#L7) that runs in a ChromeHeadless).

Would you be able to output the results of PKCE availability checks[[1]](https://github.com/okta/okta-auth-js/blob/9831eb1362dc4674071bc0aa8fe058b9339a18f3/lib/features.ts#L51)[[2]](https://github.com/okta/okta-auth-js/blob/9831eb1362dc4674071bc0aa8fe058b9339a18f3/lib/features.ts#L55) in testing environment?

**Comment by langfordG** [comment]
Sure thing! Here is the error we're seeing when trying to login with Chrome in TestCafe. Is this the correct output?
<img width="642" alt="Screen Shot 2021-04-28 at 4 30 05 PM" src="https://user-images.githubusercontent.com/11727106/116485163-62dd2c00-a83f-11eb-94cb-11b29a76e97d.png">

**Comment by oleksandrpravosudko-okta** [comment]
Thanks - I was hoping to pinpoint the exact missing module by invoking them in the automated browser console when test execution is paused.
From the latest screenshot it looks like tests are running against an app hosted at/proxied to `http://192.168.0.6` - please note that it is not considered a secure context and Crypto module is not available in such case.
