### ISSUE TITLE
Session cookie call on Safari

### ISSUE THREAD

**Issue by NicholasGWK** [okta/okta-auth-js#71]
Hello, great library! I've got it setup to use the Session based OIDC flow with Silent refresh. It's working great on all browsers but safari...the initial getWithoutPrompt call to exchange the sessionToken for a session icookie is not correctly setting a session cookie from our okta instance, presumably because of Safari's restrictive iframe/cookie policies. The tokens are returned properly as expected.

Just wondering if there's a workaround for this or any additional insight!

Thanks,

Nick

**Comment by lboyette-okta** [comment]
@NicholasGWK @Cezarion - Safari's third-party cookie policy prevents third-party storage (like Okta's cookie/localStorage) [unless the browser has redirected through it in the last 24 hours](https://webkit.org/blog/7675/intelligent-tracking-prevention/).

That means there are two options:
1) Ask your customers to enable third-party cookies in Safari
2) Use the redirect sign-in flow. You'll still be able to refresh silently.

**Comment by Cezarion** [comment]
@lboyette-okta Thank's for your response. 
Using Okta OAuth and the OpenId settings of the signin widget can they be a functional alternative?

**Comment by lboyette-okta** [comment]
@Cezarion Unfortunately not, the widget uses `okta-auth-js` under the hood, so any limitations of `okta-auth-js` also apply to widget
