### ISSUE TITLE
Token is autorenewed for Chrome 90 stable but no for Chrome 91 beta

### ISSUE THREAD

**Issue by makbol** [okta/okta-auth-js#723]
Hello!

I run into issue and after a lot of debugging i come to conclusion that for some reason, token is automatically renewed for Chrome 90.0.4430.93 stable channel but it's not auto renewed for Chrome 91.0.4472.27 beta channel and 92.0.4496.0 canary channel. 

I set token lifetime to 5 minutes in access policies rules, executing on localhost. Having code:

```javascript
authClient.tokenManager.get('accessToken')
  .then(accessToken => {
      if(!accessToken) {
          return Promise.reject();
      }
  
      const hasExpired = authClient.tokenManager.hasExpired(accessToken);
      return hasExpired ? Promise.reject() : Promise.resolve();
  });
```

For Chrome beta and Chrome canary as `accessToken` I'm getting `undefined` when `removed` event has been dispatched (after `window.location.reload()`) while the same code in Chrome stable I'm getting token data (`expiresAt`, `accessToken`, `claims` etc).
I tried to add `tokenManager: { autoRenew: false }` to configuration and it seems made behaviour identical.

I don't understand why there's a difference in behaviour for different Chrome versions. Do you somehow detect version and based on that assign certain configuration?

**Comment by oleksandrpravosudko-okta** [comment]
Hi @makbol,

Token auto-renewal seems to be working as expected under `Chrome 91.0.4472.27 (Official Build) beta (x86_64)`. I used our [sample app](https://github.com/okta/okta-auth-js/tree/master/test/app) to verify it. Please note that in v5 it is required to invoke [`start`](https://github.com/okta/okta-auth-js#running-as-a-service) method on the SDK instance to enable tokens autorenew.

**Comment by shuowu** [comment]
@makbol Can you try the suggestion @oleksandrpravosudko-okta provided above? Feel free to reopen the issue if the suggestion does not work for you.
