### ISSUE TITLE
React-Native support? 

### ISSUE THREAD

**Issue by farshidbakh** [okta/okta-auth-js#73]
Hello All,
Does this package support React-Native apps? I have installed the package using the "npm install" but when I try to run it I get the following message "Document is not defined". See the image below.

I wold greatly appreciate your response.
Thanks,
Farshid 

![screen shot 2017-11-15 at 1 41 08 pm](https://user-images.githubusercontent.com/22581604/32853948-fdc1501e-ca0a-11e7-9745-48c74521b1d4.png)

**Comment by lboyette-okta** [comment]
React Native isn't currently supported. Are you using `okta-auth-js` for OpenID Connect or the [Okta Authentication API](https://developer.okta.com/docs/api/resources/authn.html) flows?

**Comment by asharafshahi** [comment]
I'm curious about this as well.  I've been looking for a solution for signup/auth for a react native app that doesn't involve redirecting the user to a 3rd party webpage.  What approach does Okta recommend?

**Comment by farshidbakh** [comment]
Thanks for your response. I am looking to use it as Authentication and hopefully authorization as well.

**Comment by mraible** [comment]
I wrote an article for scotch.io that shows how to authenticate with Okta using React Native: https://scotch.io/tutorials/build-a-react-native-app-and-authenticate-with-oauth-20

**Comment by jmelberg-okta** [comment]
We currently do not have plans to support React Native with **this library**.

Instead, please checkout the new [`@okta/okta-react-native`](https://www.npmjs.com/package/@okta/okta-react-native) integration for OpenID Connect authentication flows.
