### ISSUE TITLE
okta-cache-storage saves failed call to .well-known, causing login failures until manually cleared.

### ISSUE THREAD

**Issue by esodell** [okta/okta-auth-js#737]
Users will enter credentials into an application hosted login page (using Okta sign-in widget) and the followup code after the login is never called, the application just stops in the browser. This is intermittent, not readily reproducible (as far as I can tell), and does not affect all users. It can, however, affect both users with an MFA step and users without one. From what I can tell, the issue is directly related to the call to https://<OKTA ORG>/oauth2/<AUTH SERVER>/.well-known/openid-configuration 

When the issue happens, the contents of this call is always an error, with the error summary "Could not parse server response". 
Refreshing, including emptying cache and hard reload does not remedy the issue, only clearing the local storage fixes it, as it must be forced to reacquire this cached data, and doing this has always fixed the issue thus far.

Ideally, the failed calls returning an error should not be stored, which would force the browser to reacquire this data and have a successful login.

Support case reference 01105646

![image-20210503-125004](https://user-images.githubusercontent.com/37704833/118160130-c3896e80-b3d2-11eb-8131-369d3e423a10.png)

**Comment by bryanapellanes-okta** [comment]
@esodell,
Thanks for reaching out!  I'll bring this to the attention of our JavaScript developers and someone will comment here with more.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
Internal Ref: OKTA-395479

**Comment by shuowu** [comment]
@esodell Please try v5.3.1, it should only cache successful response.
