### ISSUE TITLE
[PKCE SPA] Expired refresh token in local storage results in an inconsistent application state

### ISSUE THREAD

**Issue by priyath** [okta/okta-auth-js#738]
The issue can be recreated on the [okta-hosted-login sample](https://github.com/okta/samples-js-react/tree/master/okta-hosted-login) as follows:

Setup:

- okta-hosted-login sample with early access feature Refresh Token Rotation enabled on okta authorization server
- Requested scopes: ['openid', 'profile', 'email', 'offline_access']
- @okta/okta-auth-js version 4.9.0 and @okta/okta-react version 5.1.1
- Start the application, perform login then close the application tab until the refresh token has expired. (For debugging I configured the refresh token expiration time to 6 minutes on okta server)

Observations:

Reload the application once the refresh token expiration time has exceeded. The request to  `oauth2/{id}/v1/token`  will fail with the following error:

```
{"error":"invalid_grant","error_description":"The refresh token is invalid or expired."}
```

After this, I expected the user to be directed back to the login page. However, this does not happen. Instead, the user is unable to access any secure routes (accessing any secure routes will result in the above API error) but remains logged into the application. The only option at this point is to clear `localStorage`, which would direct the user over to the okta hosted login page.

When I inspected `authState` the following was observed:

```
accessToken: null
idToken: {value: …}
refreshToken: {value:...}
isPending: true
isAuthenticated: false
```

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report and detailed repro steps, @priyath.

It looks like expired refresh token error is not handled by renew code - I have created a [PR](https://github.com/okta/okta-auth-js/pull/739) to address that.

**Comment by aarongranick-okta** [comment]
@priyath we have prioritized this bug and will work to release a new version with a fix next week. Thanks again for bringing this issue to our attention.

**Comment by aarongranick-okta** [comment]
This issue has been corrected in `okta-auth-js` version 5.2.0.

**Comment by priyath** [comment]
Thanks for addressing this!

**Comment by AliHENDA** [comment]
Hi, I use the version 4.9.2, and okta-vue 3.0 since my SPA is under Vue2. It seems that version 5.2 is not compatible with my version of okta-vue.
If I revert to version 4.1.2 of okta-auth-js, is the problem will be still here?
