### ISSUE TITLE
Token not revoked when used via the Widget following built in Reset Password feature

### ISSUE THREAD

**Issue by staffordp** [okta/okta-auth-js#748]
Okta version: 5.0.1

The revoke is not working when using the okta widget when a user uses the built-in reset password feature from the Okta widget provided by Okta.   Once the password is reset, it takes the user to a dashboard where they can launch the application (again dashboard provided by Okta) and the user authenticates in with this token.  I see the token is stored in the cookie storage and when I do an introspect on this cookie, it shows as active.  Yet when I log out of the app which, in turn, revokes the token, an introspect call shows the token as active still. Is this a known limitation of the library or is this supposed to work?

Code for revoke token:

```
  async signOut() {
      await this.authClient.revokeAccessToken();
      await this.authClient.closeSession()
      .then(() => {
      })
      .catch(e => {
        if (e.xhr && e.xhr.status === 429) {
          console.error('Too many requests.');
        }
      });
  }
```

**Comment by laura-rodriguez** [comment]
Hi @staffordp,

This seems to be related to #747. Can you use an older version for now until our JS devs submit a fix?

**Comment by staffordp** [comment]
@laura-rodriguez Which version do you suggest?  We had been using 4.6.1 and that didn't work either.

**Comment by staffordp** [comment]
Tried 4.9.0. Does not work either.  The only difference I see in the introspect of these users is the scope field.

For these users, introspect comes back with:

    "scope": "email openid",

whereas other users that do not use this flow (where the revoke works) have a scope of the following when an introspect is done on their active token:

    "scope": "profile openid email",

**Comment by shuowu** [comment]
@staffordp Can you share any detail about how the tokens is stored? Issue may happen if multiple OktaAuth instances has been created, but one use custom storage (cookie) for storage, but the other one use the default storage ('sessionStorage') for revoke.

**Comment by staffordp** [comment]
We use the .sessionStorage option when setting the okta config.

**Comment by shuowu** [comment]
Then why the tokens end up in the cookies? Can you share your storage related widget config and the oktaAuth config (if you create another authClient instance)?

**Comment by shuowu** [comment]
@staffordp also, what browser are you using? token storage may fallback to cookies if neither sessionstroage nor localStorage is available. Just want to check if it's the case.

**Comment by staffordp** [comment]
@shuowu Using Chrome 
Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by staffordp** [comment]
Is there any update or workaround for this issue?

**Comment by staffordp** [comment]
Discovered why the revoke was failing. During the getWithoutPrompt which is used for the tile Login, the tokens received were not being grabbed by the tokenManager.  Adding this bit of code fixed the issue:
``
          this.authSvc.authClient.tokenManager.setTokens(
            {accessToken: tokenOrTokens.tokens.idToken,
              idToken: tokenOrTokens.tokens.accessToken}
          );
``
