### ISSUE TITLE
Unable to pass a custom query parameter to IdP authorize endpoint

### ISSUE THREAD

**Issue by richie5um** [okta/okta-auth-js#757]
I'm using Okta for local users, and AzureAdB2C for my custom IdP integrations.

I've configured Okta to have my own Okta app, and also a AzureAdB2C IdP app - which connects to my AzureAdB2C account. In the Okta SignIn widget, the user can either enter their credentials directly (to use Okta local users) or click the 'SSO' button to then use AzureB2C to federate the auth to their specific IdP connection (as configured in AzureAdB2C).

The challenge I have is that I want to be able to pass a runtime 'domain_hint' query parameter to the AzureAdB2C /authorize call so that I can pre-select the IdP for the user that is trying to login.

The Okta IdP discovery is great for selecting my AzureAdB2C IdP (configured in Okta), but I can't figure out how (or if) I can also pass that query param, as the redirect to {AzureAdB2C}/authorize comes from Okta servers itself.

Hopefully this page makes it clearer, I want to add an additional parameter to the 302 - Idp Authorize endpoint, as seen here: 
https://developer.okta.com/docs/concepts/social-login/ 

Is this possible?!

[ I know it sounds like a _sub-optimal_ setup, but I've been tasked with combining two auth platforms without any change on the existing AzureAdB2C IdP configurations. ]

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref: OKTA-398264

**Comment by shuowu** [comment]
@vellala2000 It's supported since [v5.9](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.9.0), you can use the latest version and add custom param in `extraParams` field. See test example [here](https://github.com/okta/okta-auth-js/pull/1004/files#diff-53fd7b93850671c87da2f49dfe42226c9e8229c5fb280eeddab5e0ca2575ddffR66).

**Comment by vellala2000** [comment]
Thank you @shuowu !!
