### ISSUE TITLE
getIdToken not a function in jest test

### ISSUE THREAD

**Issue by jchabotamica** [okta/okta-auth-js#769]
We have jest tests that the dependent code does pull in the OktaAuth.  When instantiating 'new OktaAuth(oktaConfig)', the object returned does not include any of the getters such as getIdToken().
Is there specific logic to not set these when the NODE_ENV is not "development" or "production"?

**Comment by bryanapellanes-okta** [comment]
@jchabotamica,
Thanks for reaching out!  I'll notify our Javascript developers and someone will respond here.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
Internal Ref: OKTA-399609

**Comment by shuowu-okta** [comment]
@jchabotamica Which version of okta-auth-js are you testing in your app? Before 5.x, the server side oktaAuth instance (picked by jest by default) does not include `getIdToken`. We have made the OktaAuth class isomorphic since version 5.

If you need to stay with other versions, you can add the following config in your jest.config file.
```
"moduleNameMapper": {
    "^@okta/okta-auth-js$": "<rootDir>/node_modules/@okta/okta-auth-js/dist/okta-auth-js.min.js"
  }
```

**Comment by jchabotamica** [comment]
@shuowu we are using okta-auth-js 4.9.0.  We hope to be upgrading to 5.x soon but right now our jest tests are blocked.
When trying your suggestion, we get a different error:
    TypeError: _oktaAuthJs.OktaAuth is not a constructor

**Comment by shuowu** [comment]
@jchabotamica Does the jest config in the previous comment help?

**Comment by jchabotamica** [comment]
@shuowu I get this error when trying that suggestion in jest config:

TypeError: _oktaAuthJs.OktaAuth is not a constructor

It's on this line of code:
new OktaAuth(oktaConfig));

Not sure why that wouldn't work however - since this functionality works outside the context of jest tests.

**Comment by shuowu** [comment]
Wondering how did you imported the module in test?

**Comment by jchabotamica** [comment]
in the file its failing: 
![image](https://user-images.githubusercontent.com/52013619/120518927-16d25980-c3a0-11eb-96ea-5819d77e0d97.png)

**Comment by shuowu** [comment]
looks like you are using commonjs module, probably try `var oktaAuth = require('@okta/okta-auth-js').OktaAuth`;

**Comment by jchabotamica** [comment]
hmmm not sure I follow.  We use ES6/TypeScript.  And this functionality works in our app itself.  Just not when executed from a jest test.  The jest test doesn't include the new OktaAuth(oktaConfig).  The jest tests cover components which rely on the okta client being instantiated.

**Comment by jchabotamica** [comment]
@shuowu switching it from the .min.js file to the .umd.js in the moduleNameMapper seems to have helped us make progress.  I'll keep you updated if we run into more issues.  Thanks for your help!

**Comment by jchabotamica** [comment]
For reference, I got this idea from: https://github.com/okta/samples-js-react/pull/149
