### ISSUE TITLE
Setting oauthOptions on request has no effect

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-auth-js#77]
If you pass pass OAuth options (such as `authorizeUri` or `issuer`) to [getWithoutPrompt](https://github.com/okta/okta-auth-js/blob/master/lib/token.js#L502), they are ignored.

The reason is the underlying `getOAuthUrls` method only looks at the third `options` parameter for those options. See: https://github.com/okta/okta-auth-js/blob/master/lib/oauthUtil.js#L128-L134

I'm not sure if this is by-design or a bug, but it confused me.

**Comment by tkirk-okta** [comment]
@nbarbettini This seems to be a bug according to [https://github.com/okta/okta-auth-js#openid-connect-options](url)

> These configuration options can be included when instantiating Okta Auth JS (new OktaAuth(config)) or in token.getWithoutPrompt, token.getWithPopup, or token.getWithRedirect. If included in both, the value passed in the method takes priority.

**Comment by robertjd** [comment]
This appears to have been addressed in #214
