### ISSUE TITLE
AuthSdkError: Passed in oktaAuth is not compatible with the SDK, okta-auth-js version 4.x is the current supported version.

### ISSUE THREAD

**Issue by salimakhtar92** [okta/okta-auth-js#787]
Using following version

Okta version
"@okta/okta-auth-js": "^5.0.2",
    "@okta/okta-react": "^5.1.2",
    "@okta/okta-signin-widget": "^5.7.0",

React Version
"react": "^16.12.0",

and node version
node:10.13.0

AuthSdkError: Passed in oktaAuth is not compatible with the SDK, okta-auth-js version 4.x is the current supported version.

**Comment by mraible** [comment]
Can you please try using "@okta/okta-auth-js": "^4.9.2"?

**Comment by shuowu** [comment]
@salimakhtar92 okta-react version 6.0 which works with okta-auth-js v5 has been released. See [Migrating guide](https://github.com/okta/okta-react#migrating-from-5x-to-6x) for more information.

Close this issue, please feel free to reopen it if you have further questions.
