### ISSUE TITLE
Hoping to get some clarity on the auto refresh of the access token

### ISSUE THREAD

**Issue by GlennDOrr** [okta/okta-auth-js#80]
It looks like the access token is refreshed forever if the browser is left open. That seems like a security concern. Would it be possible to wire something up so that it's only refreshed if there is activity? Maybe a call back function that can be supplied and if called within the refresh time-period, it's refreshed, otherwise it allows it to expire.

**Comment by lboyette-okta** [comment]
It's refreshed as long as the Okta session cookie is valid. The duration of the session is configurable in your admin console, so the level of security is up to you.

If you want to terminate the Okta session before it expires, call [`authClient.signOut()`](https://github.com/okta/okta-auth-js#signout), then remove the token with [`authClient.tokenManager.remove('tokenName')`](https://github.com/okta/okta-auth-js#tokenmanagerremovekey).

Does that help?

**Comment by GlennDOrr** [comment]
Yes, thank you.

**Comment by thm-design** [comment]
@GlennDOrr will calling `authClient.tokenManager.clear()` cause any issues? I have been having some weird redirect issues and just saw I was calling

`authClient.tokenManager.clear()` first then `authClient.signOut()`. Does `authClient.signOut()` not take care of cleaning up everything? Or is calling `authClient.tokenManager.remove('tokenName').` Necessary? And which token key name should be cleared `accessToken ` ? `idToken` ?
