### ISSUE TITLE
tsd package problematic in serverless projects

### ISSUE THREAD

**Issue by micheleangioni** [okta/okta-auth-js#819]
Dear team,
I've noticed that fairly recently this application included `tsd` into the dependencies of the project.

This has terrible consequences for our projects, because we use it in some AWS lambdas. As you probably know, the lambdas [have size limits](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html) of the code they can contain. This includes the `node_modules` folder of course.

The problem is that `tsd` has an enormous size

<img width="260" alt="image" src="https://user-images.githubusercontent.com/7933034/121515758-d56c2a80-c9ed-11eb-8601-ec22b008b069.png">

and creates big problems when trying to deploy our lambdas in AWS, forcing us to use unpleasant workarounds.

Moving `tsd` to the `devDependencies` would already fix the problem, as it would be dropped when packaging the lambdas. If not possible, I really invite you to consider using a lighter alternative.

Thanks

**Comment by denysoblohin-okta** [comment]
Thanks for submitting this issue.
Internal ref: https://oktainc.atlassian.net/browse/OKTA-403207

**Comment by shuowu** [comment]
@micheleangioni Thanks for reporting the issue! The `tsd` module is used only for type testing, and it should belong to the `devDependencies`. Just wondering which version of okta-auth-js are you using, then we can release a patch for it.

**Comment by micheleangioni** [comment]
Hi @shuowu ,
thanks for the very fast answer :) 

We include in our package.json the version 2.1.0 of `@okta/jwt-verifier`

![image](https://user-images.githubusercontent.com/7933034/121526123-64cb0b00-c9f9-11eb-8e1c-96465c36080c.png)

It then brings this chain of dependencies:

<img width="605" alt="image" src="https://user-images.githubusercontent.com/7933034/121526186-70b6cd00-c9f9-11eb-8d04-8fc2b579b419.png">

**Comment by shuowu** [comment]
@micheleangioni @okta/jwt-verifier v2.2.0 which removed the dependency of `@okta/configuration-valiadation` has been released on npm. It should also resolves the `tsd` issue for your case.

Meanwhile, we are also working on move tsd to devDependencies in okta-auth-js. PR can be tracked #839

**Comment by micheleangioni** [comment]
Thank you very much @shuowu :)
