### ISSUE TITLE
How to redirect from backend authentication

### ISSUE THREAD

**Issue by flabbyThoroughbred** [okta/okta-auth-js#822]
Hi,

I'm using Django to authenticate on the backend as I use a client secret. 
I've written a custom callback that calls to Django to authenticate and then posts back something like:
`          <Security oktaAuth={this.oktaAuth} restoreOriginalUri={this.restoreOriginalUri}>`
`            <Switch>`
`              <Route exact path="/" component={NewLogin} />`
`              <Route exact path="/oidc/callback" component={CustomCallback} />`
`              <SecureRoute exact path="/home" component={Home} />`
`            </Switch>`
`        </Security>`

Where **CustomCallback** calls to the Django REST API to do the authentication and then POSTs back with the id/access token.
I tried using **otkaAuth.handleLoginRedirect** and pass in the id/access token except I'm getting a 
`assignment to undeclared variable tokens` 
error.

Firstly, does passing tokens as an argument take precedence over tokens in the URL (I do not have any in the URL).
Second, how must the token arguments be formatted to work?
Beyond this, do I need to manually update the authState values or is this handled in handleLoginRedirect.

Most importantly, am I making this way too difficult on myself or is there an easier way to go about this (or is this an awful idea and should I be doing something else instead)?

Thanks!

**Comment by shuowu** [comment]
@flabbyThoroughbred Looks like you have a React (SPA) app as frontend and a Django server as backend resource server. Then the SPA app acquires tokens via the oidc flow, then POST with access token to get access to protected resources on your backend.

If my understanding is correct, you can follow the [express resource server sample](https://github.com/okta/samples-nodejs-express-4/tree/master/resource-server) to validate the accessToken from the request header. IFAIK, there is no Python(Django) related sample available right now, but they basically follow the same validation approach, hopefully the sample can help.

For the frontend sample, you can find it [here](https://github.com/okta/samples-js-react).

**Comment by shuowu** [comment]
@flabbyThoroughbred  Closing the issue, feel free to re-open it if you still have further questions.
