### ISSUE TITLE
Is there a way to skip OIDC

### ISSUE THREAD

**Issue by said-saifi** [okta/okta-auth-js#827]
### Question

Is there a way to skip `OIDC` by not sending `openid` scope? Or is there any reason why `OIDC` can't be ignored if we wish to.

For some reason (long story) I'm trying to not send any scopes and have the Okta Authorization server return the default custom scopes that I've predefined in Okta for the user using access policy rules. Okta does not allow us to set any of the base scopes including `openid` as default scopes. So there is no way to have Okta return the default scopes and `openid` scope in one request.

When not using `openid` scope it means we are skipping `OIDC` so `id_token` will not be generated and only `access_token` will, which IMO should be fine if we don't care about the use profile at client level and we just need to forward the `access_token` to the Backend APIs. But when trying some sample libraries what is happening in this scenario is an endless redirection (one page redirects to another infinitely).

The sample I have tried is the [react okta hosted login](https://github.com/okta/samples-js-react/tree/master/okta-hosted-login) which is importing this library. The issue happens when accessing any of the secure routes such as `/messages`

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for the question @said-saifi.

You could try using [`transformAuthState`](https://github.com/okta/okta-auth-js#transformauthstate) to define `isAuthenticated` value using accessToken only:

```javascript
transformAuthState: (_, authState) => {
  authState.isAuthenticated = !!authState.accessToken;
  return authState;
}
```

**Comment by said-saifi** [comment]
@oleksandrpravosudko-okta Perfect, thank you.
