### ISSUE TITLE
Bundle size increase from v4 to v5

### ISSUE THREAD

**Issue by hboylan** [okta/okta-auth-js#830]
We noticed a massive increase in bundle size when upgrading from v4 to v5. This module is already a massive portion of our overall app, but not it's more than 2x than before.

You can see the difference here using [RelativeCI](https://app.relative-ci.com/).
![Screen Shot 2021-06-18 at 9 40 44 AM](https://user-images.githubusercontent.com/2158740/122578196-42e51000-d019-11eb-8aa5-4b3a235b3151.png)

**Comment by shuowu** [comment]
@hboylan Thanks for reporting the issue! We actually noticed the issue and are working on a fix for it.

Internal Ref: OKTA-396841

**Comment by hboylan** [comment]
Oh, awesome! Thanks for the update.

Maybe just some dependencies getting bundled by accident.

**Comment by shuowu** [comment]
@hboylan Please try version 5.2.0, it should provide a smaller bundle size. You can find update details [here](https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#520). In the future, we will keep investigating on other options to reduce the bundle size. 

Close this issue, please feel free to reopen or create a new issue if you still experience bundle size related issue.

**Comment by hboylan** [comment]
v5.2.0 certainly helps, but it's still 150% larger than v4.9.0 which we currently use in production. That would nearly double the entire bundle size for our app. 😬 

![Screen Shot 2021-06-30 at 3 44 06 PM](https://user-images.githubusercontent.com/2158740/124028790-04a50480-d9ba-11eb-85b5-972b7992ceca.png)
