### ISSUE TITLE
npm i doesn't install all required packages and fails Jest testing

### ISSUE THREAD

**Issue by mtruong09** [okta/okta-auth-js#834]
On version 5.1.1, after running `npm i`, the required modules are not included in the okta-idx-js folder. Our jest tests fail because it cannot find the module 'core-js/modules/es.string.replace.js'. We are using Jest 26.2.2

![image](https://user-images.githubusercontent.com/3227839/123123766-195f2680-d415-11eb-9515-dcfb1e0fa556.png)

Our current workaround is to run `npm i` in the node_modules\@okta\okta-idx-js folder, and then all tests pass.

**Comment by shuowu** [comment]
@mtruong09 Thanks for reporting the issue! 

Internal Ref: OKTA-406794

**Comment by shuowu** [comment]
Resolved in version 5.2.0. https://github.com/okta/okta-auth-js/blob/master/CHANGELOG.md#520
