### ISSUE TITLE
Refresh tokens are not being set properly in session storage

### ISSUE THREAD

**Issue by raspy8766** [okta/okta-auth-js#836]
## Problem
Okta Auth JS is not properly setting the refresh token to session storage. This seems to only be a problem when refresh token rotation is turned on.

## Details
During the initial authorization code flow the refresh token gets set properly for example:

```javascript
{ 
  accessToken: { accessToken: 123.456.789 },
  idToken: { idToken: 456.789.123 },
  refreshToken: { refreshToken: 789.123.456 }
}
```

During the first token renew call however, the api call successfully returns tokens, but `okta-auth-js` is improperly setting them to session storage (note `refreshToken` is now set to `accessToken`):

```javascript
{ 
  accessToken: { accessToken: 123.456.789 },
  idToken: { idToken: 456.789.123 },
  refreshToken: { accessToken: 789.123.456 }
}
```

This causes the `okta-auth-js` to use the fallback `getWithoutPrompt` which is using the `authorization_code` grant flow and also requires 3rd party cookies.

## Solution
Modify the logic in the [`renewToken`](https://github.com/okta/okta-auth-js/blob/master/lib/TokenManager.ts#L370) function to also handle refresh tokens:
### Before
```javascript
return isIDToken(token) ? freshTokens.idToken : freshTokens.accessToken;
```

### After
```javascript
const { idToken, accessToken, refreshToken } = freshTokens;
return idToken || accessToken || refreshToken;
```

**Comment by shuowu** [comment]
@raspy8766 Thanks for reporting the issue! There is actually a PR (#832) in progress to resolve this issue.

**Comment by shuowu-okta** [comment]
@raspy8766 This issue is handled in recent patches, can you verify with the latest version of okta-auth-js (5.2.3)? Closing this issue, feel free to re-open it if the issue still exist.
