### ISSUE TITLE
Angular SDK doesn't work with Ionic because of Router dependency

### ISSUE THREAD

**Issue by mraible** [okta/okta-auth-js#84]
Ionic uses a `NavController` instead of Angular Router. Attached is the error that happens when you try to use Okta's Angular SDK in an Ionic project.

![Okta Angular SDK Error](https://user-images.githubusercontent.com/17892/34996021-838dce60-fa95-11e7-85d5-c78d327db1ae.png)

**Comment by lboyette-okta** [comment]
Hey Matt, I think you intended to file this in `okta/okta-oidc-js`, so I filed the issue there instead.

**Comment by mraible** [comment]
Thanks for moving it @lboyette-okta!
