### ISSUE TITLE
Min version of the library uses the 'class' keyword which cannot be polyfilled

### ISSUE THREAD

**Issue by meh-uk** [okta/okta-auth-js#841]
The 5.1.1 version of the library uses the class keyword in the minified version which cannot be polyfilled for IE, can we remove this so IE can be supported?

**Comment by meh-uk** [comment]
The 5.1.1 version of the library uses the class keyword in the minified version which cannot be polyfilled for IE, can we remove this so IE can be supported?

**Comment by arvindkrishnakumar-okta** [comment]
@meh-uk Thanks for posting!

@aarongranick-okta @shuowu-okta can you assist with this?

**Comment by aarongranick-okta** [comment]
@meh-uk thanks for the report. We have confirmed the problem and created an internal ref: OKTA-408169
We will get this fixed ASAP

**Comment by meh-uk** [comment]
Thanks!

**Comment by shuowu** [comment]
@meh-uk The issue is fixed and released in version 5.2.2. Closing the issue, feel free to re-open it if the issue still exists.
