### ISSUE TITLE
auto renew fails

### ISSUE THREAD

**Issue by jeffg-hpe** [okta/okta-auth-js#842]
Using an oidc app with refresh tokens and refresh token rotation enabled, and using the `master` branch, I am getting this error on autorenew:

```
AuthSdkError: Renew must be passed a token with an array of scopes and an accessToken or idToken
    at wn (okta-auth-js.umd.js:811)
    at okta-auth-js.umd.js:811
    at c (okta-auth-js.umd.js:13)
    at Generator._invoke (okta-auth-js.umd.js:13)
    at Generator.next (okta-auth-js.umd.js:13)
    at okta-auth-js.umd.js:799
    at new Promise (<anonymous>)
    at xn (okta-auth-js.umd.js:799)
    at Sn (okta-auth-js.umd.js:811)
    at e.value (okta-auth-js.umd.js:918)
```

I am looking into it to see if I can provide more details.

EDIT: I can confirm the values passed during token autorenew at this function https://github.com/okta/okta-auth-js/blob/e39e66db2e24df1e1ca31bf082e49095292da043/lib/oidc/endpoints/token.ts#L87-L94 are correct in my environment. It includes an appropriate list of scopes in the expected format, as well as the other parameters I'd expect for the /token call to renew with refresh token. Hope this helps narrow it down.

**Comment by arvindkrishnakumar-okta** [comment]
@jeffg-hpe Thanks for reporting this!

@aarongranick-okta / @shuowu-okta Can you help with this?

**Comment by aarongranick-okta** [comment]
@jeffg-hpe Are you using custom storage keys to put tokens in non-standard locations? If you are able to place a breakpoint on the exception it would  be very helpful to see what object is being passed to renew.

**Comment by jeffg-hpe** [comment]
> Are you using custom storage keys to put tokens in non-standard locations?

Token is stored in session storage under `okta-token-storage`

I logged the value for `args` in `postRefreshToken` linked above, and it generates this string:
```
client_id=<ID>&grant_type=refresh_token&scope=offline_access%20profile%20openid%20email&refresh_token=<TOKEN>
```
I masked the values for client ID and refresh token. The values look correct to me.

Specifically this is the code I logged the output of:
```
    args: Object.entries({
      client_id: options.clientId, // eslint-disable-line camelcase
      grant_type: 'refresh_token', // eslint-disable-line camelcase
      scope: refreshToken.scopes.join(' '),
      refresh_token: refreshToken.refreshToken, // eslint-disable-line camelcase
    }).map(function ([name, value]) {
      return name + '=' + encodeURIComponent(value);
    }).join('&'),
```

**Comment by jeffg-hpe** [comment]
Specifically, I think this is getting called but the token is a refresh token:

https://github.com/okta/okta-auth-js/blob/e39e66db2e24df1e1ca31bf082e49095292da043/lib/oidc/renewToken.ts#L36-L39

**Comment by aarongranick-okta** [comment]
@jeffg-hpe thanks for the information. I believe I was able to reproduce the issue locally, and I am working on a fix now. Hopefully should be verified and released within the next few days.

**Comment by shuowu** [comment]
@jeffg-hpe Can you try okta-auth-js version 5.2.1? The newly released patch should handle the refresh token issue properly.
