### ISSUE TITLE
State not being returned when using getWithRedirect

### ISSUE THREAD

**Issue by rorygrandin** [okta/okta-auth-js#850]
We've just updated from using okta-auth-js 4.0.2 to 5.1.1, and the state is no longer returned when using getWithRedirect. I've tracked it down to [this ](https://github.com/okta/okta-auth-js/pull/567) pull request. I've got a fix for this (I think) which shouldn't have any impact on anything else, which I'll make a pull request for shortly.

Note that this may be the same issue as https://github.com/okta/okta-auth-js/issues/598, and fixing one should fix the other.

**Comment by shuowu** [comment]
@rorygrandin Thanks for the contribution! While we are review the PR, can you sign an CLA as described at - https://developer.okta.com/cla/

**Comment by shuowu** [comment]
Link PR #851

**Comment by rorygrandin** [comment]
@shuowu updated the PR description to indicate that I think it's probably an obvious fix. If not, let me know.

**Comment by shuowu** [comment]
@rorygrandin The fix has been released in [v5.3.0](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.3.0)
