### ISSUE TITLE
transformAuthState on OktaAuthOptions - typescript issue with OktaAuth parameter

### ISSUE THREAD

**Issue by dean-dot-git** [okta/okta-auth-js#857]
I'm getting the following type error when applying the OktaAuth type to the oktaAuth parameter:

![image](https://user-images.githubusercontent.com/86485757/125298340-a9dea780-e2ed-11eb-936b-337f6084a17d.png)

I'm using v5.2.0 of @okta/okta-auth-js.

This is reproducible by just specifying the type on the parameter.

**Comment by laura-rodriguez** [comment]
Hi @dean-dot-git,

Thanks for reporting this issue. 

Someone from our JS team will take a look soon.

**Comment by shuowu** [comment]
Internal ref: OKTA-411084

**Comment by shuowu** [comment]
@dean-dot-git okta-auth-js exposes type for `OktaAuthOptions`, you can use it directly when you declare the configs. 

```
import { OktaAuthOptions } from '@okta/okta-auth-js';
```

See details [here](https://github.com/okta/okta-auth-js/blob/5.2/lib/types/OktaAuthOptions.ts)

**Comment by dean-dot-git** [comment]
![image](https://user-images.githubusercontent.com/86485757/125824323-5fea4dae-5748-4dae-884f-89bb5db6ee39.png)

By doing this, it solved the issue.  Please close this issue.  It was my mistake.
