### ISSUE TITLE
Issue signing in using Okta on iOS 9 

### ISSUE THREAD

**Issue by Connor-Knabe** [okta/okta-auth-js#86]
We have a Javascript application that seems to have login issues with Safari on iOS 9.  We don't have a specific error (seems like sign in function isn't working) but I do know iOS 10+ works and all other browsers we support seem to be working fine.  Does anyone know if this is a known issue or of a possible fix/workaround? Thanks!

**Comment by lboyette-okta** [comment]
This isn't a known issue, thanks for reporting! We'll try to repro and get back to you

**Comment by lboyette-okta** [comment]
I can't reproduce your issue using `@okta/okta-auth-js@1.11.0` on Safari iOS 9.3:

```html
<script
  src='https://ok1static.oktacdn.com/assets/js/sdk/okta-auth-js/1.11.0/okta-auth-js.min.js'
  type='text/javascript'></script>

<body>
  <script>
    const authClient = new OktaAuth({
      url: 'your domain'
    });

    authClient.signIn({
      username: 'uname',
      password: 'pw'
    })
    .then(function(result) {
      alert(JSON.stringify(result));
    })
    .catch(function(error) {
      alert(error);
    });
  </script>
</body>
```

**Comment by Connor-Knabe** [comment]
@lboyette-okta we'll keep investigating and will follow back up if we narrow down issue or replication steps. Thanks!
