### ISSUE TITLE
Token manager event constants not available in Jest

### ISSUE THREAD

**Issue by darkowic** [okta/okta-auth-js#868]
The package exports constants for [token manager events](https://github.com/okta/okta-auth-js#tokenmanageronevent-callback-context):
```ts
import {
    EVENT_ADDED,
    EVENT_EXPIRED,
    EVENT_RENEWED,
    EVENT_ERROR,
    EVENT_REMOVED,
} from '@okta/okta-auth-js';
```
The constants are not available in Jest. This is because of the different builds for es modules and for cjs.
Browser:
<img width="610" alt="Screenshot 2021-07-16 at 16 45 27" src="https://user-images.githubusercontent.com/11510581/125965933-cd2cba44-36b5-4717-b1c8-6238eb30bbb6.png">
Jest:
<img width="531" alt="Screenshot 2021-07-16 at 16 46 21" src="https://user-images.githubusercontent.com/11510581/125966065-febb12af-be39-48c5-a08f-70ec4d01c462.png">

Version: 4.8.0

**Comment by shuowu** [comment]
@darkowic Can you try the version 5.x? as it exposes isomorphic APIs for both browser and node envs, the issue should be addressed with the upgrading.

**Comment by darkowic** [comment]
I was afraid of this question :D 

I can not fully upgrade at the moment but I was able to run it with v5 and the events are there (and many more helpers than previously).

Thanks!

**Comment by shuowu** [comment]
Another option would be using the jest.moduleNameMapper, you can find example [here](https://github.com/okta/samples-js-react/blob/master/okta-hosted-login/package.json#L47)

**Comment by darkowic** [comment]
Great! This is what I need! Thanks 🚀
