### ISSUE TITLE
Token Storage

### ISSUE THREAD

**Issue by GlennDOrr** [okta/okta-auth-js#87]
In the code of TokenManager I see the option of storing the token in sessionStorage instead of localStorage. I'm not sure how to set the options to accomplish this?

**Comment by GlennDOrr** [comment]
Found it:

 oktaAuth = new OktaAuth({
    url: 'https://myinstance.okta.com', 
    clientId: 'myid',
    issuer: 'https://myinstance.okta.com/oauth2/default', 
    redirectUri: 'http://amp.local:1234/callback/',
    tokenManager: { storage: 'sessionStorage'}
  });

Please let me know if you plan to continue to support this.

**Comment by lboyette-okta** [comment]
@GlennDOrr We do plan to continue to support it! We just need to document it
