### ISSUE TITLE
signInWithCredentials should send the request with { withCredentials: true }

### ISSUE THREAD

**Issue by x87** [okta/okta-auth-js#877]
Hi,

After a breaking change #677 in v5.0 `withCredentials` option has become `false` by default, so the browser does not attach the cookies to http requests. 

Most of the API methods were updated except one for `signInWithCredentials` that makes a call to `api/v1/authn` without cookies attached. This prevents OKTA from getting the `DT` cookie and thus skipping mandatory MFA flow if the device had gone through the MFA already, so it always returns back status `MFA_REQUIRED`. 

It worked fine with SDK v4.x.

`signInWithCredentials` itself does not allow to customize the http requests ([options are private](https://github.com/okta/okta-auth-js/blob/e39e66db2e24df1e1ca31bf082e49095292da043/lib/OktaAuth.ts#L293)). 

Please either allow to customize the http request by exposing fetch options to `signInWithCredentials`, or add the default value of `{ withCredentials: true }` to [this request](https://github.com/okta/okta-auth-js/blob/e39e66db2e24df1e1ca31bf082e49095292da043/lib/OktaAuth.ts#L295).

**Comment by shuowu** [comment]
@x87 Thanks for reporting the issue! We'll prioritize and release a patch for it soon.

Internal Ref: OKTA-415464

**Comment by x87** [comment]
Also related to that, `{ withCredentials: true }` should be included to `postToTransaction` call:
https://github.com/okta/okta-auth-js/blob/31d894324d5461351ae9c5319322377b7b60326d/lib/tx/AuthTransaction.ts#L188

without that, cookies are not attached to the `verify` call. Next time you log in, you will get `MFA_REQUIRED` again from `/authn`.

Note that `{ withCredentials: true }` has been added to [GET requests](https://github.com/okta/okta-auth-js/blob/31d894324d5461351ae9c5319322377b7b60326d/lib/tx/AuthTransaction.ts#L128), but not POST.

**Comment by shuowu** [comment]
Resolved in version 5.3.1
