### ISSUE TITLE
How can I retrieve the randomly generated state parameter after calling token.getWithRedirect?

### ISSUE THREAD

**Issue by zachauten** [okta/okta-auth-js#882]
For context, I'm implementing the OIDC authorization code flow + PKCE. My understanding is that using the nonce isn't necessary for this case, but validating with the state param is still best practice. 

The README states: `A client-provided string that will be passed to the server endpoint and returned in the OAuth response. The value can be used to validate the OAuth response and prevent cross-site request forgery (CSRF). Defaults to a random string.`

If I allow okta-auth-js to generate a string for the state parameter, is there a way I can retrieve it so that it can be saved in storage, and compared to the value in the response? If I need to generate the value myself in order to use the state parameter, do you have a recommended way of doing that?

Thanks!

**Comment by shuowu** [comment]
Relates to #850

**Comment by zachauten** [comment]
@shuowu I guess i overlooked that issue, it looks like it's the same as this one. I'll close this!

**Comment by zachauten** [comment]
Actually I'm not 100% sure this is the same as #850, I'll reopen and let you guys decide.

**Comment by shuowu** [comment]
@zachauten The issue is resolved in [v5.3.0](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.3.0).
