### ISSUE TITLE
5.4.0 Causes Angular 8 Compilation Errors

### ISSUE THREAD

**Issue by jpspringall** [okta/okta-auth-js#929]
Hi, 
For a couple reasons we are tied to Angular 8.x
This ties us to TypeScript 3.5.3

As part of the 5.4.0 release 
in the file: lib\index.ts the crypto util is exported:

However it is exported using the shorthand:
export * as crypto from './crypto';

This syntax was introduced as part Typescript 3.8

So is causing us a compilation issue with one of our libraries:
ERROR: ../../node_modules/@okta/okta-auth-js/lib/index.d.ts(24,10): error TS1005: 'from' expected.
../../node_modules/@okta/okta-auth-js/lib/index.d.ts(24,13): error TS1005: ';' expected.
../../node_modules/@okta/okta-auth-js/lib/index.d.ts(24,20): error TS1005: ';' expected.
../../node_modules/@okta/okta-auth-js/lib/index.d.ts(24,25): error TS1005: ';' expected.

I was wondering if it would be possible to revert to the non shorthand version:
import * as crypto from "./crypto";
export { crypto };

I do have a PR ready to go, if people are happy  for the change to go in.

Cheers

James

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reporting this @jpspringall.

We might want to generate(e.g. `downlevel-dts`) types for older TS version for this SDK.
I will bring this up in a team meeting to see if it is feasible to implement.

Internal Ref: OKTA-426046

**Comment by jpspringall** [comment]
Thanks @oleksandrpravosudko-okta,

Once it's been discussed could you let me know the outcome?

Cheers

James

**Comment by oleksandrpravosudko-okta** [comment]
@jpspringall it was decided to postpone implementing support of type definitions for older TS versions for now.

@shuowu went ahead and created a PR to replace the offending syntax: https://github.com/okta/okta-auth-js/pull/931

Thanks for catching this.

**Comment by jpspringall** [comment]
Thank you sir

**Comment by shuowu** [comment]
@jpspringall The fix has been released in [5.4.3](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.4.3). Closing this issue.
