### ISSUE TITLE
RefreshToken incorrectly inherits accessToken's expiration

### ISSUE THREAD

**Issue by shanehenning** [okta/okta-auth-js#945]
Hello!

We've set an expiration duration in our okta admin dashboard for the refreshToken that is different from our accessToken's duration. But we're seeing the refreshToken having the same expiration as the accessToken. It looks as though this is a [known issue](https://github.com/okta/okta-auth-js/blob/master/lib/oidc/handleOAuthResponse.ts#L102)? 
Here's a quick screenshot of our tokens:
<img width="577" alt="refreshToken-expiration" src="https://user-images.githubusercontent.com/18336735/134266741-b74898ec-b849-4751-95ed-60c068abc460.png">

Until that release, is there a way to get the refreshToken expiration that we've set in our dashboard?

We're hoping to have our refreshToken last for a few hours after the accessToken expires, so that we can use the refreshToken to retrieve a new accessToken (some time after the accessToken has expired & been removed).

Thanks for your help, hope you're having a great day!

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reaching out @shanehenning.

You could try [`introspecting`](https://developer.okta.com/docs/reference/api/oidc/#introspect) the refresh token after it is obtained to get its dashboard-configured expiration, parse the response and set it into token storage.

**Comment by shanehenning** [comment]
Thanks for the quick response, @oleksandrpravosudko-okta!
That looks like it will work out great, thanks for the tip!

**Comment by shanehenning** [comment]
Before closing, I should've asked--@oleksandrpravosudko-okta, if there's a method in this SDK to introspect, or if I'll need to hit the endpoint you linked in your suggestion? I don't see anything in this package's readme about introspecting.

**Comment by oleksandrpravosudko-okta** [comment]
Currently there is no SDK method for introspecting OIDC tokens - you will need to hit the endpoint using non-SDK code.

I have created a ticket for team to consider adding such method:
Internal Ref: OKTA-430783

**Comment by shanehenning** [comment]
Terrific, thank you for closing the loop on that, @oleksandrpravosudko-okta! We'll look into the endpoint then.
