### ISSUE TITLE
Compilation failed angular. 

### ISSUE THREAD

**Issue by guptaji21** [okta/okta-auth-js#946]
hi, the compilation for the okta app is failing. https://developer.okta.com/code/angular/okta_angular_sign-in_widget/#add-an-openid-connect-client document referred. error while compiling :- error in node_modules/@okta/okta-auth-js/lib/idx/cancel.d.ts(14,87): error ts1005: '>' expected. node_modules/@okta/okta-auth-js/lib/idx/cancel.d.ts(14,120): error ts1109: expression expected. node_modules/@okta/okta-auth-js/lib/idx/remediators/authenticatorverificationdata.d.ts(23,30): error ts1110: type expected. node_modules/@okta/okta-auth-js/lib/idx/remediators/authenticatorverificationdata.d.ts(23,37): error ts1003: identifier expected. node_modules/@okta/okta-auth-js/lib/idx/remediators/authenticatorverificationdata.d.ts(23,55): error ts1144: '{' or ';' expected. node_modules/@okta/okta-auth-js/lib/idx/remediators/authenticatorverificationdata.d.ts(23,75): error ts1005: '=' expected. node_modules/@okta/okta-auth-js/lib/idx/remediators/authenticatorverificationdata.d.ts(24,21): error ts1005

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report @guptaji21.

Could you please specify which okta-auth-js, okta-angular and Angular versions you are using?

**Comment by guptaji21** [comment]
![Uploading IMG_20210922_185221.jpg…]()

**Comment by guptaji21** [comment]
![IMG_20210922_185157](https://user-images.githubusercontent.com/29679195/134351666-802076ee-81b5-484d-93a1-546af3d8eb2f.jpg)

**Comment by guptaji21** [comment]
![Uploading IMG_20210922_185221.jpg…]()

**Comment by guptaji21** [comment]
Angular version is 5.2.5
Ts is 2.5.3

**Comment by oleksandrpravosudko-okta** [comment]
Is there an upgrade option available for you?
`okta-angular` is not confirmed to be working with Angular <7:

```
This library has been tested for compatibility with the following Angular versions: 7, 8, 9, 10, 11, 12 ⚠️ Angular versions older than 7 may not be fully compatible with all dependencies of this library
```

**Comment by guptaji21** [comment]
The entire application uogradation is not possible at the moment.
By any chance we can integrate Okta in angular 5?

**Comment by oleksandrpravosudko-okta** [comment]
Angular 5/TS2.x support is unlikely to be prioritized.

You could try picking older okta-angular version (e.g. 1.3.0) for dev testing purposes - it is not recommended to use it in production app.
