### ISSUE TITLE
Add custom logic to redirect

### ISSUE THREAD

**Issue by harrydema** [okta/okta-auth-js#958]
Is there a way to modify the tokens.getWithRedirect? I need to add logic to the way it is redirecting as I am not working on a browser.

I am working on another environment that is not browser-based. You can think of an electron app (not using electron, but it is a good example). I need to redirect the user to the browser in order to login.

It would be helpful a function that retrieves the URL to where the user should be redirected so I can manually redirect him.

**Comment by shuowu** [comment]
@harrydema `tokens.getWithRedirect` is a browser only method, and no custom hooks is available to extend the implementation right now. 

For non browser-based js app, you may try the [idx module](https://github.com/okta/okta-auth-js/blob/master/docs/idx.md) (still in early access stage), it can communicate with Okta Identity Engine via xhr requests, which should be platform agnostic.

**Comment by harrydema** [comment]
@shuowu Thanks for the help!

It looks idx module is not compatible with idpDiscovery. It only provides a method to signin with email/password.

is there a way to do a sso signin?

**Comment by shuowu** [comment]
@harrydema the `idx` module does support idpDiscovery. You can have access to the available idps from `idx.startTransaction` method. See [sample code](https://github.com/okta/okta-auth-js/blob/master/samples/generated/express-embedded-auth-with-sdk/web-server/routes/login.js#L43).

For the `token.getWithRedirect` method, you probably can hack it by overriding the `_setLocation` function of it. See code detail [here](https://github.com/okta/okta-auth-js/blob/master/lib/OktaAuth.ts#L235).

**NOTE**:  it's NOT a public maintained API, which means the implementation may be changed/removed in the future versions as a non-breaking change.

**Comment by harrydema** [comment]
Thanks! I ended up doing that. I override the _setLocation and that worked!
