### ISSUE TITLE
Wrong typing for AuthState

### ISSUE THREAD

**Issue by ojathelonius** [okta/okta-auth-js#962]
Hi,

In latest v5.x, according to the docs, `getAuthState` can now return `null` while authentication flow is still pending. The default value for internal `_state` is `null` as well.

This seems wrong considering the signatures for `getAuthState` and `updateAuthState` which should always return `AuthState` and not `AuthState | null`. Similarly, internal `_state` type is `AuthState`.

This is currently allowed by `strictNullChecks: false` in `tsconfig.json`.

This can be a (minor) issue for projects that have a stricter TypeScript config, which causes a mismatch between possible `authState` value and its type. Would it be possible to have something like a `AuthState | null` discriminated union type instead ?

**Comment by shuowu** [comment]
@ojathelonius Thanks for the suggestion!

Internal Ref: OKTA-433337

**Comment by ahmednkhan24** [comment]
Is there any documentation explaining why `isPending` was removed from the `authState` object, and why `authState` potentially being `null` is an improvement to the overall SDK?
