### ISSUE TITLE
Custom Login Page: Okta Auth JS with React with latest versions

### ISSUE THREAD

**Issue by chinanderm** [okta/okta-auth-js#964]
I'm currently using `@okta/okta-auth-js` v4 and `@okta/okta-react` v5. In an effort to stay current and avoid using retired versions, I'm trying to upgrade to v6 of `@okta/okta-react` but it requires an upgrade to v5 of `@okta/okta-auth-js`. I'm running into some troubles with the upgrade to v5 of `@okta/okta-auth-js`, specifically in the context of supporting my own custom sign in page.

The example document on the Okta developer website for [Okta Auth JS and React](https://developer.okta.com/code/react/okta_react/) is out of date and is what I originally based my implementation off of.

Here is my current flow for authenticating the user after collecting user's email and password:
```
import { oktaAuth} from 'path-to-okta-auth-config'

type AuthProps = {
  password: string
  username: string
}

export default function authenticate(props: AuthProps): Promise<void> {
  const { password, username } = props

  return new Promise<void>((_, reject) => {
    oktaAuth.signInWithCredentials({
      username,
      password,
    })
      .then(response => {
        if (response.status === 'SUCCESS') {
          oktaAuth.signInWithRedirect({ sessionToken: response.sessionToken })
        } else {
         // handle
        }
      })
      .catch(() => {
        // handle
      })
  })
}

```
After upgrading to latest `@okta/okta-auth-js`, the `signInWithRedirect` method has completely changed and no longer accepts a `sessionToken`.  The current flow works well in that after calling `signInWithRedirect` the user gets routed to the configured `redirectUri` with query params of `code` and `state`, `react-router` routes that path to the `LoginCallback` component from `okta-react` and then my user is logged in.

**_How can I continue to have a similar flow with v6 of `okta-auth-js` with support of `okta-react`? I'd greatly appreciate any help._**

I've instead tried to use `oktaAuth.session.setCookieAndRedirect(response.sessionToken, window.location.origin)` but the `redirectUri` isn't getting hit in the same way, thus the auth'd user isn't set in local storage and cookies and I get sent right back to the login page because `okta-react` doesn't see the user as logged in.

```
import { toRelativeUrl } from '@okta/okta-auth-js'
import { LoginCallback, SecureRoute, Security } from '@okta/okta-react'
// ... other imports ...

const oktaCallbackUrl = '/implicit/callback'
const oktaAuthConfig: OktaAuthOptions = {
  clientId: '...',
  issuer: '...',
  redirectUri: window.location.origin + oktaCallbackUrl,
}
export const oktaAuth = new OktaAuth(oktaAuthConfig)

const App: React.FC = () => {

  const history = useHistory()

  const routeToLoginPage = () => {
    history.push(routes.login)
  }

  const restoreOriginalUri = async (_: unknown, originalUri: string) => {
    history.replace(toRelativeUrl(originalUri, window.location.origin))
  }

  return (
      <Security
        oktaAuth={oktaAuth}
        onAuthRequired={routeToLoginPage}
        restoreOriginalUri={restoreOriginalUri}
      >
        <Switch>
          <Route path="/login" exact>
            <LoginPage />
          </Route>
          <Route path={oktaCallbackUrl}>
            <LoginCallback />
          </Route>
          <SecureRoute path='/'>
            <MySecureAppComponent />
          </SecureRoute>
        </Switch>
      </Security>
  )
}
```

**Comment by shuowu** [comment]
@chinanderm You code looks correct, I believe it's most probably caused by a known type issue. And there is a PR for it: https://github.com/okta/okta-auth-js/pull/960

Also, you can find an update to date sample here: https://github.com/okta/okta-react/blob/master/generated/samples/doc-direct-auth/src/LoginForm.jsx

**Comment by chinanderm** [comment]
Thank you @shuowu! I didn't think to just try it, despite the types issue and sure enough, works as expected. I've added a `@ts-expect-error` comment and noted the PR. I really appreciate your quick review and comment. Going to close this.
