### ISSUE TITLE
Support for SMART on FHIR launch

### ISSUE THREAD

**Issue by CambianRwalker** [okta/okta-auth-js#984]
There is no way to add additional parameters that would support [SMART on FHIR launch](http://www.hl7.org/fhir/smart-app-launch/#ehr-launch-sequence).  Simplistically all this requires is to allow an additional parameter (in this case "launch") that can be passed to the /authorize endpoint.  The endpoint can ignore that parameter, but since the entire URL with parameters are provided when the [Okta Inline Token Hook](https://developer.okta.com/docs/reference/token-hook/) is called the contents of that launch parameter is available, and from that, can be used to provide the context to inject during the minting of the JWT access token.

As an aside, It would of course be nice if there was no need to part the URL parameters within the Inline Token Hook.  If you take a look at the definition of the [JSON payload](https://developer.okta.com/docs/reference/token-hook/#sample-json-payload-of-a-request) that is passed into the Inline Token Hook I could currently retrieve this launch parameter from the URL at:

<payloadRoot>.data.context.request.url.value

That is, retrieve this value and parse that URL value to find the launch parameter and value that had been passed to the /authorize endpoint.

The issue description to this point would be adequate to allow SMART on FHIR launch and only impacts the okta-auth-js Javascript library.

Extension:
To extend this solution, it would be much nicer if I could pull the launch parameter from the "**<payloadRoot>.data.context.protocol.request**" sub structure within the [payload passed to the hook](https://developer.okta.com/docs/reference/token-hook/#sample-json-payload-of-a-request).  From that example, that substructure contains many of the parameters relevant to the /authorize call, including state.  As a workaround to the issue I'm identifying here, I am currently using the state parameter instead, and so pull the state parameter from this substructure.  While use of the state parameter is a reasonable short term workaround for the missing functionality this issue identifies, it will not be compliant to the SMART on FHIR launch standard.  So it would be nice to pull the launch parameter from this substructure.

Okta Inline Token Hook payload:
_{
  "source": "https://${yourOktaDomain}/oauth2/default/v1/authorize",
  "eventId": "3OWo4oo-QQ-rBWfRyTmQYw",
  "eventTime": "2019-01-15T23:20:47.000Z",
  "eventTypeVersion": "1.0",
  "cloudEventVersion": "0.1",
  "contentType": "application/json",
  "eventType": "com.okta.oauth2.tokens.transform",
  "**data**": {
    "**context**": {
      "request": {
        "id": "reqv66CbCaCStGEFc8AdfS0ng",
        "method": "GET",
        "url": {
          "value": "https://${yourOktaDomain}/oauth2/default/v1/authorize?scope=openid+profile+email&response_type=token+id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fget&state=foobareere&nonce=asf&client_id=customClientIdNative"
        },
        "ipAddress": "127.0.0.1"
      },
      "**protocol**": {
        "type": "OAUTH2.0",
        "**request**": {
          "scope": "openid profile email",
          "state": "foobareere",
          **"launch": "123",**              **<==  Proposal of where the proposed launch parameter could be added**
          "redirect_uri": "https://httpbin.org/get",
          "response_mode": "fragment",
          "response_type": "token id_token",
          "client_id": "customClientIdNative"
        },
...
...
..._

**Comment by shuowu** [comment]
Released in [5.9.0](https://github.com/okta/okta-auth-js/releases/tag/okta-auth-js-5.9.0)
