### ISSUE TITLE
Being redirected to Okta's branded login page instead of my login page.

### ISSUE THREAD

**Issue by thm-design** [okta/okta-auth-js#99]
Hi, I am running into some weird behaviour that I have been trying to figure out for weeks, even doing a support session with an Okta dev to no avail. 

I am using the accesstoken from `signIn()` in to validate api calls to the backend of my app (express). I am validating the token with `'@okta/jwt-verifier'`

```
oktaJwtVerifier.verifyAccessToken(accessTokenString).then((jwt) ... etc..
```

When the verification fails, I log the user out with:
```
    oktaAuth.signOut().then(() => {
      oktaAuth.tokenManager.clear()
      history.push('/')

      dispatch({
        type: LOGOUT_COMPLETE
      })

      dispatch(resetUser()) // clear redux state and redux-persist state
    })
```

This works fine if the token becomes invalid while using the app continuously.

The problem arises If I leave the computer alone for a longer period of time with out using it. Or if I close my laptop for example and open it the next day with the app still how it was (logged in), when I then click something and the `accessToken` validation fails, the app will redirect to Okta's branded login page instead of staying on in my app. And sometimes then after that if I go back to my login page and try to login, I get immediately get logged out again. After that logging/out in works normally.

Am I missing any steps for this situation? (logging the user out when the token becomes invalid). The Okta developer I spoke with felt like I was missing some handling with the session token directly.

Any help is greatly appreciated.

**Comment by thm-design** [comment]
I would be also be happy for now if I could just make sure the accessToken and Session are never expired.

**Comment by jmelberg-okta** [comment]
Hey @thm-design!

Help me clarify a couple of things. When the `accessToken` is invalid, you're pushing users to your root path `/`. How are you determining if the user is authenticated or not?

Secondly, what methods are you using to bootstrap the login flow? Are you using the [`signin`](https://github.com/okta/okta-auth-js#signinoptions) method to return a `sessionToken`, then passing this to [`token.getWithoutPrompt()`](https://github.com/okta/okta-auth-js#tokengetwithoutpromptoauthoptions)?

**Comment by thm-design** [comment]
Hey! Thanks for replying.

1 ) In the root I check authentication like so:
```
    checkAuthentication = async () => {
      const authenticated = await this.props.auth.isAuthenticated()
      if (authenticated !== this.state.authenticated) {
        this.setState({authenticated})
      }
    }
```
`auth` is passed in by the `withAuth()` hoc provided by '@okta/okta-react'.

2 ) Yes I am using the `signIn` method to get a `sessionToken`, but using this `auth.redirect({sessionToken})` also from the `okta-react` package: https://github.com/okta/okta-oidc-js/tree/master/packages/okta-react#authredirectsessiontoken

This tutorial guided most of the authentication steps I have implemented: https://scotch.io/tutorials/add-user-registration-to-your-site-with-node-react-and-okta

**Comment by jmelberg-okta** [comment]
Are you by chance using the `1.0.0` version of `@okta/okta-react`?

If so, you'll want to make sure to call your login method with a `path` parameter:

```typescript
auth.redirect({sessionToken});

// Should become
const redirectPathAfterLogin = '/profile';
auth.redirect(redirectPathAfterLogin, {sessionToken});
```

I *think* this is why you're always redirecting back to the Okta login page, since the `sessionToken` isn't being picked up properly.

Can you try that and let me know what happens?

**Comment by thm-design** [comment]
Hey, I am actually using `0.0.12` . o: Will update that package and try your suggestion. Thank you sir!

**Comment by thm-design** [comment]
Hey @jmelberg-okta I updated to 1.0.0, and tried adding the path param in `.redirect(path, {sessionToken})`. But that caused the app to immediately redirect to the Okta login page on when trying to login (`signIn()`).

I see in the release notes the path was added, for `login()` is that what you meant? I tried adding it to the `signOn()` method I am using and didn't work either.

That's fine. Increasing the session duration to 90days seems to have helped temporarily. It seems that maybe calling the logout (okta-auth-js) method when the session is expired might be causing my originally described redirects.

I will leave it like this for now. And keep an eye on it

Feel free to close this, I will open another ticket if the problem resurfaces. Thanks for your help thus far!

**Comment by jmelberg-okta** [comment]
@thm-design - Good to hear! Please let us know if any other issues come up!

**Comment by shogan94** [comment]
I'm sorry I don't understand what the solution was? I'm running into the same problem as well, though only in chrome. Firefox works fine.

I create a login request with 
```
export const login = credentials => {
  return dispatch => {
    dispatch(dispatchToReducer(LOGIN));
    oktaAuth
      .signIn(credentials)
      .then(res => {
        dispatch(loginSuccess(res));
        dispatch(getGroup(res.user.id));
        dispatch(getJwt(res.sessionToken));
        dispatch(updateAll(res.user.id));
      })
      .catch(err => {
        dispatch(loginFailure( err));
      });
  };
};

And at this point I have my users info, session token, etc. So I call...

```
```
  async componentDidUpdate(prevProps) {
    if (this.props.authenticated && !prevProps.authenticated) {
      const auth = await this.props.auth;
      auth.redirect('/', { sessionToken: this.props.sessionToken });
    }
  }
```

I tried adding the suggested path, but that still doesn't work. It always redirects to Oktas web site.

On chromes console, there is a warning also 

> HTTP-Based Public Key Pinning is deprecated. Chrome 69 and later will ignore HPKP response headers. (Host: dev-xxxxxx.oktapreview.com)

Not sure if that is relevant or not

**Comment by thm-design** [comment]
@shogan94 The issues still happens for me. Not sure what else to do at this point. Seems like it might be related to this: https://github.com/okta/okta-auth-js/issues/140
